INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, example_sentence, difficulty) VALUES
('hello', '안녕하세요', 'a greeting', 'Hello, how are you today?', 'beginner'),
('goodbye', '안녕히 가세요', 'farewell', 'Goodbye, see you tomorrow!', 'beginner'),
('thanks', '감사합니다', 'expression of gratitude', 'Thanks for your help!', 'beginner'),
('please', '부탁합니다', 'polite request', 'Please pass me the salt.', 'beginner'),
('sorry', '미안합니다', 'expression of apology', 'I am sorry for being late.', 'beginner'),
('yes', '네', 'affirmative', 'Yes, I agree with you.', 'beginner'),
('no', '아니요', 'negative', 'No, I cannot come today.', 'beginner'),
('okay', '좋아요', 'agreement', 'Okay, I will do it now.', 'beginner'),
('excuse', '실례합니다', 'polite interruption', 'Excuse me, where is the bathroom?', 'beginner'),
('welcome', '환영합니다', 'greeting arrival', 'Welcome to our home!', 'beginner'),
('be', '이다', 'to exist', 'I want to be a teacher.', 'beginner'),
('have', '가지다', 'to possess', 'I have a cat and a dog.', 'beginner'),
('do', '하다', 'to perform', 'What do you do for work?', 'beginner'),
('say', '말하다', 'to speak', 'What did you say?', 'beginner'),
('go', '가다', 'to move', 'Let us go to the park.', 'beginner'),
('come', '오다', 'to arrive', 'Please come to my party.', 'beginner'),
('make', '만들다', 'to create', 'She makes beautiful art.', 'beginner'),
('take', '가져가다', 'to grab', 'Take this book with you.', 'beginner'),
('get', '얻다', 'to obtain', 'I need to get some milk.', 'beginner'),
('see', '보다', 'to view', 'I see a bird in the tree.', 'beginner'),
('know', '알다', 'to understand', 'I know the answer.', 'beginner'),
('think', '생각하다', 'to consider', 'I think it will rain today.', 'beginner'),
('want', '원하다', 'to desire', 'I want to learn English.', 'beginner'),
('give', '주다', 'to provide', 'Can you give me a pen?', 'beginner'),
('use', '사용하다', 'to utilize', 'How do you use this phone?', 'beginner'),
('find', '찾다', 'to discover', 'I cannot find my keys.', 'beginner'),
('tell', '말하다', 'to inform', 'Tell me your name.', 'beginner'),
('ask', '묻다', 'to question', 'Can I ask you something?', 'beginner'),
('work', '일하다', 'to labor', 'I work at a hospital.', 'beginner'),
('call', '전화하다', 'to telephone', 'I will call you later.', 'beginner'),
('try', '시도하다', 'to attempt', 'Try to do your best.', 'beginner'),
('feel', '느끼다', 'to sense', 'I feel happy today.', 'beginner'),
('become', '되다', 'to change into', 'She became a doctor.', 'beginner'),
('leave', '떠나다', 'to depart', 'I will leave at 5 PM.', 'beginner'),
('put', '놓다', 'to place', 'Put the book on the table.', 'beginner'),
('mean', '의미하다', 'to signify', 'What does this word mean?', 'beginner'),
('keep', '유지하다', 'to maintain', 'Keep the door closed.', 'beginner'),
('let', '허락하다', 'to allow', 'Let me help you.', 'beginner'),
('begin', '시작하다', 'to start', 'Let us begin the lesson.', 'beginner'),
('seem', '~처럼 보이다', 'to appear', 'You seem tired today.', 'beginner'),
('help', '돕다', 'to assist', 'Can you help me please?', 'beginner'),
('show', '보여주다', 'to display', 'Show me your homework.', 'beginner'),
('hear', '듣다', 'to perceive sound', 'I hear music playing.', 'beginner'),
('play', '놀다', 'to engage in activity', 'Children play in the park.', 'beginner'),
('run', '달리다', 'to move quickly', 'I run every morning.', 'beginner'),
('move', '움직이다', 'to change position', 'Move your chair closer.', 'beginner'),
('like', '좋아하다', 'to enjoy', 'I like chocolate ice cream.', 'beginner'),
('live', '살다', 'to reside', 'Where do you live?', 'beginner'),
('believe', '믿다', 'to accept as true', 'I believe you are right.', 'beginner'),
('bring', '가져오다', 'to carry', 'Bring your book tomorrow.', 'beginner');
