-- Part 2: Words 51-100
INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, example_sentence, difficulty) VALUES
('document', '문서', 'a written record', 'Read this document carefully.', 'intermediate'),
('domestic', '국내의', 'relating to home', 'Domestic sales increased.', 'intermediate'),
('dominant', '지배적인', 'most powerful', 'English is the dominant language.', 'intermediate'),
('economy', '경제', 'financial system', 'The economy is growing.', 'intermediate'),
('efficient', '효율적인', 'working well', 'This is a very efficient method.', 'intermediate'),
('eliminate', '제거하다', 'to remove', 'We need to eliminate waste.', 'intermediate'),
('emerge', '나타나다', 'to appear', 'New problems emerged.', 'intermediate'),
('emphasis', '강조', 'special importance', 'Put emphasis on quality.', 'intermediate'),
('enable', '가능하게 하다', 'to make possible', 'This will enable us to work faster.', 'intermediate'),
('encounter', '마주치다', 'to meet', 'I encountered a problem.', 'intermediate'),
('enhance', '향상시키다', 'to improve', 'This will enhance performance.', 'intermediate'),
('ensure', '보장하다', 'to make certain', 'Please ensure everything is ready.', 'intermediate'),
('environment', '환경', 'surroundings', 'Protect the environment.', 'intermediate'),
('establish', '확립하다', 'to set up', 'We will establish new rules.', 'intermediate'),
('estimate', '추정하다', 'to calculate', 'I estimate it will take two hours.', 'intermediate'),
('evaluate', '평가하다', 'to assess', 'We need to evaluate the results.', 'intermediate'),
('evidence', '증거', 'proof', 'There is no evidence.', 'intermediate'),
('exceed', '초과하다', 'to go beyond', 'Sales exceeded expectations.', 'intermediate'),
('exclude', '제외하다', 'to leave out', 'This price excludes tax.', 'intermediate'),
('expand', '확장하다', 'to grow', 'We plan to expand our business.', 'intermediate'),
('expert', '전문가', 'specialist', 'Consult an expert.', 'intermediate'),
('explicit', '명확한', 'clear', 'Give explicit instructions.', 'intermediate'),
('expose', '노출시키다', 'to reveal', 'Do not expose it to sunlight.', 'intermediate'),
('external', '외부의', 'outside', 'External factors matter.', 'intermediate'),
('facilitate', '촉진하다', 'to make easier', 'This will facilitate communication.', 'intermediate'),
('factor', '요인', 'an element', 'Price is an important factor.', 'intermediate'),
('feature', '특징', 'characteristic', 'The main feature is speed.', 'intermediate'),
('finance', '재정', 'money management', 'Our finance team handles this.', 'intermediate'),
('flexible', '유연한', 'adaptable', 'Be flexible with your schedule.', 'intermediate'),
('focus', '집중하다', 'to concentrate', 'Focus on the main issue.', 'intermediate'),
('function', '기능', 'purpose', 'What is its function?', 'intermediate'),
('fundamental', '근본적인', 'basic', 'This is a fundamental principle.', 'intermediate'),
('generate', '생성하다', 'to create', 'This will generate profits.', 'intermediate'),
('goal', '목표', 'objective', 'Our goal is clear.', 'intermediate'),
('grant', '허가하다', 'to give', 'They granted permission.', 'intermediate'),
('guarantee', '보장하다', 'to promise', 'We guarantee quality.', 'intermediate'),
('guideline', '지침', 'recommendation', 'Follow these guidelines.', 'intermediate'),
('hence', '그러므로', 'therefore', 'Hence, we must act now.', 'intermediate'),
('highlight', '강조하다', 'to emphasize', 'Let me highlight key points.', 'intermediate'),
('identify', '식별하다', 'to recognize', 'Can you identify the problem?', 'intermediate'),
('illustrate', '설명하다', 'to show', 'This example illustrates the point.', 'intermediate'),
('impact', '영향', 'effect', 'It had a big impact.', 'intermediate'),
('implement', '실행하다', 'to carry out', 'We will implement new policies.', 'intermediate'),
('imply', '암시하다', 'to suggest', 'What does this imply?', 'intermediate'),
('impose', '부과하다', 'to force', 'They imposed new taxes.', 'intermediate'),
('indicate', '나타내다', 'to show', 'The data indicates growth.', 'intermediate'),
('individual', '개인', 'person', 'Each individual is different.', 'intermediate'),
('inevitable', '불가피한', 'unavoidable', 'Change is inevitable.', 'intermediate'),
('influence', '영향을 미치다', 'to affect', 'This will influence the outcome.', 'intermediate'),
('initial', '초기의', 'first', 'The initial reaction was positive.', 'intermediate';