-- WorVox Comprehensive Vocabulary Set (1000 words)
-- Beginner: 400 words | Intermediate: 300 words | Advanced: 300 words
-- Categories: Daily conversation, Business, Travel, TOEIC, TOEFL, Academic

-- BEGINNER LEVEL (400 words)
-- Category: Daily Conversation & Basic Words

INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, pronunciation, part_of_speech, example_sentence, difficulty, category, is_toeic, is_toefl, frequency_rank) VALUES

-- Basic Greetings & Common Phrases (50 words)
('hello', '안녕하세요', 'a greeting', '/həˈloʊ/', 'interjection', 'Hello, how are you today?', 'beginner', 'daily', 0, 0, 1),
('goodbye', '안녕히 가세요', 'farewell', '/ɡʊdˈbaɪ/', 'interjection', 'Goodbye, see you tomorrow!', 'beginner', 'daily', 0, 0, 2),
('thanks', '감사합니다', 'expression of gratitude', '/θæŋks/', 'noun', 'Thanks for your help!', 'beginner', 'daily', 0, 0, 3),
('please', '부탁합니다', 'polite request', '/pliːz/', 'adverb', 'Please pass me the salt.', 'beginner', 'daily', 0, 0, 4),
('sorry', '미안합니다', 'expression of apology', '/ˈsɑːri/', 'adjective', 'I am sorry for being late.', 'beginner', 'daily', 0, 0, 5),
('yes', '네', 'affirmative', '/jes/', 'adverb', 'Yes, I agree with you.', 'beginner', 'daily', 0, 0, 6),
('no', '아니요', 'negative', '/noʊ/', 'adverb', 'No, I cannot come today.', 'beginner', 'daily', 0, 0, 7),
('okay', '좋아요', 'agreement', '/oʊˈkeɪ/', 'adjective', 'Okay, I will do it now.', 'beginner', 'daily', 0, 0, 8),
('excuse', '실례합니다', 'polite interruption', '/ɪkˈskjuːs/', 'verb', 'Excuse me, where is the bathroom?', 'beginner', 'daily', 0, 0, 9),
('welcome', '환영합니다', 'greeting arrival', '/ˈwelkəm/', 'interjection', 'Welcome to our home!', 'beginner', 'daily', 0, 0, 10),

-- Basic Verbs (100 words)
('be', '이다', 'to exist', '/biː/', 'verb', 'I want to be a teacher.', 'beginner', 'general', 0, 0, 11),
('have', '가지다', 'to possess', '/hæv/', 'verb', 'I have a cat and a dog.', 'beginner', 'general', 0, 0, 12),
('do', '하다', 'to perform', '/duː/', 'verb', 'What do you do for work?', 'beginner', 'general', 0, 0, 13),
('say', '말하다', 'to speak', '/seɪ/', 'verb', 'What did you say?', 'beginner', 'general', 0, 0, 14),
('go', '가다', 'to move', '/ɡoʊ/', 'verb', 'Let us go to the park.', 'beginner', 'general', 0, 0, 15),
('come', '오다', 'to arrive', '/kʌm/', 'verb', 'Please come to my party.', 'beginner', 'general', 0, 0, 16),
('make', '만들다', 'to create', '/meɪk/', 'verb', 'She makes beautiful art.', 'beginner', 'general', 0, 0, 17),
('take', '가져가다', 'to grab', '/teɪk/', 'verb', 'Take this book with you.', 'beginner', 'general', 0, 0, 18),
('get', '얻다', 'to obtain', '/ɡet/', 'verb', 'I need to get some milk.', 'beginner', 'general', 0, 0, 19),
('see', '보다', 'to view', '/siː/', 'verb', 'I see a bird in the tree.', 'beginner', 'general', 0, 0, 20),
('know', '알다', 'to understand', '/noʊ/', 'verb', 'I know the answer.', 'beginner', 'general', 0, 0, 21),
('think', '생각하다', 'to consider', '/θɪŋk/', 'verb', 'I think it will rain today.', 'beginner', 'general', 0, 0, 22),
('want', '원하다', 'to desire', '/wɑːnt/', 'verb', 'I want to learn English.', 'beginner', 'general', 0, 0, 23),
('give', '주다', 'to provide', '/ɡɪv/', 'verb', 'Can you give me a pen?', 'beginner', 'general', 0, 0, 24),
('use', '사용하다', 'to utilize', '/juːz/', 'verb', 'How do you use this phone?', 'beginner', 'general', 0, 0, 25),
('find', '찾다', 'to discover', '/faɪnd/', 'verb', 'I cannot find my keys.', 'beginner', 'general', 0, 0, 26),
('tell', '말하다', 'to inform', '/tel/', 'verb', 'Tell me your name.', 'beginner', 'general', 0, 0, 27),
('ask', '묻다', 'to question', '/æsk/', 'verb', 'Can I ask you something?', 'beginner', 'general', 0, 0, 28),
('work', '일하다', 'to labor', '/wɜːrk/', 'verb', 'I work at a hospital.', 'beginner', 'general', 0, 0, 29),
('call', '전화하다', 'to telephone', '/kɔːl/', 'verb', 'I will call you later.', 'beginner', 'general', 0, 0, 30),
('try', '시도하다', 'to attempt', '/traɪ/', 'verb', 'Try to do your best.', 'beginner', 'general', 0, 0, 31),
('feel', '느끼다', 'to sense', '/fiːl/', 'verb', 'I feel happy today.', 'beginner', 'general', 0, 0, 32),
('become', '되다', 'to change into', '/bɪˈkʌm/', 'verb', 'She became a doctor.', 'beginner', 'general', 0, 0, 33),
('leave', '떠나다', 'to depart', '/liːv/', 'verb', 'I will leave at 5 PM.', 'beginner', 'general', 0, 0, 34),
('put', '놓다', 'to place', '/pʊt/', 'verb', 'Put the book on the table.', 'beginner', 'general', 0, 0, 35),
('mean', '의미하다', 'to signify', '/miːn/', 'verb', 'What does this word mean?', 'beginner', 'general', 0, 0, 36),
('keep', '유지하다', 'to maintain', '/kiːp/', 'verb', 'Keep the door closed.', 'beginner', 'general', 0, 0, 37),
('let', '허락하다', 'to allow', '/let/', 'verb', 'Let me help you.', 'beginner', 'general', 0, 0, 38),
('begin', '시작하다', 'to start', '/bɪˈɡɪn/', 'verb', 'Let us begin the lesson.', 'beginner', 'general', 0, 0, 39),
('seem', '~처럼 보이다', 'to appear', '/siːm/', 'verb', 'You seem tired today.', 'beginner', 'general', 0, 0, 40),
('help', '돕다', 'to assist', '/help/', 'verb', 'Can you help me please?', 'beginner', 'general', 0, 0, 41),
('show', '보여주다', 'to display', '/ʃoʊ/', 'verb', 'Show me your homework.', 'beginner', 'general', 0, 0, 42),
('hear', '듣다', 'to perceive sound', '/hɪr/', 'verb', 'I hear music playing.', 'beginner', 'general', 0, 0, 43),
('play', '놀다', 'to engage in activity', '/pleɪ/', 'verb', 'Children play in the park.', 'beginner', 'general', 0, 0, 44),
('run', '달리다', 'to move quickly', '/rʌn/', 'verb', 'I run every morning.', 'beginner', 'general', 0, 0, 45),
('move', '움직이다', 'to change position', '/muːv/', 'verb', 'Move your chair closer.', 'beginner', 'general', 0, 0, 46),
('like', '좋아하다', 'to enjoy', '/laɪk/', 'verb', 'I like chocolate ice cream.', 'beginner', 'general', 0, 0, 47),
('live', '살다', 'to reside', '/lɪv/', 'verb', 'Where do you live?', 'beginner', 'general', 0, 0, 48),
('believe', '믿다', 'to accept as true', '/bɪˈliːv/', 'verb', 'I believe you are right.', 'beginner', 'general', 0, 0, 49),
('bring', '가져오다', 'to carry', '/brɪŋ/', 'verb', 'Bring your book tomorrow.', 'beginner', 'general', 0, 0, 50),
('happen', '일어나다', 'to occur', '/ˈhæpən/', 'verb', 'What happened yesterday?', 'beginner', 'general', 0, 0, 51),
('write', '쓰다', 'to compose', '/raɪt/', 'verb', 'Write your name here.', 'beginner', 'general', 0, 0, 52),
('sit', '앉다', 'to be seated', '/sɪt/', 'verb', 'Please sit down.', 'beginner', 'general', 0, 0, 53),
('stand', '서다', 'to be upright', '/stænd/', 'verb', 'Stand up when you speak.', 'beginner', 'general', 0, 0, 54),
('lose', '잃다', 'to misplace', '/luːz/', 'verb', 'Do not lose your ticket.', 'beginner', 'general', 0, 0, 55),
('pay', '지불하다', 'to give money', '/peɪ/', 'verb', 'I will pay for dinner.', 'beginner', 'general', 0, 0, 56),
('meet', '만나다', 'to encounter', '/miːt/', 'verb', 'Let us meet at noon.', 'beginner', 'general', 0, 0, 57),
('include', '포함하다', 'to contain', '/ɪnˈkluːd/', 'verb', 'The price includes tax.', 'beginner', 'general', 0, 0, 58),
('continue', '계속하다', 'to persist', '/kənˈtɪnjuː/', 'verb', 'Please continue reading.', 'beginner', 'general', 0, 0, 59),
('set', '설정하다', 'to establish', '/set/', 'verb', 'Set the alarm for 7 AM.', 'beginner', 'general', 0, 0, 60),
('learn', '배우다', 'to acquire knowledge', '/lɜːrn/', 'verb', 'I want to learn Korean.', 'beginner', 'general', 0, 0, 61),
('change', '바꾸다', 'to alter', '/tʃeɪndʒ/', 'verb', 'Can you change this tire?', 'beginner', 'general', 0, 0, 62),
('lead', '이끌다', 'to guide', '/liːd/', 'verb', 'She will lead the team.', 'beginner', 'general', 0, 0, 63),
('understand', '이해하다', 'to comprehend', '/ˌʌndərˈstænd/', 'verb', 'I understand your problem.', 'beginner', 'general', 0, 0, 64),
('watch', '보다', 'to observe', '/wɑːtʃ/', 'verb', 'I watch TV every night.', 'beginner', 'general', 0, 0, 65),
('follow', '따르다', 'to go after', '/ˈfɑːloʊ/', 'verb', 'Follow me this way.', 'beginner', 'general', 0, 0, 66),
('stop', '멈추다', 'to cease', '/stɑːp/', 'verb', 'Stop talking and listen.', 'beginner', 'general', 0, 0, 67),
('create', '창조하다', 'to make', '/kriˈeɪt/', 'verb', 'Artists create beautiful works.', 'beginner', 'general', 0, 0, 68),
('speak', '말하다', 'to talk', '/spiːk/', 'verb', 'Can you speak English?', 'beginner', 'general', 0, 0, 69),
('read', '읽다', 'to look at words', '/riːd/', 'verb', 'I read a book yesterday.', 'beginner', 'general', 0, 0, 70),
('spend', '쓰다', 'to use money or time', '/spend/', 'verb', 'I spend too much money.', 'beginner', 'general', 0, 0, 71),
('grow', '자라다', 'to increase', '/ɡroʊ/', 'verb', 'Plants grow in spring.', 'beginner', 'general', 0, 0, 72),
('open', '열다', 'to unlock', '/ˈoʊpən/', 'verb', 'Open the window please.', 'beginner', 'general', 0, 0, 73),
('walk', '걷다', 'to move on foot', '/wɔːk/', 'verb', 'I walk to school.', 'beginner', 'general', 0, 0, 74),
('win', '이기다', 'to be victorious', '/wɪn/', 'verb', 'Our team will win today.', 'beginner', 'general', 0, 0, 75),
('teach', '가르치다', 'to educate', '/tiːtʃ/', 'verb', 'I teach English online.', 'beginner', 'general', 0, 0, 76),
('offer', '제공하다', 'to present', '/ˈɔːfər/', 'verb', 'Can I offer you coffee?', 'beginner', 'general', 0, 0, 77),
('remember', '기억하다', 'to recall', '/rɪˈmembər/', 'verb', 'I remember your birthday.', 'beginner', 'general', 0, 0, 78),
('consider', '고려하다', 'to think about', '/kənˈsɪdər/', 'verb', 'Consider all options first.', 'beginner', 'general', 0, 0, 79),
('appear', '나타나다', 'to become visible', '/əˈpɪr/', 'verb', 'Stars appear at night.', 'beginner', 'general', 0, 0, 80),
('buy', '사다', 'to purchase', '/baɪ/', 'verb', 'I will buy new shoes.', 'beginner', 'general', 0, 0, 81),
('wait', '기다리다', 'to remain', '/weɪt/', 'verb', 'Wait for me here.', 'beginner', 'general', 0, 0, 82),
('serve', '제공하다', 'to provide service', '/sɜːrv/', 'verb', 'They serve good food.', 'beginner', 'general', 0, 0, 83),
('die', '죽다', 'to cease living', '/daɪ/', 'verb', 'The flowers died quickly.', 'beginner', 'general', 0, 0, 84),
('send', '보내다', 'to dispatch', '/send/', 'verb', 'Send me an email.', 'beginner', 'general', 0, 0, 85),
('expect', '기대하다', 'to anticipate', '/ɪkˈspekt/', 'verb', 'I expect good results.', 'beginner', 'general', 0, 0, 86),
('build', '짓다', 'to construct', '/bɪld/', 'verb', 'They build houses fast.', 'beginner', 'general', 0, 0, 87),
('stay', '머물다', 'to remain', '/steɪ/', 'verb', 'Stay with me tonight.', 'beginner', 'general', 0, 0, 88),
('fall', '떨어지다', 'to descend', '/fɔːl/', 'verb', 'Leaves fall in autumn.', 'beginner', 'general', 0, 0, 89),
('cut', '자르다', 'to divide', '/kʌt/', 'verb', 'Cut the paper in half.', 'beginner', 'general', 0, 0, 90),
('reach', '도달하다', 'to arrive at', '/riːtʃ/', 'verb', 'We will reach soon.', 'beginner', 'general', 0, 0, 91),
('kill', '죽이다', 'to cause death', '/kɪl/', 'verb', 'Smoking kills people.', 'beginner', 'general', 0, 0, 92),
('remain', '남다', 'to stay', '/rɪˈmeɪn/', 'verb', 'Only two remain now.', 'beginner', 'general', 0, 0, 93),
('suggest', '제안하다', 'to propose', '/səɡˈdʒest/', 'verb', 'I suggest we leave early.', 'beginner', 'general', 0, 0, 94),
('raise', '올리다', 'to lift', '/reɪz/', 'verb', 'Raise your hand please.', 'beginner', 'general', 0, 0, 95),
('pass', '지나가다', 'to go by', '/pæs/', 'verb', 'Time passes quickly.', 'beginner', 'general', 0, 0, 96),
('sell', '팔다', 'to trade', '/sel/', 'verb', 'They sell fresh fruit.', 'beginner', 'general', 0, 0, 97),
('require', '필요하다', 'to need', '/rɪˈkwaɪər/', 'verb', 'This job requires skill.', 'beginner', 'general', 0, 0, 98),
('report', '보고하다', 'to inform', '/rɪˈpɔːrt/', 'verb', 'Report any problems.', 'beginner', 'general', 0, 0, 99),
('decide', '결정하다', 'to choose', '/dɪˈsaɪd/', 'verb', 'You must decide now.', 'beginner', 'general', 0, 0, 100),
('pull', '당기다', 'to drag', '/pʊl/', 'verb', 'Pull the door open.', 'beginner', 'general', 0, 0, 101),
('break', '부수다', 'to shatter', '/breɪk/', 'verb', 'Do not break the glass.', 'beginner', 'general', 0, 0, 102),
('pick', '고르다', 'to select', '/pɪk/', 'verb', 'Pick your favorite color.', 'beginner', 'general', 0, 0, 103),
('wear', '입다', 'to have on', '/wer/', 'verb', 'Wear a warm coat.', 'beginner', 'general', 0, 0, 104),
('enjoy', '즐기다', 'to take pleasure', '/ɪnˈdʒɔɪ/', 'verb', 'Enjoy your vacation!', 'beginner', 'general', 0, 0, 105),
('drive', '운전하다', 'to operate vehicle', '/draɪv/', 'verb', 'Can you drive a car?', 'beginner', 'general', 0, 0, 106),
('draw', '그리다', 'to sketch', '/drɔː/', 'verb', 'She draws very well.', 'beginner', 'general', 0, 0, 107),
('choose', '선택하다', 'to pick', '/tʃuːz/', 'verb', 'Choose one answer.', 'beginner', 'general', 0, 0, 108),
('cook', '요리하다', 'to prepare food', '/kʊk/', 'verb', 'I cook dinner daily.', 'beginner', 'general', 0, 0, 109),
('clean', '청소하다', 'to make tidy', '/kliːn/', 'verb', 'Clean your room now.', 'beginner', 'general', 0, 0, 110),

-- Basic Nouns (100 words)
('time', '시간', 'duration', '/taɪm/', 'noun', 'What time is it now?', 'beginner', 'general', 0, 0, 111),
('year', '년', 'period of 365 days', '/jɪr/', 'noun', 'Last year was great.', 'beginner', 'general', 0, 0, 112),
('people', '사람들', 'humans', '/ˈpiːpl/', 'noun', 'Many people came today.', 'beginner', 'general', 0, 0, 113),
('way', '방법', 'method', '/weɪ/', 'noun', 'Show me the way home.', 'beginner', 'general', 0, 0, 114),
('day', '날', 'period of 24 hours', '/deɪ/', 'noun', 'Have a nice day!', 'beginner', 'general', 0, 0, 115),
('man', '남자', 'adult male', '/mæn/', 'noun', 'That man is my father.', 'beginner', 'general', 0, 0, 116),
('thing', '것', 'object', '/θɪŋ/', 'noun', 'What is that thing?', 'beginner', 'general', 0, 0, 117),
('woman', '여자', 'adult female', '/ˈwʊmən/', 'noun', 'That woman is a doctor.', 'beginner', 'general', 0, 0, 118),
('life', '삶', 'existence', '/laɪf/', 'noun', 'Life is beautiful.', 'beginner', 'general', 0, 0, 119),
('child', '아이', 'young person', '/tʃaɪld/', 'noun', 'The child is playing.', 'beginner', 'general', 0, 0, 120),
('world', '세계', 'earth', '/wɜːrld/', 'noun', 'The world is big.', 'beginner', 'general', 0, 0, 121),
('school', '학교', 'educational institution', '/skuːl/', 'noun', 'I go to school daily.', 'beginner', 'general', 0, 0, 122),
('family', '가족', 'relatives', '/ˈfæməli/', 'noun', 'My family is small.', 'beginner', 'general', 0, 0, 123),
('student', '학생', 'learner', '/ˈstuːdnt/', 'noun', 'She is a good student.', 'beginner', 'general', 0, 0, 124),
('group', '그룹', 'collection', '/ɡruːp/', 'noun', 'Join our study group.', 'beginner', 'general', 0, 0, 125),
('problem', '문제', 'difficulty', '/ˈprɑːbləm/', 'noun', 'We have a problem.', 'beginner', 'general', 0, 0, 126),
('fact', '사실', 'truth', '/fækt/', 'noun', 'That is a fact.', 'beginner', 'general', 0, 0, 127),
('hand', '손', 'body part', '/hænd/', 'noun', 'Wash your hands first.', 'beginner', 'general', 0, 0, 128),
('place', '장소', 'location', '/pleɪs/', 'noun', 'This is a nice place.', 'beginner', 'general', 0, 0, 129),
('week', '주', 'seven days', '/wiːk/', 'noun', 'See you next week.', 'beginner', 'general', 0, 0, 130),
('company', '회사', 'business', '/ˈkʌmpəni/', 'noun', 'I work for a company.', 'beginner', 'general', 0, 0, 131),
('system', '시스템', 'organized structure', '/ˈsɪstəm/', 'noun', 'The system is broken.', 'beginner', 'general', 0, 0, 132),
('program', '프로그램', 'plan or software', '/ˈproʊɡræm/', 'noun', 'Watch this TV program.', 'beginner', 'general', 0, 0, 133),
('question', '질문', 'inquiry', '/ˈkwestʃən/', 'noun', 'Ask me a question.', 'beginner', 'general', 0, 0, 134),
('work', '일', 'job', '/wɜːrk/', 'noun', 'I have much work today.', 'beginner', 'general', 0, 0, 135),
('number', '숫자', 'numerical value', '/ˈnʌmbər/', 'noun', 'Write your phone number.', 'beginner', 'general', 0, 0, 136),
('night', '밤', 'dark hours', '/naɪt/', 'noun', 'Good night, sleep well.', 'beginner', 'general', 0, 0, 137),
('point', '점', 'specific location', '/pɔɪnt/', 'noun', 'You make a good point.', 'beginner', 'general', 0, 0, 138),
('home', '집', 'residence', '/hoʊm/', 'noun', 'Let us go home now.', 'beginner', 'general', 0, 0, 139),
('water', '물', 'liquid H2O', '/ˈwɔːtər/', 'noun', 'Drink more water daily.', 'beginner', 'general', 0, 0, 140),
('room', '방', 'enclosed space', '/ruːm/', 'noun', 'My room is clean.', 'beginner', 'general', 0, 0, 141),
('mother', '어머니', 'female parent', '/ˈmʌðər/', 'noun', 'My mother is kind.', 'beginner', 'general', 0, 0, 142),
('area', '지역', 'region', '/ˈeriə/', 'noun', 'This area is safe.', 'beginner', 'general', 0, 0, 143),
('money', '돈', 'currency', '/ˈmʌni/', 'noun', 'I need some money.', 'beginner', 'general', 0, 0, 144),
('story', '이야기', 'narrative', '/ˈstɔːri/', 'noun', 'Tell me a story.', 'beginner', 'general', 0, 0, 145),
('month', '달', 'period of time', '/mʌnθ/', 'noun', 'Last month was cold.', 'beginner', 'general', 0, 0, 146),
('lot', '많은', 'large amount', '/lɑːt/', 'noun', 'I have a lot of work.', 'beginner', 'general', 0, 0, 147),
('right', '권리', 'entitlement', '/raɪt/', 'noun', 'You have the right.', 'beginner', 'general', 0, 0, 148),
('study', '공부', 'learning', '/ˈstʌdi/', 'noun', 'Study is important.', 'beginner', 'general', 0, 0, 149),
('book', '책', 'written work', '/bʊk/', 'noun', 'Read this book please.', 'beginner', 'general', 0, 0, 150),
('eye', '눈', 'organ of sight', '/aɪ/', 'noun', 'Close your eyes now.', 'beginner', 'general', 0, 0, 151),
('job', '직업', 'work', '/dʒɑːb/', 'noun', 'She has a good job.', 'beginner', 'general', 0, 0, 152),
('word', '단어', 'language unit', '/wɜːrd/', 'noun', 'Learn new words daily.', 'beginner', 'general', 0, 0, 153),
('business', '사업', 'commercial activity', '/ˈbɪznəs/', 'noun', 'Business is good now.', 'beginner', 'general', 0, 0, 154),
('issue', '문제', 'matter', '/ˈɪʃuː/', 'noun', 'We have an issue.', 'beginner', 'general', 0, 0, 155),
('side', '면', 'surface', '/saɪd/', 'noun', 'Stand by my side.', 'beginner', 'general', 0, 0, 156),
('kind', '종류', 'type', '/kaɪnd/', 'noun', 'What kind do you want?', 'beginner', 'general', 0, 0, 157),
('head', '머리', 'top part of body', '/hed/', 'noun', 'My head hurts today.', 'beginner', 'general', 0, 0, 158),
('house', '집', 'building', '/haʊs/', 'noun', 'We bought a new house.', 'beginner', 'general', 0, 0, 159),
('service', '서비스', 'assistance', '/ˈsɜːrvɪs/', 'noun', 'Good service is important.', 'beginner', 'general', 0, 0, 160),
('friend', '친구', 'companion', '/frend/', 'noun', 'She is my best friend.', 'beginner', 'general', 0, 0, 161),
('father', '아버지', 'male parent', '/ˈfɑːðər/', 'noun', 'My father is tall.', 'beginner', 'general', 0, 0, 162),
('power', '힘', 'strength', '/ˈpaʊər/', 'noun', 'Knowledge is power.', 'beginner', 'general', 0, 0, 163),
('hour', '시간', 'sixty minutes', '/ˈaʊər/', 'noun', 'Wait one more hour.', 'beginner', 'general', 0, 0, 164),
('game', '게임', 'play activity', '/ɡeɪm/', 'noun', 'Let us play a game.', 'beginner', 'general', 0, 0, 165),
('line', '선', 'mark', '/laɪn/', 'noun', 'Draw a straight line.', 'beginner', 'general', 0, 0, 166),
('end', '끝', 'final part', '/end/', 'noun', 'This is the end.', 'beginner', 'general', 0, 0, 167),
('member', '회원', 'person in group', '/ˈmembər/', 'noun', 'He is a team member.', 'beginner', 'general', 0, 0, 168),
('law', '법', 'rule', '/lɔː/', 'noun', 'Obey the law always.', 'beginner', 'general', 0, 0, 169),
('car', '차', 'vehicle', '/kɑːr/', 'noun', 'I drive a red car.', 'beginner', 'general', 0, 0, 170),
('city', '도시', 'urban area', '/ˈsɪti/', 'noun', 'Seoul is a big city.', 'beginner', 'general', 0, 0, 171),
('name', '이름', 'identifier', '/neɪm/', 'noun', 'What is your name?', 'beginner', 'general', 0, 0, 172),
('president', '대통령', 'leader', '/ˈprezɪdənt/', 'noun', 'The president spoke today.', 'beginner', 'general', 0, 0, 173),
('team', '팀', 'group', '/tiːm/', 'noun', 'Our team won today.', 'beginner', 'general', 0, 0, 174),
('minute', '분', 'sixty seconds', '/ˈmɪnɪt/', 'noun', 'Wait just one minute.', 'beginner', 'general', 0, 0, 175),
('idea', '아이디어', 'thought', '/aɪˈdiːə/', 'noun', 'That is a great idea.', 'beginner', 'general', 0, 0, 176),
('body', '몸', 'physical form', '/ˈbɑːdi/', 'noun', 'Take care of your body.', 'beginner', 'general', 0, 0, 177),
('information', '정보', 'data', '/ˌɪnfərˈmeɪʃn/', 'noun', 'I need more information.', 'beginner', 'general', 0, 0, 178),
('nothing', '아무것도', 'not anything', '/ˈnʌθɪŋ/', 'pronoun', 'There is nothing here.', 'beginner', 'general', 0, 0, 179),
('age', '나이', 'years lived', '/eɪdʒ/', 'noun', 'What is your age?', 'beginner', 'general', 0, 0, 180),
('society', '사회', 'community', '/səˈsaɪəti/', 'noun', 'Society is changing fast.', 'beginner', 'general', 0, 0, 181),
('person', '사람', 'individual', '/ˈpɜːrsn/', 'noun', 'She is a nice person.', 'beginner', 'general', 0, 0, 182),
('health', '건강', 'wellness', '/helθ/', 'noun', 'Health is wealth.', 'beginner', 'general', 0, 0, 183),
('level', '수준', 'degree', '/ˈlevl/', 'noun', 'What is your English level?', 'beginner', 'general', 0, 0, 184),
('office', '사무실', 'workplace', '/ˈɔːfɪs/', 'noun', 'I work in an office.', 'beginner', 'general', 0, 0, 185),
('door', '문', 'entrance', '/dɔːr/', 'noun', 'Close the door please.', 'beginner', 'general', 0, 0, 186),
('morning', '아침', 'early day', '/ˈmɔːrnɪŋ/', 'noun', 'Good morning everyone!', 'beginner', 'general', 0, 0, 187),
('reason', '이유', 'explanation', '/ˈriːzn/', 'noun', 'Tell me the reason why.', 'beginner', 'general', 0, 0, 188),
('food', '음식', 'nourishment', '/fuːd/', 'noun', 'Korean food is delicious.', 'beginner', 'general', 0, 0, 189),
('teacher', '선생님', 'educator', '/ˈtiːtʃər/', 'noun', 'My teacher is kind.', 'beginner', 'general', 0, 0, 190),
('phone', '전화', 'communication device', '/foʊn/', 'noun', 'Answer your phone please.', 'beginner', 'general', 0, 0, 191),
('price', '가격', 'cost', '/praɪs/', 'noun', 'What is the price?', 'beginner', 'general', 0, 0, 192),
('street', '거리', 'road', '/striːt/', 'noun', 'Cross the street carefully.', 'beginner', 'general', 0, 0, 193),
('building', '건물', 'structure', '/ˈbɪldɪŋ/', 'noun', 'That building is tall.', 'beginner', 'general', 0, 0, 194),
('paper', '종이', 'sheet material', '/ˈpeɪpər/', 'noun', 'Write on this paper.', 'beginner', 'general', 0, 0, 195),
('computer', '컴퓨터', 'electronic device', '/kəmˈpjuːtər/', 'noun', 'Turn on the computer.', 'beginner', 'general', 0, 0, 196),
('hospital', '병원', 'medical facility', '/ˈhɑːspɪtl/', 'noun', 'He is in the hospital.', 'beginner', 'general', 0, 0, 197),
('restaurant', '식당', 'eating place', '/ˈrestrɑːnt/', 'noun', 'This restaurant is good.', 'beginner', 'general', 0, 0, 198),
('airport', '공항', 'flight terminal', '/ˈerpɔːrt/', 'noun', 'Meet me at the airport.', 'beginner', 'general', 0, 0, 199),
('hotel', '호텔', 'lodging', '/hoʊˈtel/', 'noun', 'Book a hotel room.', 'beginner', 'general', 0, 0, 200),
('bank', '은행', 'financial institution', '/bæŋk/', 'noun', 'Go to the bank tomorrow.', 'beginner', 'general', 0, 0, 201),
('store', '가게', 'shop', '/stɔːr/', 'noun', 'Buy it at that store.', 'beginner', 'general', 0, 0, 202),
('church', '교회', 'place of worship', '/tʃɜːrtʃ/', 'noun', 'She goes to church.', 'beginner', 'general', 0, 0, 203),
('park', '공원', 'recreational area', '/pɑːrk/', 'noun', 'Play in the park.', 'beginner', 'general', 0, 0, 204),
('market', '시장', 'trading place', '/ˈmɑːrkɪt/', 'noun', 'Shop at the market.', 'beginner', 'general', 0, 0, 205),
('station', '역', 'stop point', '/ˈsteɪʃn/', 'noun', 'Meet at the train station.', 'beginner', 'general', 0, 0, 206),
('doctor', '의사', 'physician', '/ˈdɑːktər/', 'noun', 'See a doctor soon.', 'beginner', 'general', 0, 0, 207),
('brother', '형제', 'male sibling', '/ˈbrʌðər/', 'noun', 'My brother is younger.', 'beginner', 'general', 0, 0, 208),
('sister', '자매', 'female sibling', '/ˈsɪstər/', 'noun', 'My sister is older.', 'beginner', 'general', 0, 0, 209),
('husband', '남편', 'married man', '/ˈhʌzbənd/', 'noun', 'Her husband is kind.', 'beginner', 'general', 0, 0, 210),

-- Basic Adjectives (100 words)
('good', '좋은', 'positive quality', '/ɡʊd/', 'adjective', 'This is a good book.', 'beginner', 'general', 0, 0, 211),
('new', '새로운', 'recent', '/nuː/', 'adjective', 'I bought a new phone.', 'beginner', 'general', 0, 0, 212),
('first', '첫번째', 'initial', '/fɜːrst/', 'adjective', 'This is my first time.', 'beginner', 'general', 0, 0, 213),
('last', '마지막', 'final', '/læst/', 'adjective', 'This is the last chance.', 'beginner', 'general', 0, 0, 214),
('long', '긴', 'extended', '/lɔːŋ/', 'adjective', 'That is a long road.', 'beginner', 'general', 0, 0, 215),
('great', '훌륭한', 'excellent', '/ɡreɪt/', 'adjective', 'You did a great job!', 'beginner', 'general', 0, 0, 216),
('little', '작은', 'small', '/ˈlɪtl/', 'adjective', 'I have a little dog.', 'beginner', 'general', 0, 0, 217),
('own', '자신의', 'belonging to self', '/oʊn/', 'adjective', 'This is my own car.', 'beginner', 'general', 0, 0, 218),
('other', '다른', 'different', '/ˈʌðər/', 'adjective', 'Try the other option.', 'beginner', 'general', 0, 0, 219),
('old', '오래된', 'aged', '/oʊld/', 'adjective', 'He lives in an old house.', 'beginner', 'general', 0, 0, 220),
('right', '옳은', 'correct', '/raɪt/', 'adjective', 'That is the right answer.', 'beginner', 'general', 0, 0, 221),
('big', '큰', 'large', '/bɪɡ/', 'adjective', 'Seoul is a big city.', 'beginner', 'general', 0, 0, 222),
('high', '높은', 'elevated', '/haɪ/', 'adjective', 'That mountain is very high.', 'beginner', 'general', 0, 0, 223),
('different', '다른', 'not the same', '/ˈdɪfrənt/', 'adjective', 'We have different opinions.', 'beginner', 'general', 0, 0, 224),
('small', '작은', 'tiny', '/smɔːl/', 'adjective', 'I live in a small apartment.', 'beginner', 'general', 0, 0, 225),
('large', '큰', 'big', '/lɑːrdʒ/', 'adjective', 'We need a large table.', 'beginner', 'general', 0, 0, 226),
('next', '다음', 'following', '/nekst/', 'adjective', 'See you next week.', 'beginner', 'general', 0, 0, 227),
('early', '이른', 'before time', '/ˈɜːrli/', 'adjective', 'Wake up early tomorrow.', 'beginner', 'general', 0, 0, 228),
('young', '젊은', 'not old', '/jʌŋ/', 'adjective', 'She is still very young.', 'beginner', 'general', 0, 0, 229),
('important', '중요한', 'significant', '/ɪmˈpɔːrtnt/', 'adjective', 'This is very important.', 'beginner', 'general', 0, 0, 230),
('few', '적은', 'not many', '/fjuː/', 'adjective', 'Only a few people came.', 'beginner', 'general', 0, 0, 231),
('public', '공공의', 'for everyone', '/ˈpʌblɪk/', 'adjective', 'Use public transportation.', 'beginner', 'general', 0, 0, 232),
('bad', '나쁜', 'negative', '/bæd/', 'adjective', 'That is a bad idea.', 'beginner', 'general', 0, 0, 233),
('same', '같은', 'identical', '/seɪm/', 'adjective', 'We have the same phone.', 'beginner', 'general', 0, 0, 234),
('able', '할 수 있는', 'capable', '/ˈeɪbl/', 'adjective', 'I am able to help you.', 'beginner', 'general', 0, 0, 235),
('free', '무료의', 'no cost', '/friː/', 'adjective', 'This service is free.', 'beginner', 'general', 0, 0, 236),
('white', '흰색', 'color', '/waɪt/', 'adjective', 'I like white shirts.', 'beginner', 'general', 0, 0, 237),
('black', '검은색', 'dark color', '/blæk/', 'adjective', 'He wears black shoes.', 'beginner', 'general', 0, 0, 238),
('red', '빨간색', 'color', '/red/', 'adjective', 'She has a red car.', 'beginner', 'general', 0, 0, 239),
('blue', '파란색', 'color', '/bluː/', 'adjective', 'The sky is blue today.', 'beginner', 'general', 0, 0, 240),
('green', '초록색', 'color', '/ɡriːn/', 'adjective', 'Trees are green in spring.', 'beginner', 'general', 0, 0, 241),
('yellow', '노란색', 'color', '/ˈjeloʊ/', 'adjective', 'I bought yellow flowers.', 'beginner', 'general', 0, 0, 242),
('happy', '행복한', 'joyful', '/ˈhæpi/', 'adjective', 'I feel happy today.', 'beginner', 'general', 0, 0, 243),
('sad', '슬픈', 'unhappy', '/sæd/', 'adjective', 'Why are you so sad?', 'beginner', 'general', 0, 0, 244),
('angry', '화난', 'mad', '/ˈæŋɡri/', 'adjective', 'He looks very angry.', 'beginner', 'general', 0, 0, 245),
('tired', '피곤한', 'exhausted', '/ˈtaɪərd/', 'adjective', 'I am so tired now.', 'beginner', 'general', 0, 0, 246),
('hungry', '배고픈', 'need food', '/ˈhʌŋɡri/', 'adjective', 'I am very hungry.', 'beginner', 'general', 0, 0, 247),
('thirsty', '목마른', 'need drink', '/ˈθɜːrsti/', 'adjective', 'I feel thirsty now.', 'beginner', 'general', 0, 0, 248),
('sick', '아픈', 'ill', '/sɪk/', 'adjective', 'She is sick today.', 'beginner', 'general', 0, 0, 249),
('healthy', '건강한', 'well', '/ˈhelθi/', 'adjective', 'Eat healthy food daily.', 'beginner', 'general', 0, 0, 250),
('hot', '뜨거운', 'high temperature', '/hɑːt/', 'adjective', 'The water is very hot.', 'beginner', 'general', 0, 0, 251),
('cold', '차가운', 'low temperature', '/koʊld/', 'adjective', 'It is cold outside.', 'beginner', 'general', 0, 0, 252),
('warm', '따뜻한', 'comfortable heat', '/wɔːrm/', 'adjective', 'The soup is warm.', 'beginner', 'general', 0, 0, 253),
('cool', '시원한', 'pleasantly cold', '/kuːl/', 'adjective', 'This room is cool.', 'beginner', 'general', 0, 0, 254),
('fast', '빠른', 'quick', '/fæst/', 'adjective', 'He is a fast runner.', 'beginner', 'general', 0, 0, 255),
('slow', '느린', 'not fast', '/sloʊ/', 'adjective', 'This computer is slow.', 'beginner', 'general', 0, 0, 256),
('easy', '쉬운', 'simple', '/ˈiːzi/', 'adjective', 'This test is easy.', 'beginner', 'general', 0, 0, 257),
('hard', '어려운', 'difficult', '/hɑːrd/', 'adjective', 'Math is very hard.', 'beginner', 'general', 0, 0, 258),
('beautiful', '아름다운', 'attractive', '/ˈbjuːtɪfl/', 'adjective', 'What a beautiful view!', 'beginner', 'general', 0, 0, 259),
('ugly', '못생긴', 'unattractive', '/ˈʌɡli/', 'adjective', 'That is an ugly building.', 'beginner', 'general', 0, 0, 260),
('clean', '깨끗한', 'not dirty', '/kliːn/', 'adjective', 'Keep your room clean.', 'beginner', 'general', 0, 0, 261),
('dirty', '더러운', 'not clean', '/ˈdɜːrti/', 'adjective', 'Your hands are dirty.', 'beginner', 'general', 0, 0, 262),
('full', '가득한', 'filled', '/fʊl/', 'adjective', 'The glass is full.', 'beginner', 'general', 0, 0, 263),
('empty', '빈', 'nothing inside', '/ˈempti/', 'adjective', 'The room is empty.', 'beginner', 'general', 0, 0, 264),
('heavy', '무거운', 'having weight', '/ˈhevi/', 'adjective', 'This box is heavy.', 'beginner', 'general', 0, 0, 265),
('light', '가벼운', 'not heavy', '/laɪt/', 'adjective', 'This bag is light.', 'beginner', 'general', 0, 0, 266),
('strong', '강한', 'powerful', '/strɔːŋ/', 'adjective', 'He is very strong.', 'beginner', 'general', 0, 0, 267),
('weak', '약한', 'not strong', '/wiːk/', 'adjective', 'I feel weak today.', 'beginner', 'general', 0, 0, 268),
('loud', '시끄러운', 'noisy', '/laʊd/', 'adjective', 'The music is too loud.', 'beginner', 'general', 0, 0, 269),
('quiet', '조용한', 'silent', '/ˈkwaɪət/', 'adjective', 'Please be quiet now.', 'beginner', 'general', 0, 0, 270),
('safe', '안전한', 'not dangerous', '/seɪf/', 'adjective', 'This place is safe.', 'beginner', 'general', 0, 0, 271),
('dangerous', '위험한', 'risky', '/ˈdeɪndʒərəs/', 'adjective', 'That road is dangerous.', 'beginner', 'general', 0, 0, 272),
('rich', '부유한', 'wealthy', '/rɪtʃ/', 'adjective', 'He is a rich man.', 'beginner', 'general', 0, 0, 273),
('poor', '가난한', 'lacking money', '/pʊr/', 'adjective', 'They are very poor.', 'beginner', 'general', 0, 0, 274),
('expensive', '비싼', 'costly', '/ɪkˈspensɪv/', 'adjective', 'This watch is expensive.', 'beginner', 'general', 0, 0, 275),
('cheap', '싼', 'low cost', '/tʃiːp/', 'adjective', 'Buy cheap vegetables.', 'beginner', 'general', 0, 0, 276),
('near', '가까운', 'close', '/nɪr/', 'adjective', 'The store is near.', 'beginner', 'general', 0, 0, 277),
('far', '먼', 'distant', '/fɑːr/', 'adjective', 'My home is far away.', 'beginner', 'general', 0, 0, 278),
('wide', '넓은', 'broad', '/waɪd/', 'adjective', 'This is a wide street.', 'beginner', 'general', 0, 0, 279),
('narrow', '좁은', 'not wide', '/ˈnæroʊ/', 'adjective', 'The alley is narrow.', 'beginner', 'general', 0, 0, 280),
('tall', '키큰', 'having height', '/tɔːl/', 'adjective', 'He is very tall.', 'beginner', 'general', 0, 0, 281),
('short', '키작은', 'not tall', '/ʃɔːrt/', 'adjective', 'She is quite short.', 'beginner', 'general', 0, 0, 282),
('thick', '두꺼운', 'wide', '/θɪk/', 'adjective', 'This is a thick book.', 'beginner', 'general', 0, 0, 283),
('thin', '얇은', 'not thick', '/θɪn/', 'adjective', 'Wear a thin jacket.', 'beginner', 'general', 0, 0, 284),
('deep', '깊은', 'extending down', '/diːp/', 'adjective', 'The ocean is deep.', 'beginner', 'general', 0, 0, 285),
('shallow', '얕은', 'not deep', '/ˈʃæloʊ/', 'adjective', 'This pool is shallow.', 'beginner', 'general', 0, 0, 286),
('wet', '젖은', 'covered with water', '/wet/', 'adjective', 'My clothes are wet.', 'beginner', 'general', 0, 0, 287),
('dry', '마른', 'not wet', '/draɪ/', 'adjective', 'The towel is dry now.', 'beginner', 'general', 0, 0, 288),
('soft', '부드러운', 'not hard', '/sɔːft/', 'adjective', 'This pillow is soft.', 'beginner', 'general', 0, 0, 289),
('hard', '딱딱한', 'solid', '/hɑːrd/', 'adjective', 'This bed is too hard.', 'beginner', 'general', 0, 0, 290),
('smooth', '매끄러운', 'even surface', '/smuːð/', 'adjective', 'The table is smooth.', 'beginner', 'general', 0, 0, 291),
('rough', '거친', 'uneven', '/rʌf/', 'adjective', 'The wall feels rough.', 'beginner', 'general', 0, 0, 292),
('bright', '밝은', 'giving light', '/braɪt/', 'adjective', 'The sun is bright.', 'beginner', 'general', 0, 0, 293),
('dark', '어두운', 'lacking light', '/dɑːrk/', 'adjective', 'The room is dark.', 'beginner', 'general', 0, 0, 294),
('sharp', '날카로운', 'having edge', '/ʃɑːrp/', 'adjective', 'Be careful, it is sharp.', 'beginner', 'general', 0, 0, 295),
('dull', '둔한', 'not sharp', '/dʌl/', 'adjective', 'This knife is dull.', 'beginner', 'general', 0, 0, 296),
('sweet', '달콤한', 'sugary taste', '/swiːt/', 'adjective', 'This cake is sweet.', 'beginner', 'general', 0, 0, 297),
('sour', '신', 'acidic taste', '/ˈsaʊər/', 'adjective', 'Lemons taste sour.', 'beginner', 'general', 0, 0, 298),
('bitter', '쓴', 'sharp taste', '/ˈbɪtər/', 'adjective', 'Coffee tastes bitter.', 'beginner', 'general', 0, 0, 299),
('salty', '짠', 'containing salt', '/ˈsɔːlti/', 'adjective', 'This soup is salty.', 'beginner', 'general', 0, 0, 300),
('delicious', '맛있는', 'very tasty', '/dɪˈlɪʃəs/', 'adjective', 'This food is delicious!', 'beginner', 'general', 0, 0, 301),
('fresh', '신선한', 'newly made', '/freʃ/', 'adjective', 'Buy fresh vegetables.', 'beginner', 'general', 0, 0, 302),
('stale', '오래된', 'not fresh', '/steɪl/', 'adjective', 'This bread is stale.', 'beginner', 'general', 0, 0, 303),
('ready', '준비된', 'prepared', '/ˈredi/', 'adjective', 'Are you ready to go?', 'beginner', 'general', 0, 0, 304),
('busy', '바쁜', 'occupied', '/ˈbɪzi/', 'adjective', 'I am very busy today.', 'beginner', 'general', 0, 0, 305),
('lazy', '게으른', 'not active', '/ˈleɪzi/', 'adjective', 'Do not be lazy.', 'beginner', 'general', 0, 0, 306),
('careful', '조심하는', 'cautious', '/ˈkerfəl/', 'adjective', 'Be careful on the road.', 'beginner', 'general', 0, 0, 307),
('careless', '부주의한', 'not careful', '/ˈkerləs/', 'adjective', 'That was a careless mistake.', 'beginner', 'general', 0, 0, 308),
('funny', '웃긴', 'amusing', '/ˈfʌni/', 'adjective', 'He told a funny joke.', 'beginner', 'general', 0, 0, 309),
('serious', '진지한', 'not joking', '/ˈsɪriəs/', 'adjective', 'This is a serious problem.', 'beginner', 'general', 0, 0, 310),

-- Numbers, Time, Days (50 words)
('one', '하나', 'number 1', '/wʌn/', 'number', 'I have one apple.', 'beginner', 'numbers', 0, 0, 311),
('two', '둘', 'number 2', '/tuː/', 'number', 'There are two cats.', 'beginner', 'numbers', 0, 0, 312),
('three', '셋', 'number 3', '/θriː/', 'number', 'I need three chairs.', 'beginner', 'numbers', 0, 0, 313),
('four', '넷', 'number 4', '/fɔːr/', 'number', 'Buy four tickets please.', 'beginner', 'numbers', 0, 0, 314),
('five', '다섯', 'number 5', '/faɪv/', 'number', 'Wait five minutes.', 'beginner', 'numbers', 0, 0, 315),
('six', '여섯', 'number 6', '/sɪks/', 'number', 'I work six days.', 'beginner', 'numbers', 0, 0, 316),
('seven', '일곱', 'number 7', '/ˈsevn/', 'number', 'There are seven days.', 'beginner', 'numbers', 0, 0, 317),
('eight', '여덟', 'number 8', '/eɪt/', 'number', 'Class starts at eight.', 'beginner', 'numbers', 0, 0, 318),
('nine', '아홉', 'number 9', '/naɪn/', 'number', 'I have nine books.', 'beginner', 'numbers', 0, 0, 319),
('ten', '열', 'number 10', '/ten/', 'number', 'Count to ten slowly.', 'beginner', 'numbers', 0, 0, 320),
('hundred', '백', 'number 100', '/ˈhʌndrəd/', 'number', 'I have one hundred dollars.', 'beginner', 'numbers', 0, 0, 321),
('thousand', '천', 'number 1000', '/ˈθaʊznd/', 'number', 'It costs one thousand won.', 'beginner', 'numbers', 0, 0, 322),
('million', '백만', 'number 1000000', '/ˈmɪljən/', 'number', 'One million people live here.', 'beginner', 'numbers', 0, 0, 323),
('today', '오늘', 'this day', '/təˈdeɪ/', 'noun', 'What day is today?', 'beginner', 'time', 0, 0, 324),
('yesterday', '어제', 'day before', '/ˈjestərdeɪ/', 'noun', 'I saw him yesterday.', 'beginner', 'time', 0, 0, 325),
('tomorrow', '내일', 'day after', '/təˈmɑːroʊ/', 'noun', 'See you tomorrow morning.', 'beginner', 'time', 0, 0, 326),
('now', '지금', 'at this moment', '/naʊ/', 'adverb', 'Come here right now.', 'beginner', 'time', 0, 0, 327),
('later', '나중에', 'after this', '/ˈleɪtər/', 'adverb', 'I will call you later.', 'beginner', 'time', 0, 0, 328),
('soon', '곧', 'in near future', '/suːn/', 'adverb', 'Spring will come soon.', 'beginner', 'time', 0, 0, 329),
('always', '항상', 'every time', '/ˈɔːlweɪz/', 'adverb', 'I always wake up early.', 'beginner', 'time', 0, 0, 330),
('never', '절대', 'not ever', '/ˈnevər/', 'adverb', 'I never eat meat.', 'beginner', 'time', 0, 0, 331),
('sometimes', '때때로', 'occasionally', '/ˈsʌmtaɪmz/', 'adverb', 'I sometimes drink coffee.', 'beginner', 'time', 0, 0, 332),
('often', '자주', 'frequently', '/ˈɔːfn/', 'adverb', 'I often visit my parents.', 'beginner', 'time', 0, 0, 333),
('usually', '보통', 'generally', '/ˈjuːʒuəli/', 'adverb', 'I usually eat at home.', 'beginner', 'time', 0, 0, 334),
('Monday', '월요일', 'first weekday', '/ˈmʌndeɪ/', 'noun', 'I hate Monday mornings.', 'beginner', 'time', 0, 0, 335),
('Tuesday', '화요일', 'second weekday', '/ˈtuːzdeɪ/', 'noun', 'See you on Tuesday.', 'beginner', 'time', 0, 0, 336),
('Wednesday', '수요일', 'third weekday', '/ˈwenzdeɪ/', 'noun', 'Wednesday is meeting day.', 'beginner', 'time', 0, 0, 337),
('Thursday', '목요일', 'fourth weekday', '/ˈθɜːrzdeɪ/', 'noun', 'Call me on Thursday.', 'beginner', 'time', 0, 0, 338),
('Friday', '금요일', 'fifth weekday', '/ˈfraɪdeɪ/', 'noun', 'Friday is my favorite.', 'beginner', 'time', 0, 0, 339),
('Saturday', '토요일', 'sixth weekday', '/ˈsætərdeɪ/', 'noun', 'I rest on Saturday.', 'beginner', 'time', 0, 0, 340),
('Sunday', '일요일', 'seventh weekday', '/ˈsʌndeɪ/', 'noun', 'Sunday is family day.', 'beginner', 'time', 0, 0, 341),
('January', '1월', 'first month', '/ˈdʒænjueri/', 'noun', 'January is very cold.', 'beginner', 'time', 0, 0, 342),
('February', '2월', 'second month', '/ˈfebrueri/', 'noun', 'My birthday is in February.', 'beginner', 'time', 0, 0, 343),
('March', '3월', 'third month', '/mɑːrtʃ/', 'noun', 'Spring starts in March.', 'beginner', 'time', 0, 0, 344),
('April', '4월', 'fourth month', '/ˈeɪprəl/', 'noun', 'April showers bring flowers.', 'beginner', 'time', 0, 0, 345),
('May', '5월', 'fifth month', '/meɪ/', 'noun', 'May is a beautiful month.', 'beginner', 'time', 0, 0, 346),
('June', '6월', 'sixth month', '/dʒuːn/', 'noun', 'School ends in June.', 'beginner', 'time', 0, 0, 347),
('July', '7월', 'seventh month', '/dʒuˈlaɪ/', 'noun', 'July is very hot here.', 'beginner', 'time', 0, 0, 348),
('August', '8월', 'eighth month', '/ˈɔːɡəst/', 'noun', 'I vacation in August.', 'beginner', 'time', 0, 0, 349),
('September', '9월', 'ninth month', '/sepˈtembər/', 'noun', 'School starts in September.', 'beginner', 'time', 0, 0, 350),
('October', '10월', 'tenth month', '/ɑːkˈtoʊbər/', 'noun', 'October has nice weather.', 'beginner', 'time', 0, 0, 351),
('November', '11월', 'eleventh month', '/noʊˈvembər/', 'noun', 'November is autumn time.', 'beginner', 'time', 0, 0, 352),
('December', '12월', 'twelfth month', '/dɪˈsembər/', 'noun', 'December is Christmas month.', 'beginner', 'time', 0, 0, 353),
('spring', '봄', 'warm season', '/sprɪŋ/', 'noun', 'I love spring flowers.', 'beginner', 'time', 0, 0, 354),
('summer', '여름', 'hot season', '/ˈsʌmər/', 'noun', 'Summer is too hot.', 'beginner', 'time', 0, 0, 355),
('autumn', '가을', 'cool season', '/ˈɔːtəm/', 'noun', 'Autumn leaves are beautiful.', 'beginner', 'time', 0, 0, 356),
('winter', '겨울', 'cold season', '/ˈwɪntər/', 'noun', 'Winter is my favorite.', 'beginner', 'time', 0, 0, 357),
('birthday', '생일', 'day of birth', '/ˈbɜːrθdeɪ/', 'noun', 'Happy birthday to you!', 'beginner', 'time', 0, 0, 358),
('holiday', '휴일', 'day off', '/ˈhɑːlədeɪ/', 'noun', 'Enjoy your holiday!', 'beginner', 'time', 0, 0, 359),
('vacation', '휴가', 'time off work', '/veɪˈkeɪʃn/', 'noun', 'I need a vacation soon.', 'beginner', 'time', 0, 0, 360),

-- Daily Conversation & Common Phrases (40 words)
('how', '어떻게', 'in what way', '/haʊ/', 'adverb', 'How are you today?', 'beginner', 'daily', 0, 0, 361),
('why', '왜', 'for what reason', '/waɪ/', 'adverb', 'Why did you come late?', 'beginner', 'daily', 0, 0, 362),
('when', '언제', 'at what time', '/wen/', 'adverb', 'When will you arrive?', 'beginner', 'daily', 0, 0, 363),
('where', '어디', 'in what place', '/wer/', 'adverb', 'Where do you live?', 'beginner', 'daily', 0, 0, 364),
('what', '무엇', 'which thing', '/wʌt/', 'pronoun', 'What is your name?', 'beginner', 'daily', 0, 0, 365),
('who', '누구', 'which person', '/huː/', 'pronoun', 'Who is that man?', 'beginner', 'daily', 0, 0, 366),
('which', '어느', 'what one', '/wɪtʃ/', 'pronoun', 'Which book do you want?', 'beginner', 'daily', 0, 0, 367),
('whose', '누구의', 'of whom', '/huːz/', 'pronoun', 'Whose phone is this?', 'beginner', 'daily', 0, 0, 368),
('because', '왜냐하면', 'for the reason that', '/bɪˈkɔːz/', 'conjunction', 'I stayed home because it rained.', 'beginner', 'daily', 0, 0, 369),
('but', '그러나', 'however', '/bʌt/', 'conjunction', 'I want to go but I am busy.', 'beginner', 'daily', 0, 0, 370),
('and', '그리고', 'also', '/ænd/', 'conjunction', 'I like coffee and tea.', 'beginner', 'daily', 0, 0, 371),
('or', '또는', 'alternative', '/ɔːr/', 'conjunction', 'Do you want tea or coffee?', 'beginner', 'daily', 0, 0, 372),
('so', '그래서', 'therefore', '/soʊ/', 'conjunction', 'I was tired so I slept.', 'beginner', 'daily', 0, 0, 373),
('if', '만약', 'in case', '/ɪf/', 'conjunction', 'If it rains, stay home.', 'beginner', 'daily', 0, 0, 374),
('very', '매우', 'extremely', '/ˈveri/', 'adverb', 'This is very good!', 'beginner', 'daily', 0, 0, 375),
('too', '너무', 'excessively', '/tuː/', 'adverb', 'This is too expensive.', 'beginner', 'daily', 0, 0, 376),
('much', '많은', 'great amount', '/mʌtʃ/', 'determiner', 'I have too much work.', 'beginner', 'daily', 0, 0, 377),
('many', '많은', 'numerous', '/ˈmeni/', 'determiner', 'There are many people.', 'beginner', 'daily', 0, 0, 378),
('some', '약간', 'a few', '/sʌm/', 'determiner', 'Give me some water.', 'beginner', 'daily', 0, 0, 379),
('any', '어떤', 'one or more', '/ˈeni/', 'determiner', 'Do you have any questions?', 'beginner', 'daily', 0, 0, 380),
('all', '모두', 'every one', '/ɔːl/', 'determiner', 'All students passed the test.', 'beginner', 'daily', 0, 0, 381),
('both', '둘 다', 'two together', '/boʊθ/', 'determiner', 'Both answers are correct.', 'beginner', 'daily', 0, 0, 382),
('each', '각각', 'every single', '/iːtʃ/', 'determiner', 'Each person gets one.', 'beginner', 'daily', 0, 0, 383),
('every', '모든', 'all', '/ˈevri/', 'determiner', 'I study every day.', 'beginner', 'daily', 0, 0, 384),
('here', '여기', 'in this place', '/hɪr/', 'adverb', 'Come over here please.', 'beginner', 'daily', 0, 0, 385),
('there', '저기', 'in that place', '/ðer/', 'adverb', 'Put it over there.', 'beginner', 'daily', 0, 0, 386),
('up', '위로', 'to higher place', '/ʌp/', 'adverb', 'Look up at the sky.', 'beginner', 'daily', 0, 0, 387),
('down', '아래로', 'to lower place', '/daʊn/', 'adverb', 'Sit down on the chair.', 'beginner', 'daily', 0, 0, 388),
('in', '안에', 'inside', '/ɪn/', 'preposition', 'The cat is in the box.', 'beginner', 'daily', 0, 0, 389),
('out', '밖에', 'outside', '/aʊt/', 'preposition', 'The dog is out there.', 'beginner', 'daily', 0, 0, 390),
('on', '위에', 'upon', '/ɑːn/', 'preposition', 'The book is on the table.', 'beginner', 'daily', 0, 0, 391),
('off', '떨어져', 'away from', '/ɔːf/', 'preposition', 'Take your shoes off.', 'beginner', 'daily', 0, 0, 392),
('over', '위에', 'above', '/ˈoʊvər/', 'preposition', 'The plane flew over us.', 'beginner', 'daily', 0, 0, 393),
('under', '아래에', 'below', '/ˈʌndər/', 'preposition', 'The cat is under the table.', 'beginner', 'daily', 0, 0, 394),
('before', '전에', 'earlier than', '/bɪˈfɔːr/', 'preposition', 'Come before noon.', 'beginner', 'daily', 0, 0, 395),
('after', '후에', 'later than', '/ˈæftər/', 'preposition', 'Call me after lunch.', 'beginner', 'daily', 0, 0, 396),
('between', '사이에', 'in the middle', '/bɪˈtwiːn/', 'preposition', 'Sit between them.', 'beginner', 'daily', 0, 0, 397),
('with', '함께', 'together', '/wɪð/', 'preposition', 'Come with me now.', 'beginner', 'daily', 0, 0, 398),
('without', '없이', 'lacking', '/wɪðˈaʊt/', 'preposition', 'Do not go without me.', 'beginner', 'daily', 0, 0, 399),
('about', '대해', 'concerning', '/əˈbaʊt/', 'preposition', 'Tell me about your day.', 'beginner', 'daily', 0, 0, 400);
