-- WorVox Test Vocabulary (50 words)
-- Test upload to D1 Console

INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, pronunciation, part_of_speech, example_sentence, difficulty, category, is_toeic, is_toefl, frequency_rank) VALUES
('hello', '안녕하세요', 'a greeting', '/həˈloʊ/', 'interjection', 'Hello, how are you today?', 'beginner', 'daily', 0, 0, 1),
('goodbye', '안녕히 가세요', 'farewell', '/ɡʊdˈbaɪ/', 'interjection', 'Goodbye, see you tomorrow!', 'beginner', 'daily', 0, 0, 2),
('thanks', '감사합니다', 'expression of gratitude', '/θæŋks/', 'noun', 'Thanks for your help!', 'beginner', 'daily', 0, 0, 3),
('please', '부탁합니다', 'polite request', '/pliːz/', 'adverb', 'Please pass me the salt.', 'beginner', 'daily', 0, 0, 4),
('sorry', '미안합니다', 'expression of apology', '/ˈsɑːri/', 'adjective', 'I am sorry for being late.', 'beginner', 'daily', 0, 0, 5),
('yes', '네', 'affirmative', '/jes/', 'adverb', 'Yes, I agree with you.', 'beginner', 'daily', 0, 0, 6),
('no', '아니요', 'negative', '/noʊ/', 'adverb', 'No, I cannot come today.', 'beginner', 'daily', 0, 0, 7),
('okay', '좋아요', 'agreement', '/oʊˈkeɪ/', 'adjective', 'Okay, I will do it now.', 'beginner', 'daily', 0, 0, 8),
('excuse', '실례합니다', 'polite interruption', '/ɪkˈskjuːs/', 'verb', 'Excuse me, where is the bathroom?', 'beginner', 'daily', 0, 0, 9),
('welcome', '환영합니다', 'greeting arrival', '/ˈwelkəm/', 'interjection', 'Welcome to our home!', 'beginner', 'daily', 0, 0, 10),
('be', '이다', 'to exist', '/biː/', 'verb', 'I want to be a teacher.', 'beginner', 'general', 0, 0, 11),
('have', '가지다', 'to possess', '/hæv/', 'verb', 'I have a cat and a dog.', 'beginner', 'general', 0, 0, 12),
('do', '하다', 'to perform', '/duː/', 'verb', 'What do you do for work?', 'beginner', 'general', 0, 0, 13),
('say', '말하다', 'to speak', '/seɪ/', 'verb', 'What did you say?', 'beginner', 'general', 0, 0, 14),
('go', '가다', 'to move', '/ɡoʊ/', 'verb', 'Let us go to the park.', 'beginner', 'general', 0, 0, 15),
('come', '오다', 'to arrive', '/kʌm/', 'verb', 'Please come to my party.', 'beginner', 'general', 0, 0, 16),
('make', '만들다', 'to create', '/meɪk/', 'verb', 'She makes beautiful art.', 'beginner', 'general', 0, 0, 17),
('take', '가져가다', 'to grab', '/teɪk/', 'verb', 'Take this book with you.', 'beginner', 'general', 0, 0, 18),
('get', '얻다', 'to obtain', '/ɡet/', 'verb', 'I need to get some milk.', 'beginner', 'general', 0, 0, 19),
('see', '보다', 'to view', '/siː/', 'verb', 'I see a bird in the tree.', 'beginner', 'general', 0, 0, 20),
('know', '알다', 'to understand', '/noʊ/', 'verb', 'I know the answer.', 'beginner', 'general', 0, 0, 21),
('think', '생각하다', 'to consider', '/θɪŋk/', 'verb', 'I think it will rain today.', 'beginner', 'general', 0, 0, 22),
('want', '원하다', 'to desire', '/wɑːnt/', 'verb', 'I want to learn English.', 'beginner', 'general', 0, 0, 23),
('give', '주다', 'to provide', '/ɡɪv/', 'verb', 'Can you give me a pen?', 'beginner', 'general', 0, 0, 24),
('use', '사용하다', 'to utilize', '/juːz/', 'verb', 'How do you use this phone?', 'beginner', 'general', 0, 0, 25),
('find', '찾다', 'to discover', '/faɪnd/', 'verb', 'I cannot find my keys.', 'beginner', 'general', 0, 0, 26),
('tell', '말하다', 'to inform', '/tel/', 'verb', 'Tell me your name.', 'beginner', 'general', 0, 0, 27),
('ask', '묻다', 'to question', '/æsk/', 'verb', 'Can I ask you something?', 'beginner', 'general', 0, 0, 28),
('work', '일하다', 'to labor', '/wɜːrk/', 'verb', 'I work at a hospital.', 'beginner', 'general', 0, 0, 29),
('call', '전화하다', 'to telephone', '/kɔːl/', 'verb', 'I will call you later.', 'beginner', 'daily', 0, 0, 30),
('time', '시간', 'duration', '/taɪm/', 'noun', 'What time is it now?', 'beginner', 'general', 0, 0, 31),
('year', '년', 'period of 365 days', '/jɪr/', 'noun', 'Last year was great.', 'beginner', 'general', 0, 0, 32),
('people', '사람들', 'humans', '/ˈpiːpl/', 'noun', 'Many people came today.', 'beginner', 'general', 0, 0, 33),
('day', '날', 'period of 24 hours', '/deɪ/', 'noun', 'Have a nice day!', 'beginner', 'general', 0, 0, 34),
('man', '남자', 'adult male', '/mæn/', 'noun', 'That man is my father.', 'beginner', 'general', 0, 0, 35),
('woman', '여자', 'adult female', '/ˈwʊmən/', 'noun', 'That woman is a doctor.', 'beginner', 'general', 0, 0, 36),
('child', '아이', 'young person', '/tʃaɪld/', 'noun', 'The child is playing.', 'beginner', 'general', 0, 0, 37),
('world', '세계', 'earth', '/wɜːrld/', 'noun', 'The world is big.', 'beginner', 'general', 0, 0, 38),
('school', '학교', 'educational institution', '/skuːl/', 'noun', 'I go to school daily.', 'beginner', 'general', 0, 0, 39),
('family', '가족', 'relatives', '/ˈfæməli/', 'noun', 'My family is small.', 'beginner', 'general', 0, 0, 40),
('good', '좋은', 'positive quality', '/ɡʊd/', 'adjective', 'This is a good book.', 'beginner', 'general', 0, 0, 41),
('new', '새로운', 'recent', '/nuː/', 'adjective', 'I bought a new phone.', 'beginner', 'general', 0, 0, 42),
('first', '첫번째', 'initial', '/fɜːrst/', 'adjective', 'This is my first time.', 'beginner', 'general', 0, 0, 43),
('big', '큰', 'large', '/bɪɡ/', 'adjective', 'Seoul is a big city.', 'beginner', 'general', 0, 0, 44),
('small', '작은', 'tiny', '/smɔːl/', 'adjective', 'I live in a small apartment.', 'beginner', 'general', 0, 0, 45),
('happy', '행복한', 'joyful', '/ˈhæpi/', 'adjective', 'I feel happy today.', 'beginner', 'general', 0, 0, 46),
('beautiful', '아름다운', 'attractive', '/ˈbjuːtɪfl/', 'adjective', 'What a beautiful view!', 'beginner', 'general', 0, 0, 47),
('today', '오늘', 'this day', '/təˈdeɪ/', 'noun', 'What day is today?', 'beginner', 'time', 0, 0, 48),
('tomorrow', '내일', 'day after', '/təˈmɑːroʊ/', 'noun', 'See you tomorrow morning.', 'beginner', 'time', 0, 0, 49),
('water', '물', 'liquid H2O', '/ˈwɔːtər/', 'noun', 'Drink more water daily.', 'beginner', 'general', 0, 0, 50);

-- Verify insertion
SELECT COUNT(*) as total_words FROM vocabulary_words;
SELECT * FROM vocabulary_words LIMIT 5;
