-- Part 3: Words 101-150
INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, example_sentence, difficulty) VALUES
('accelerate', '가속화하다', 'to speed up', 'We need to accelerate the process.', 'advanced'),
('accommodate', '수용하다', 'to provide for', 'The hotel can accommodate 200 guests.', 'advanced'),
('accumulate', '축적하다', 'to gather', 'Experience accumulates over time.', 'advanced'),
('adjacent', '인접한', 'next to', 'The office is adjacent to the bank.', 'advanced'),
('advocate', '옹호하다', 'to support', 'I advocate for environmental protection.', 'advanced'),
('aggregate', '총계', 'total', 'The aggregate amount is significant.', 'advanced'),
('allocate', '할당하다', 'to distribute', 'We must allocate resources wisely.', 'advanced'),
('ambiguous', '애매한', 'unclear', 'The statement was ambiguous.', 'advanced'),
('amendment', '수정', 'a change', 'The amendment was approved.', 'advanced'),
('analogy', '비유', 'comparison', 'Let me use an analogy.', 'advanced'),
('anticipate', '예상하다', 'to expect', 'We anticipate strong demand.', 'advanced'),
('arbitrary', '임의의', 'random', 'The decision seemed arbitrary.', 'advanced'),
('assemble', '조립하다', 'to put together', 'Assemble the parts carefully.', 'advanced'),
('attribute', '속성', 'characteristic', 'List the key attributes.', 'advanced'),
('autonomy', '자율성', 'independence', 'The team has full autonomy.', 'advanced'),
('bias', '편견', 'prejudice', 'Avoid bias in your judgment.', 'advanced'),
('capable', '유능한', 'able', 'She is highly capable.', 'advanced'),
('capacity', '용량', 'ability', 'The capacity is 100 people.', 'advanced'),
('cease', '중단하다', 'to stop', 'The fighting must cease.', 'advanced'),
('coherent', '일관된', 'logical', 'Make a coherent argument.', 'advanced'),
('coincide', '일치하다', 'to occur together', 'Our meetings coincide.', 'advanced'),
('collapse', '붕괴하다', 'to fall down', 'The building could collapse.', 'advanced'),
('commence', '시작하다', 'to begin', 'The ceremony will commence at 9.', 'advanced'),
('compatible', '호환되는', 'able to work together', 'Are these systems compatible?', 'advanced'),
('compensate', '보상하다', 'to pay', 'We will compensate for the loss.', 'advanced'),
('compile', '편집하다', 'to collect', 'Compile the reports.', 'advanced'),
('complement', '보완하다', 'to complete', 'These skills complement each other.', 'advanced'),
('comprehensive', '포괄적인', 'complete', 'This is a comprehensive guide.', 'advanced'),
('comprise', '구성하다', 'to consist of', 'The team comprises experts.', 'advanced'),
('conceive', '생각해내다', 'to imagine', 'I cannot conceive of a solution.', 'advanced'),
('concurrent', '동시의', 'happening together', 'Concurrent events occurred.', 'advanced'),
('confine', '제한하다', 'to restrict', 'Confine your comments to the topic.', 'advanced'),
('conform', '따르다', 'to comply', 'We must conform to regulations.', 'advanced'),
('consent', '동의', 'agreement', 'I need your consent.', 'advanced'),
('considerable', '상당한', 'significant', 'There is considerable interest.', 'advanced'),
('constrain', '제약하다', 'to limit', 'Budget constraints apply.', 'advanced'),
('contemporary', '현대의', 'modern', 'Contemporary art is popular.', 'advanced'),
('contradict', '모순되다', 'to oppose', 'These statements contradict.', 'advanced'),
('contrary', '반대의', 'opposite', 'Contrary to expectations...', 'advanced'),
('convene', '소집하다', 'to gather', 'The committee will convene tomorrow.', 'advanced'),
('conventional', '전통적인', 'traditional', 'Use conventional methods.', 'advanced'),
('convert', '변환하다', 'to change', 'Convert dollars to euros.', 'advanced'),
('coordinate', '조정하다', 'to organize', 'Coordinate the activities.', 'advanced'),
('core', '핵심', 'center', 'This is the core issue.', 'advanced'),
('corporate', '기업의', 'relating to business', 'Corporate policy changed.', 'advanced'),
('correspond', '일치하다', 'to match', 'These numbers correspond.', 'advanced'),
('criterion', '기준', 'standard', 'What is the main criterion?', 'advanced'),
('crucial', '중대한', 'critical', 'This is a crucial decision.', 'advanced'),
('currency', '통화', 'money', 'The local currency is weak.', 'advanced'),
('denote', '나타내다', 'to indicate', 'Red denotes danger.', 'advanced');