-- WorVox Simple Vocabulary Set (400 words)
-- Simplified schema: word, meaning_ko, meaning_en, example_sentence, difficulty

INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, example_sentence, difficulty) VALUES
-- Basic Greetings & Common Phrases (10 words)
('hello', '안녕하세요', 'a greeting', 'Hello, how are you today?', 'beginner'),
('goodbye', '안녕히 가세요', 'farewell', 'Goodbye, see you tomorrow!', 'beginner'),
('thanks', '감사합니다', 'expression of gratitude', 'Thanks for your help!', 'beginner'),
('please', '부탁합니다', 'polite request', 'Please pass me the salt.', 'beginner'),
('sorry', '미안합니다', 'expression of apology', 'I am sorry for being late.', 'beginner'),
('yes', '네', 'affirmative', 'Yes, I agree with you.', 'beginner'),
('no', '아니요', 'negative', 'No, I cannot come today.', 'beginner'),
('okay', '좋아요', 'agreement', 'Okay, I will do it now.', 'beginner'),
('excuse', '실례합니다', 'polite interruption', 'Excuse me, where is the bathroom?', 'beginner'),
('welcome', '환영합니다', 'greeting arrival', 'Welcome to our home!', 'beginner'),

-- Basic Verbs (50 words)
('be', '이다', 'to exist', 'I want to be a teacher.', 'beginner'),
('have', '가지다', 'to possess', 'I have a cat and a dog.', 'beginner'),
('do', '하다', 'to perform', 'What do you do for work?', 'beginner'),
('say', '말하다', 'to speak', 'What did you say?', 'beginner'),
('go', '가다', 'to move', 'Let us go to the park.', 'beginner'),
('come', '오다', 'to arrive', 'Please come to my party.', 'beginner'),
('make', '만들다', 'to create', 'She makes beautiful art.', 'beginner'),
('take', '가져가다', 'to grab', 'Take this book with you.', 'beginner'),
('get', '얻다', 'to obtain', 'I need to get some milk.', 'beginner'),
('see', '보다', 'to view', 'I see a bird in the tree.', 'beginner'),
('know', '알다', 'to understand', 'I know the answer.', 'beginner'),
('think', '생각하다', 'to consider', 'I think it will rain today.', 'beginner'),
('want', '원하다', 'to desire', 'I want to learn English.', 'beginner'),
('give', '주다', 'to provide', 'Can you give me a pen?', 'beginner'),
('use', '사용하다', 'to utilize', 'How do you use this phone?', 'beginner'),
('find', '찾다', 'to discover', 'I cannot find my keys.', 'beginner'),
('tell', '말하다', 'to inform', 'Tell me your name.', 'beginner'),
('ask', '묻다', 'to question', 'Can I ask you something?', 'beginner'),
('work', '일하다', 'to labor', 'I work at a hospital.', 'beginner'),
('call', '전화하다', 'to telephone', 'I will call you later.', 'beginner'),
('try', '시도하다', 'to attempt', 'Try to do your best.', 'beginner'),
('feel', '느끼다', 'to sense', 'I feel happy today.', 'beginner'),
('become', '되다', 'to change into', 'She became a doctor.', 'beginner'),
('leave', '떠나다', 'to depart', 'I will leave at 5 PM.', 'beginner'),
('put', '놓다', 'to place', 'Put the book on the table.', 'beginner'),
('mean', '의미하다', 'to signify', 'What does this word mean?', 'beginner'),
('keep', '유지하다', 'to maintain', 'Keep the door closed.', 'beginner'),
('let', '허락하다', 'to allow', 'Let me help you.', 'beginner'),
('begin', '시작하다', 'to start', 'Let us begin the lesson.', 'beginner'),
('seem', '~처럼 보이다', 'to appear', 'You seem tired today.', 'beginner'),
('help', '돕다', 'to assist', 'Can you help me please?', 'beginner'),
('show', '보여주다', 'to display', 'Show me your homework.', 'beginner'),
('hear', '듣다', 'to perceive sound', 'I hear music playing.', 'beginner'),
('play', '놀다', 'to engage in activity', 'Children play in the park.', 'beginner'),
('run', '달리다', 'to move quickly', 'I run every morning.', 'beginner'),
('move', '움직이다', 'to change position', 'Move your chair closer.', 'beginner'),
('like', '좋아하다', 'to enjoy', 'I like chocolate ice cream.', 'beginner'),
('live', '살다', 'to reside', 'Where do you live?', 'beginner'),
('believe', '믿다', 'to accept as true', 'I believe you are right.', 'beginner'),
('bring', '가져오다', 'to carry', 'Bring your book tomorrow.', 'beginner'),
('happen', '일어나다', 'to occur', 'What happened yesterday?', 'beginner'),
('write', '쓰다', 'to compose', 'Write your name here.', 'beginner'),
('sit', '앉다', 'to be seated', 'Please sit down.', 'beginner'),
('stand', '서다', 'to be upright', 'Stand up when you speak.', 'beginner'),
('lose', '잃다', 'to misplace', 'Do not lose your ticket.', 'beginner'),
('pay', '지불하다', 'to give money', 'I will pay for dinner.', 'beginner'),
('meet', '만나다', 'to encounter', 'Let us meet at noon.', 'beginner'),
('include', '포함하다', 'to contain', 'The price includes tax.', 'beginner'),
('continue', '계속하다', 'to persist', 'Please continue reading.', 'beginner'),
('set', '설정하다', 'to establish', 'Set the alarm for 7 AM.', 'beginner'),

-- Basic Nouns (50 words)
('time', '시간', 'duration', 'What time is it now?', 'beginner'),
('year', '년', 'period of 365 days', 'Last year was great.', 'beginner'),
('people', '사람들', 'humans', 'Many people came today.', 'beginner'),
('way', '방법', 'method', 'Show me the way home.', 'beginner'),
('day', '날', 'period of 24 hours', 'Have a nice day!', 'beginner'),
('man', '남자', 'adult male', 'That man is my father.', 'beginner'),
('thing', '것', 'object', 'What is that thing?', 'beginner'),
('woman', '여자', 'adult female', 'That woman is a doctor.', 'beginner'),
('life', '삶', 'existence', 'Life is beautiful.', 'beginner'),
('child', '아이', 'young person', 'The child is playing.', 'beginner'),
('world', '세계', 'earth', 'The world is big.', 'beginner'),
('school', '학교', 'educational institution', 'I go to school daily.', 'beginner'),
('family', '가족', 'relatives', 'My family is small.', 'beginner'),
('student', '학생', 'learner', 'She is a good student.', 'beginner'),
('group', '그룹', 'collection', 'Join our study group.', 'beginner'),
('problem', '문제', 'difficulty', 'We have a problem.', 'beginner'),
('fact', '사실', 'truth', 'That is a fact.', 'beginner'),
('hand', '손', 'body part', 'Wash your hands first.', 'beginner'),
('place', '장소', 'location', 'This is a nice place.', 'beginner'),
('week', '주', 'seven days', 'See you next week.', 'beginner'),
('company', '회사', 'business', 'I work for a company.', 'beginner'),
('system', '시스템', 'organized structure', 'The system is broken.', 'beginner'),
('program', '프로그램', 'plan or software', 'Watch this TV program.', 'beginner'),
('question', '질문', 'inquiry', 'Ask me a question.', 'beginner'),
('work', '일', 'job', 'I have much work today.', 'beginner'),
('number', '숫자', 'numerical value', 'Write your phone number.', 'beginner'),
('night', '밤', 'dark hours', 'Good night, sleep well.', 'beginner'),
('point', '점', 'specific location', 'You make a good point.', 'beginner'),
('home', '집', 'residence', 'Let us go home now.', 'beginner'),
('water', '물', 'liquid H2O', 'Drink more water daily.', 'beginner'),
('room', '방', 'enclosed space', 'My room is clean.', 'beginner'),
('mother', '어머니', 'female parent', 'My mother is kind.', 'beginner'),
('area', '지역', 'region', 'This area is safe.', 'beginner'),
('money', '돈', 'currency', 'I need some money.', 'beginner'),
('story', '이야기', 'narrative', 'Tell me a story.', 'beginner'),
('month', '달', 'period of time', 'Last month was cold.', 'beginner'),
('book', '책', 'written work', 'Read this book please.', 'beginner'),
('eye', '눈', 'organ of sight', 'Close your eyes now.', 'beginner'),
('job', '직업', 'work', 'She has a good job.', 'beginner'),
('word', '단어', 'language unit', 'Learn new words daily.', 'beginner'),
('business', '사업', 'commercial activity', 'Business is good now.', 'beginner'),
('friend', '친구', 'companion', 'She is my best friend.', 'beginner'),
('father', '아버지', 'male parent', 'My father is tall.', 'beginner'),
('house', '집', 'building', 'We bought a new house.', 'beginner'),
('food', '음식', 'nourishment', 'Korean food is delicious.', 'beginner'),
('teacher', '선생님', 'educator', 'My teacher is kind.', 'beginner'),
('phone', '전화', 'communication device', 'Answer your phone please.', 'beginner'),
('car', '차', 'vehicle', 'I drive a red car.', 'beginner'),
('city', '도시', 'urban area', 'Seoul is a big city.', 'beginner'),
('name', '이름', 'identifier', 'What is your name?', 'beginner'),

-- Basic Adjectives (50 words)
('good', '좋은', 'positive quality', 'This is a good book.', 'beginner'),
('new', '새로운', 'recent', 'I bought a new phone.', 'beginner'),
('first', '첫번째', 'initial', 'This is my first time.', 'beginner'),
('last', '마지막', 'final', 'This is the last chance.', 'beginner'),
('long', '긴', 'extended', 'That is a long road.', 'beginner'),
('great', '훌륭한', 'excellent', 'You did a great job!', 'beginner'),
('little', '작은', 'small', 'I have a little dog.', 'beginner'),
('old', '오래된', 'aged', 'He lives in an old house.', 'beginner'),
('big', '큰', 'large', 'Seoul is a big city.', 'beginner'),
('high', '높은', 'elevated', 'That mountain is very high.', 'beginner'),
('different', '다른', 'not the same', 'We have different opinions.', 'beginner'),
('small', '작은', 'tiny', 'I live in a small apartment.', 'beginner'),
('large', '큰', 'big', 'We need a large table.', 'beginner'),
('next', '다음', 'following', 'See you next week.', 'beginner'),
('early', '이른', 'before time', 'Wake up early tomorrow.', 'beginner'),
('young', '젊은', 'not old', 'She is still very young.', 'beginner'),
('important', '중요한', 'significant', 'This is very important.', 'beginner'),
('public', '공공의', 'for everyone', 'Use public transportation.', 'beginner'),
('bad', '나쁜', 'negative', 'That is a bad idea.', 'beginner'),
('same', '같은', 'identical', 'We have the same phone.', 'beginner'),
('free', '무료의', 'no cost', 'This service is free.', 'beginner'),
('white', '흰색', 'color', 'I like white shirts.', 'beginner'),
('black', '검은색', 'dark color', 'He wears black shoes.', 'beginner'),
('red', '빨간색', 'color', 'She has a red car.', 'beginner'),
('blue', '파란색', 'color', 'The sky is blue today.', 'beginner'),
('green', '초록색', 'color', 'Trees are green in spring.', 'beginner'),
('happy', '행복한', 'joyful', 'I feel happy today.', 'beginner'),
('sad', '슬픈', 'unhappy', 'Why are you so sad?', 'beginner'),
('tired', '피곤한', 'exhausted', 'I am so tired now.', 'beginner'),
('hungry', '배고픈', 'need food', 'I am very hungry.', 'beginner'),
('hot', '뜨거운', 'high temperature', 'The water is very hot.', 'beginner'),
('cold', '차가운', 'low temperature', 'It is cold outside.', 'beginner'),
('warm', '따뜻한', 'comfortable heat', 'The soup is warm.', 'beginner'),
('fast', '빠른', 'quick', 'He is a fast runner.', 'beginner'),
('slow', '느린', 'not fast', 'This computer is slow.', 'beginner'),
('easy', '쉬운', 'simple', 'This test is easy.', 'beginner'),
('hard', '어려운', 'difficult', 'Math is very hard.', 'beginner'),
('beautiful', '아름다운', 'attractive', 'What a beautiful view!', 'beginner'),
('clean', '깨끗한', 'not dirty', 'Keep your room clean.', 'beginner'),
('dirty', '더러운', 'not clean', 'Your hands are dirty.', 'beginner'),
('full', '가득한', 'filled', 'The glass is full.', 'beginner'),
('empty', '빈', 'nothing inside', 'The room is empty.', 'beginner'),
('heavy', '무거운', 'having weight', 'This box is heavy.', 'beginner'),
('light', '가벼운', 'not heavy', 'This bag is light.', 'beginner'),
('strong', '강한', 'powerful', 'He is very strong.', 'beginner'),
('weak', '약한', 'not strong', 'I feel weak today.', 'beginner'),
('safe', '안전한', 'not dangerous', 'This place is safe.', 'beginner'),
('rich', '부유한', 'wealthy', 'He is a rich man.', 'beginner'),
('poor', '가난한', 'lacking money', 'They are very poor.', 'beginner'),
('ready', '준비된', 'prepared', 'Are you ready to go?', 'beginner'),

-- Numbers & Time (40 words)
('one', '하나', 'number 1', 'I have one apple.', 'beginner'),
('two', '둘', 'number 2', 'There are two cats.', 'beginner'),
('three', '셋', 'number 3', 'I need three chairs.', 'beginner'),
('four', '넷', 'number 4', 'Buy four tickets please.', 'beginner'),
('five', '다섯', 'number 5', 'Wait five minutes.', 'beginner'),
('six', '여섯', 'number 6', 'I work six days.', 'beginner'),
('seven', '일곱', 'number 7', 'There are seven days.', 'beginner'),
('eight', '여덟', 'number 8', 'Class starts at eight.', 'beginner'),
('nine', '아홉', 'number 9', 'I have nine books.', 'beginner'),
('ten', '열', 'number 10', 'Count to ten slowly.', 'beginner'),
('today', '오늘', 'this day', 'What day is today?', 'beginner'),
('yesterday', '어제', 'day before', 'I saw him yesterday.', 'beginner'),
('tomorrow', '내일', 'day after', 'See you tomorrow morning.', 'beginner'),
('now', '지금', 'at this moment', 'Come here right now.', 'beginner'),
('later', '나중에', 'after this', 'I will call you later.', 'beginner'),
('soon', '곧', 'in near future', 'Spring will come soon.', 'beginner'),
('always', '항상', 'every time', 'I always wake up early.', 'beginner'),
('never', '절대', 'not ever', 'I never eat meat.', 'beginner'),
('sometimes', '때때로', 'occasionally', 'I sometimes drink coffee.', 'beginner'),
('often', '자주', 'frequently', 'I often visit my parents.', 'beginner'),
('Monday', '월요일', 'first weekday', 'I hate Monday mornings.', 'beginner'),
('Tuesday', '화요일', 'second weekday', 'See you on Tuesday.', 'beginner'),
('Wednesday', '수요일', 'third weekday', 'Wednesday is meeting day.', 'beginner'),
('Thursday', '목요일', 'fourth weekday', 'Call me on Thursday.', 'beginner'),
('Friday', '금요일', 'fifth weekday', 'Friday is my favorite.', 'beginner'),
('Saturday', '토요일', 'sixth weekday', 'I rest on Saturday.', 'beginner'),
('Sunday', '일요일', 'seventh weekday', 'Sunday is family day.', 'beginner'),
('January', '1월', 'first month', 'January is very cold.', 'beginner'),
('February', '2월', 'second month', 'My birthday is in February.', 'beginner'),
('March', '3월', 'third month', 'Spring starts in March.', 'beginner'),
('April', '4월', 'fourth month', 'April showers bring flowers.', 'beginner'),
('May', '5월', 'fifth month', 'May is a beautiful month.', 'beginner'),
('June', '6월', 'sixth month', 'School ends in June.', 'beginner'),
('July', '7월', 'seventh month', 'July is very hot here.', 'beginner'),
('August', '8월', 'eighth month', 'I vacation in August.', 'beginner'),
('September', '9월', 'ninth month', 'School starts in September.', 'beginner'),
('October', '10월', 'tenth month', 'October has nice weather.', 'beginner'),
('November', '11월', 'eleventh month', 'November is autumn time.', 'beginner'),
('December', '12월', 'twelfth month', 'December is Christmas month.', 'beginner'),
('spring', '봄', 'warm season', 'I love spring flowers.', 'beginner'),

-- Common Words (40 words)
('how', '어떻게', 'in what way', 'How are you today?', 'beginner'),
('why', '왜', 'for what reason', 'Why did you come late?', 'beginner'),
('when', '언제', 'at what time', 'When will you arrive?', 'beginner'),
('where', '어디', 'in what place', 'Where do you live?', 'beginner'),
('what', '무엇', 'which thing', 'What is your name?', 'beginner'),
('who', '누구', 'which person', 'Who is that man?', 'beginner'),
('which', '어느', 'what one', 'Which book do you want?', 'beginner'),
('because', '왜냐하면', 'for the reason that', 'I stayed home because it rained.', 'beginner'),
('but', '그러나', 'however', 'I want to go but I am busy.', 'beginner'),
('and', '그리고', 'also', 'I like coffee and tea.', 'beginner'),
('or', '또는', 'alternative', 'Do you want tea or coffee?', 'beginner'),
('so', '그래서', 'therefore', 'I was tired so I slept.', 'beginner'),
('if', '만약', 'in case', 'If it rains, stay home.', 'beginner'),
('very', '매우', 'extremely', 'This is very good!', 'beginner'),
('too', '너무', 'excessively', 'This is too expensive.', 'beginner'),
('much', '많은', 'great amount', 'I have too much work.', 'beginner'),
('many', '많은', 'numerous', 'There are many people.', 'beginner'),
('some', '약간', 'a few', 'Give me some water.', 'beginner'),
('any', '어떤', 'one or more', 'Do you have any questions?', 'beginner'),
('all', '모두', 'every one', 'All students passed the test.', 'beginner'),
('each', '각각', 'every single', 'Each person gets one.', 'beginner'),
('every', '모든', 'all', 'I study every day.', 'beginner'),
('here', '여기', 'in this place', 'Come over here please.', 'beginner'),
('there', '저기', 'in that place', 'Put it over there.', 'beginner'),
('up', '위로', 'to higher place', 'Look up at the sky.', 'beginner'),
('down', '아래로', 'to lower place', 'Sit down on the chair.', 'beginner'),
('in', '안에', 'inside', 'The cat is in the box.', 'beginner'),
('out', '밖에', 'outside', 'The dog is out there.', 'beginner'),
('on', '위에', 'upon', 'The book is on the table.', 'beginner'),
('off', '떨어져', 'away from', 'Take your shoes off.', 'beginner'),
('over', '위에', 'above', 'The plane flew over us.', 'beginner'),
('under', '아래에', 'below', 'The cat is under the table.', 'beginner'),
('before', '전에', 'earlier than', 'Come before noon.', 'beginner'),
('after', '후에', 'later than', 'Call me after lunch.', 'beginner'),
('between', '사이에', 'in the middle', 'Sit between them.', 'beginner'),
('with', '함께', 'together', 'Come with me now.', 'beginner'),
('without', '없이', 'lacking', 'Do not go without me.', 'beginner'),
('about', '대해', 'concerning', 'Tell me about your day.', 'beginner'),
('learn', '배우다', 'to acquire knowledge', 'I want to learn Korean.', 'beginner'),
('study', '공부하다', 'to learn', 'I study English every day.', 'beginner'),

-- Additional Essential Words (60 words)
('read', '읽다', 'to look at words', 'I read a book yesterday.', 'beginner'),
('open', '열다', 'to unlock', 'Open the window please.', 'beginner'),
('walk', '걷다', 'to move on foot', 'I walk to school.', 'beginner'),
('teach', '가르치다', 'to educate', 'I teach English online.', 'beginner'),
('remember', '기억하다', 'to recall', 'I remember your birthday.', 'beginner'),
('buy', '사다', 'to purchase', 'I will buy new shoes.', 'beginner'),
('wait', '기다리다', 'to remain', 'Wait for me here.', 'beginner'),
('send', '보내다', 'to dispatch', 'Send me an email.', 'beginner'),
('stay', '머물다', 'to remain', 'Stay with me tonight.', 'beginner'),
('cut', '자르다', 'to divide', 'Cut the paper in half.', 'beginner'),
('change', '바꾸다', 'to alter', 'Can you change this tire?', 'beginner'),
('understand', '이해하다', 'to comprehend', 'I understand your problem.', 'beginner'),
('watch', '보다', 'to observe', 'I watch TV every night.', 'beginner'),
('follow', '따르다', 'to go after', 'Follow me this way.', 'beginner'),
('stop', '멈추다', 'to cease', 'Stop talking and listen.', 'beginner'),
('create', '창조하다', 'to make', 'Artists create beautiful works.', 'beginner'),
('speak', '말하다', 'to talk', 'Can you speak English?', 'beginner'),
('grow', '자라다', 'to increase', 'Plants grow in spring.', 'beginner'),
('win', '이기다', 'to be victorious', 'Our team will win today.', 'beginner'),
('offer', '제공하다', 'to present', 'Can I offer you coffee?', 'beginner'),
('consider', '고려하다', 'to think about', 'Consider all options first.', 'beginner'),
('appear', '나타나다', 'to become visible', 'Stars appear at night.', 'beginner'),
('serve', '제공하다', 'to provide service', 'They serve good food.', 'beginner'),
('expect', '기대하다', 'to anticipate', 'I expect good results.', 'beginner'),
('build', '짓다', 'to construct', 'They build houses fast.', 'beginner'),
('fall', '떨어지다', 'to descend', 'Leaves fall in autumn.', 'beginner'),
('reach', '도달하다', 'to arrive at', 'We will reach soon.', 'beginner'),
('suggest', '제안하다', 'to propose', 'I suggest we leave early.', 'beginner'),
('raise', '올리다', 'to lift', 'Raise your hand please.', 'beginner'),
('pass', '지나가다', 'to go by', 'Time passes quickly.', 'beginner'),
('sell', '팔다', 'to trade', 'They sell fresh fruit.', 'beginner'),
('decide', '결정하다', 'to choose', 'You must decide now.', 'beginner'),
('pull', '당기다', 'to drag', 'Pull the door open.', 'beginner'),
('break', '부수다', 'to shatter', 'Do not break the glass.', 'beginner'),
('pick', '고르다', 'to select', 'Pick your favorite color.', 'beginner'),
('wear', '입다', 'to have on', 'Wear a warm coat.', 'beginner'),
('enjoy', '즐기다', 'to take pleasure', 'Enjoy your vacation!', 'beginner'),
('drive', '운전하다', 'to operate vehicle', 'Can you drive a car?', 'beginner'),
('draw', '그리다', 'to sketch', 'She draws very well.', 'beginner'),
('choose', '선택하다', 'to pick', 'Choose one answer.', 'beginner'),
('cook', '요리하다', 'to prepare food', 'I cook dinner daily.', 'beginner'),
('clean', '청소하다', 'to make tidy', 'Clean your room now.', 'beginner'),
('hospital', '병원', 'medical facility', 'He is in the hospital.', 'beginner'),
('restaurant', '식당', 'eating place', 'This restaurant is good.', 'beginner'),
('airport', '공항', 'flight terminal', 'Meet me at the airport.', 'beginner'),
('hotel', '호텔', 'lodging', 'Book a hotel room.', 'beginner'),
('bank', '은행', 'financial institution', 'Go to the bank tomorrow.', 'beginner'),
('store', '가게', 'shop', 'Buy it at that store.', 'beginner'),
('park', '공원', 'recreational area', 'Play in the park.', 'beginner'),
('market', '시장', 'trading place', 'Shop at the market.', 'beginner'),
('station', '역', 'stop point', 'Meet at the train station.', 'beginner'),
('doctor', '의사', 'physician', 'See a doctor soon.', 'beginner'),
('brother', '형제', 'male sibling', 'My brother is younger.', 'beginner'),
('sister', '자매', 'female sibling', 'My sister is older.', 'beginner'),
('husband', '남편', 'married man', 'Her husband is kind.', 'beginner'),
('wife', '아내', 'married woman', 'His wife is a teacher.', 'beginner'),
('summer', '여름', 'hot season', 'Summer is too hot.', 'beginner'),
('winter', '겨울', 'cold season', 'Winter is my favorite.', 'beginner'),
('morning', '아침', 'early day', 'Good morning everyone!', 'beginner'),
('afternoon', '오후', 'after noon', 'See you this afternoon.', 'beginner');

-- Verify insertion
SELECT COUNT(*) AS total_words FROM vocabulary_words;
SELECT * FROM vocabulary_words ORDER BY id LIMIT 10;
