-- Part 1: Words 1-50
INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, example_sentence, difficulty) VALUES
('achieve', '달성하다', 'to accomplish', 'We achieved our sales target.', 'intermediate'),
('advantage', '이점', 'a beneficial factor', 'This gives us a competitive advantage.', 'intermediate'),
('analyze', '분석하다', 'to examine in detail', 'Let me analyze the data.', 'intermediate'),
('approach', '접근하다', 'to come near', 'We need a different approach.', 'intermediate'),
('appropriate', '적절한', 'suitable', 'Choose an appropriate method.', 'intermediate'),
('assess', '평가하다', 'to evaluate', 'We must assess the situation.', 'intermediate'),
('assume', '가정하다', 'to suppose', 'I assume you agree.', 'intermediate'),
('authority', '권한', 'power', 'She has the authority to decide.', 'intermediate'),
('available', '이용 가능한', 'ready for use', 'The report is available now.', 'intermediate'),
('benefit', '혜택', 'advantage', 'This offers many benefits.', 'intermediate'),
('challenge', '도전', 'a difficult task', 'This is a big challenge.', 'intermediate'),
('circumstances', '상황', 'conditions', 'Under these circumstances...', 'intermediate'),
('colleague', '동료', 'coworker', 'My colleague helped me.', 'intermediate'),
('commit', '약속하다', 'to pledge', 'I commit to finishing this.', 'intermediate'),
('communicate', '의사소통하다', 'to share information', 'We need to communicate better.', 'intermediate'),
('community', '공동체', 'a group', 'Our local community is strong.', 'intermediate'),
('compare', '비교하다', 'to examine differences', 'Compare these two options.', 'intermediate'),
('compete', '경쟁하다', 'to rival', 'We compete with many companies.', 'intermediate'),
('complex', '복잡한', 'complicated', 'This is a complex problem.', 'intermediate'),
('concentrate', '집중하다', 'to focus', 'Please concentrate on your work.', 'intermediate'),
('concept', '개념', 'an idea', 'This concept is important.', 'intermediate'),
('concern', '우려', 'worry', 'Safety is our main concern.', 'intermediate'),
('conclude', '결론짓다', 'to finish', 'Let me conclude my presentation.', 'intermediate'),
('conduct', '수행하다', 'to carry out', 'We will conduct a survey.', 'intermediate'),
('conflict', '갈등', 'disagreement', 'There is a conflict of interest.', 'intermediate'),
('consequence', '결과', 'result', 'Consider the consequences.', 'intermediate'),
('consist', '구성되다', 'to be made up of', 'The team consists of five members.', 'intermediate'),
('constant', '지속적인', 'continuous', 'There is constant change.', 'intermediate'),
('construct', '건설하다', 'to build', 'They will construct a new building.', 'intermediate'),
('consume', '소비하다', 'to use up', 'We consume too much energy.', 'intermediate'),
('context', '맥락', 'circumstances', 'Consider the context.', 'intermediate'),
('contract', '계약', 'an agreement', 'Sign the contract here.', 'intermediate'),
('contrast', '대조', 'difference', 'In contrast to last year...', 'intermediate'),
('contribute', '기여하다', 'to give', 'Everyone should contribute ideas.', 'intermediate'),
('convince', '설득하다', 'to persuade', 'I need to convince them.', 'intermediate'),
('cooperate', '협력하다', 'to work together', 'We must cooperate on this.', 'intermediate'),
('create', '창조하다', 'to make', 'Let us create something new.', 'intermediate'),
('crucial', '결정적인', 'extremely important', 'This is a crucial moment.', 'intermediate'),
('debate', '토론', 'discussion', 'We had a debate about it.', 'intermediate'),
('decline', '거절하다', 'to refuse', 'I must decline your offer.', 'intermediate'),
('define', '정의하다', 'to explain meaning', 'How do you define success?', 'intermediate'),
('demonstrate', '입증하다', 'to show', 'Let me demonstrate how it works.', 'intermediate'),
('depend', '의존하다', 'to rely on', 'It depends on the weather.', 'intermediate'),
('derive', '유래하다', 'to obtain from', 'The word derives from Latin.', 'intermediate'),
('design', '설계하다', 'to plan', 'She will design the website.', 'intermediate'),
('despite', '~에도 불구하고', 'in spite of', 'Despite the rain, we went out.', 'intermediate'),
('detect', '탐지하다', 'to discover', 'The system can detect errors.', 'intermediate'),
('determine', '결정하다', 'to decide', 'We need to determine the cause.', 'intermediate'),
('device', '장치', 'a tool', 'This device is very useful.', 'intermediate'),
('distribute', '분배하다', 'to give out', 'Please distribute these papers.', 'intermediate');