-- Part 4: Words 151-200
INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, example_sentence, difficulty) VALUES
('depress', '우울하게 하다', 'to sadden', 'Bad news can depress people.', 'advanced'),
('device', '장치', 'tool', 'This device is innovative.', 'advanced'),
('differentiate', '구별하다', 'to distinguish', 'Differentiate between them.', 'advanced'),
('dimension', '차원', 'aspect', 'Consider every dimension.', 'advanced'),
('diminish', '줄어들다', 'to decrease', 'The effect will diminish.', 'advanced'),
('discrete', '별개의', 'separate', 'These are discrete issues.', 'advanced'),
('discriminate', '차별하다', 'to distinguish', 'Do not discriminate unfairly.', 'advanced'),
('displace', '이동시키다', 'to move', 'The water will displace.', 'advanced'),
('dispose', '처분하다', 'to get rid of', 'Dispose of waste properly.', 'advanced'),
('distinct', '뚜렷한', 'clear', 'There is a distinct difference.', 'advanced'),
('distort', '왜곡하다', 'to twist', 'Do not distort the facts.', 'advanced'),
('diverse', '다양한', 'varied', 'We have a diverse team.', 'advanced'),
('drama', '드라마', 'play', 'Shakespeare wrote many dramas.', 'advanced'),
('duration', '기간', 'length of time', 'The duration is two hours.', 'advanced'),
('dynamic', '역동적인', 'energetic', 'She has a dynamic personality.', 'advanced'),
('elaborate', '정교한', 'detailed', 'The plan is very elaborate.', 'advanced'),
('enforce', '시행하다', 'to impose', 'Enforce the rules strictly.', 'advanced'),
('entity', '실체', 'thing', 'The company is a legal entity.', 'advanced'),
('equivalent', '동등한', 'equal', 'This is equivalent to $100.', 'advanced'),
('erode', '침식하다', 'to wear away', 'Trust can erode quickly.', 'advanced'),
('ethic', '윤리', 'moral principle', 'Business ethics matter.', 'advanced'),
('evolve', '진화하다', 'to develop', 'Technology continues to evolve.', 'advanced'),
('explicit', '명백한', 'clear', 'Give explicit instructions.', 'advanced'),
('exploit', '착취하다', 'to use', 'Do not exploit workers.', 'advanced'),
('expose', '폭로하다', 'to reveal', 'Expose the corruption.', 'advanced'),
('extract', '추출하다', 'to remove', 'Extract the key points.', 'advanced'),
('facilitate', '용이하게 하다', 'to help', 'Technology facilitates learning.', 'advanced'),
('format', '형식', 'arrangement', 'Follow this format.', 'advanced'),
('forthcoming', '다가오는', 'approaching', 'Details will be forthcoming.', 'advanced'),
('framework', '틀', 'structure', 'Establish a framework.', 'advanced'),
('futile', '헛된', 'useless', 'Resistance is futile.', 'advanced'),
('gender', '성별', 'sex', 'Gender equality is important.', 'advanced'),
('generate', '발생시키다', 'to produce', 'Generate new ideas.', 'advanced'),
('hierarchy', '계층', 'ranking system', 'The corporate hierarchy is clear.', 'advanced'),
('hypothesis', '가설', 'theory', 'Test the hypothesis.', 'advanced'),
('ideological', '이념적인', 'relating to ideas', 'Ideological differences exist.', 'advanced'),
('ignorant', '무지한', 'lacking knowledge', 'He is ignorant of the facts.', 'advanced'),
('immigrate', '이민하다', 'to move to', 'Many people immigrate here.', 'advanced'),
('implicit', '암묵적인', 'implied', 'There is implicit agreement.', 'advanced'),
('incentive', '동기', 'motivation', 'Provide incentives for performance.', 'advanced'),
('incline', '경향', 'tendency', 'I incline to agree.', 'advanced'),
('incorporate', '통합하다', 'to include', 'Incorporate these changes.', 'advanced'),
('infrastructure', '기반시설', 'basic systems', 'Improve the infrastructure.', 'advanced'),
('inherent', '고유한', 'natural', 'There are inherent risks.', 'advanced'),
('inhibit', '억제하다', 'to prevent', 'This will inhibit growth.', 'advanced'),
('initiate', '시작하다', 'to begin', 'Initiate the project.', 'advanced'),
('innovation', '혁신', 'new idea', 'Innovation drives success.', 'advanced'),
('integral', '필수적인', 'essential', 'This is integral to the plan.', 'advanced'),
('integrate', '통합하다', 'to combine', 'Integrate the systems.', 'advanced'),
('intelligence', '지능', 'mental ability', 'Artificial intelligence is advancing.', 'advanced');