-- Additional Intermediate Words (중급 - 100 words)
INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, example_sentence, difficulty) VALUES
-- Business & Work
('achieve', '달성하다', 'to accomplish', 'We achieved our sales target.', 'intermediate'),
('advantage', '이점', 'a beneficial factor', 'This gives us a competitive advantage.', 'intermediate'),
('analyze', '분석하다', 'to examine in detail', 'Let me analyze the data.', 'intermediate'),
('approach', '접근하다', 'to come near', 'We need a different approach.', 'intermediate'),
('appropriate', '적절한', 'suitable', 'Choose an appropriate method.', 'intermediate'),
('assess', '평가하다', 'to evaluate', 'We must assess the situation.', 'intermediate'),
('assume', '가정하다', 'to suppose', 'I assume you agree.', 'intermediate'),
('authority', '권한', 'power', 'She has the authority to decide.', 'intermediate'),
('available', '이용 가능한', 'ready for use', 'The report is available now.', 'intermediate'),
('benefit', '혜택', 'advantage', 'This offers many benefits.', 'intermediate'),
('challenge', '도전', 'a difficult task', 'This is a big challenge.', 'intermediate'),
('circumstances', '상황', 'conditions', 'Under these circumstances...', 'intermediate'),
('colleague', '동료', 'coworker', 'My colleague helped me.', 'intermediate'),
('commit', '약속하다', 'to pledge', 'I commit to finishing this.', 'intermediate'),
('communicate', '의사소통하다', 'to share information', 'We need to communicate better.', 'intermediate'),
('community', '공동체', 'a group', 'Our local community is strong.', 'intermediate'),
('compare', '비교하다', 'to examine differences', 'Compare these two options.', 'intermediate'),
('compete', '경쟁하다', 'to rival', 'We compete with many companies.', 'intermediate'),
('complex', '복잡한', 'complicated', 'This is a complex problem.', 'intermediate'),
('concentrate', '집중하다', 'to focus', 'Please concentrate on your work.', 'intermediate'),

-- Academic & Education
('concept', '개념', 'an idea', 'This concept is important.', 'intermediate'),
('concern', '우려', 'worry', 'Safety is our main concern.', 'intermediate'),
('conclude', '결론짓다', 'to finish', 'Let me conclude my presentation.', 'intermediate'),
('conduct', '수행하다', 'to carry out', 'We will conduct a survey.', 'intermediate'),
('conflict', '갈등', 'disagreement', 'There is a conflict of interest.', 'intermediate'),
('consequence', '결과', 'result', 'Consider the consequences.', 'intermediate'),
('consist', '구성되다', 'to be made up of', 'The team consists of five members.', 'intermediate'),
('constant', '지속적인', 'continuous', 'There is constant change.', 'intermediate'),
('construct', '건설하다', 'to build', 'They will construct a new building.', 'intermediate'),
('consume', '소비하다', 'to use up', 'We consume too much energy.', 'intermediate'),
('context', '맥락', 'circumstances', 'Consider the context.', 'intermediate'),
('contract', '계약', 'an agreement', 'Sign the contract here.', 'intermediate'),
('contrast', '대조', 'difference', 'In contrast to last year...', 'intermediate'),
('contribute', '기여하다', 'to give', 'Everyone should contribute ideas.', 'intermediate'),
('convince', '설득하다', 'to persuade', 'I need to convince them.', 'intermediate'),
('cooperate', '협력하다', 'to work together', 'We must cooperate on this.', 'intermediate'),
('create', '창조하다', 'to make', 'Let us create something new.', 'intermediate'),
('crucial', '결정적인', 'extremely important', 'This is a crucial moment.', 'intermediate'),
('debate', '토론', 'discussion', 'We had a debate about it.', 'intermediate'),
('decline', '거절하다', 'to refuse', 'I must decline your offer.', 'intermediate'),

-- Technology & Modern Life
('define', '정의하다', 'to explain meaning', 'How do you define success?', 'intermediate'),
('demonstrate', '입증하다', 'to show', 'Let me demonstrate how it works.', 'intermediate'),
('depend', '의존하다', 'to rely on', 'It depends on the weather.', 'intermediate'),
('derive', '유래하다', 'to obtain from', 'The word derives from Latin.', 'intermediate'),
('design', '설계하다', 'to plan', 'She will design the website.', 'intermediate'),
('despite', '~에도 불구하고', 'in spite of', 'Despite the rain, we went out.', 'intermediate'),
('detect', '탐지하다', 'to discover', 'The system can detect errors.', 'intermediate'),
('determine', '결정하다', 'to decide', 'We need to determine the cause.', 'intermediate'),
('device', '장치', 'a tool', 'This device is very useful.', 'intermediate'),
('distribute', '분배하다', 'to give out', 'Please distribute these papers.', 'intermediate'),
('document', '문서', 'a written record', 'Read this document carefully.', 'intermediate'),
('domestic', '국내의', 'relating to home', 'Domestic sales increased.', 'intermediate'),
('dominant', '지배적인', 'most powerful', 'English is the dominant language.', 'intermediate'),
('economy', '경제', 'financial system', 'The economy is growing.', 'intermediate'),
('efficient', '효율적인', 'working well', 'This is a very efficient method.', 'intermediate'),
('eliminate', '제거하다', 'to remove', 'We need to eliminate waste.', 'intermediate'),
('emerge', '나타나다', 'to appear', 'New problems emerged.', 'intermediate'),
('emphasis', '강조', 'special importance', 'Put emphasis on quality.', 'intermediate'),
('enable', '가능하게 하다', 'to make possible', 'This will enable us to work faster.', 'intermediate'),
('encounter', '마주치다', 'to meet', 'I encountered a problem.', 'intermediate'),

-- Daily Life & Communication
('enhance', '향상시키다', 'to improve', 'This will enhance performance.', 'intermediate'),
('ensure', '보장하다', 'to make certain', 'Please ensure everything is ready.', 'intermediate'),
('environment', '환경', 'surroundings', 'Protect the environment.', 'intermediate'),
('establish', '확립하다', 'to set up', 'We will establish new rules.', 'intermediate'),
('estimate', '추정하다', 'to calculate', 'I estimate it will take two hours.', 'intermediate'),
('evaluate', '평가하다', 'to assess', 'We need to evaluate the results.', 'intermediate'),
('evidence', '증거', 'proof', 'There is no evidence.', 'intermediate'),
('exceed', '초과하다', 'to go beyond', 'Sales exceeded expectations.', 'intermediate'),
('exclude', '제외하다', 'to leave out', 'This price excludes tax.', 'intermediate'),
('expand', '확장하다', 'to grow', 'We plan to expand our business.', 'intermediate'),
('expert', '전문가', 'specialist', 'Consult an expert.', 'intermediate'),
('explicit', '명확한', 'clear', 'Give explicit instructions.', 'intermediate'),
('expose', '노출시키다', 'to reveal', 'Do not expose it to sunlight.', 'intermediate'),
('external', '외부의', 'outside', 'External factors matter.', 'intermediate'),
('facilitate', '촉진하다', 'to make easier', 'This will facilitate communication.', 'intermediate'),
('factor', '요인', 'an element', 'Price is an important factor.', 'intermediate'),
('feature', '특징', 'characteristic', 'The main feature is speed.', 'intermediate'),
('finance', '재정', 'money management', 'Our finance team handles this.', 'intermediate'),
('flexible', '유연한', 'adaptable', 'Be flexible with your schedule.', 'intermediate'),
('focus', '집중하다', 'to concentrate', 'Focus on the main issue.', 'intermediate'),
('function', '기능', 'purpose', 'What is its function?', 'intermediate'),
('fundamental', '근본적인', 'basic', 'This is a fundamental principle.', 'intermediate'),
('generate', '생성하다', 'to create', 'This will generate profits.', 'intermediate'),
('goal', '목표', 'objective', 'Our goal is clear.', 'intermediate'),
('grant', '허가하다', 'to give', 'They granted permission.', 'intermediate'),
('guarantee', '보장하다', 'to promise', 'We guarantee quality.', 'intermediate'),
('guideline', '지침', 'recommendation', 'Follow these guidelines.', 'intermediate'),
('hence', '그러므로', 'therefore', 'Hence, we must act now.', 'intermediate'),
('highlight', '강조하다', 'to emphasize', 'Let me highlight key points.', 'intermediate'),
('identify', '식별하다', 'to recognize', 'Can you identify the problem?', 'intermediate'),
('illustrate', '설명하다', 'to show', 'This example illustrates the point.', 'intermediate'),
('impact', '영향', 'effect', 'It had a big impact.', 'intermediate'),
('implement', '실행하다', 'to carry out', 'We will implement new policies.', 'intermediate'),
('imply', '암시하다', 'to suggest', 'What does this imply?', 'intermediate'),
('impose', '부과하다', 'to force', 'They imposed new taxes.', 'intermediate'),
('indicate', '나타내다', 'to show', 'The data indicates growth.', 'intermediate'),
('individual', '개인', 'person', 'Each individual is different.', 'intermediate'),
('inevitable', '불가피한', 'unavoidable', 'Change is inevitable.', 'intermediate'),
('influence', '영향을 미치다', 'to affect', 'This will influence the outcome.', 'intermediate'),
('initial', '초기의', 'first', 'The initial reaction was positive.', 'intermediate');

-- Advanced Words (고급 - 100 words)
INSERT INTO vocabulary_words (word, meaning_ko, meaning_en, example_sentence, difficulty) VALUES
-- Academic & Professional
('accelerate', '가속화하다', 'to speed up', 'We need to accelerate the process.', 'advanced'),
('accommodate', '수용하다', 'to provide for', 'The hotel can accommodate 200 guests.', 'advanced'),
('accumulate', '축적하다', 'to gather', 'Experience accumulates over time.', 'advanced'),
('adjacent', '인접한', 'next to', 'The office is adjacent to the bank.', 'advanced'),
('advocate', '옹호하다', 'to support', 'I advocate for environmental protection.', 'advanced'),
('aggregate', '총계', 'total', 'The aggregate amount is significant.', 'advanced'),
('allocate', '할당하다', 'to distribute', 'We must allocate resources wisely.', 'advanced'),
('ambiguous', '애매한', 'unclear', 'The statement was ambiguous.', 'advanced'),
('amendment', '수정', 'a change', 'The amendment was approved.', 'advanced'),
('analogy', '비유', 'comparison', 'Let me use an analogy.', 'advanced'),
('anticipate', '예상하다', 'to expect', 'We anticipate strong demand.', 'advanced'),
('arbitrary', '임의의', 'random', 'The decision seemed arbitrary.', 'advanced'),
('assemble', '조립하다', 'to put together', 'Assemble the parts carefully.', 'advanced'),
('attribute', '속성', 'characteristic', 'List the key attributes.', 'advanced'),
('autonomy', '자율성', 'independence', 'The team has full autonomy.', 'advanced'),
('bias', '편견', 'prejudice', 'Avoid bias in your judgment.', 'advanced'),
('capable', '유능한', 'able', 'She is highly capable.', 'advanced'),
('capacity', '용량', 'ability', 'The capacity is 100 people.', 'advanced'),
('cease', '중단하다', 'to stop', 'The fighting must cease.', 'advanced'),
('coherent', '일관된', 'logical', 'Make a coherent argument.', 'advanced'),

-- Business & Economics
('coincide', '일치하다', 'to occur together', 'Our meetings coincide.', 'advanced'),
('collapse', '붕괴하다', 'to fall down', 'The building could collapse.', 'advanced'),
('commence', '시작하다', 'to begin', 'The ceremony will commence at 9.', 'advanced'),
('compatible', '호환되는', 'able to work together', 'Are these systems compatible?', 'advanced'),
('compensate', '보상하다', 'to pay', 'We will compensate for the loss.', 'advanced'),
('compile', '편집하다', 'to collect', 'Compile the reports.', 'advanced'),
('complement', '보완하다', 'to complete', 'These skills complement each other.', 'advanced'),
('comprehensive', '포괄적인', 'complete', 'This is a comprehensive guide.', 'advanced'),
('comprise', '구성하다', 'to consist of', 'The team comprises experts.', 'advanced'),
('conceive', '생각해내다', 'to imagine', 'I cannot conceive of a solution.', 'advanced'),
('concurrent', '동시의', 'happening together', 'Concurrent events occurred.', 'advanced'),
('confine', '제한하다', 'to restrict', 'Confine your comments to the topic.', 'advanced'),
('conform', '따르다', 'to comply', 'We must conform to regulations.', 'advanced'),
('consent', '동의', 'agreement', 'I need your consent.', 'advanced'),
('considerable', '상당한', 'significant', 'There is considerable interest.', 'advanced'),
('constrain', '제약하다', 'to limit', 'Budget constraints apply.', 'advanced'),
('contemporary', '현대의', 'modern', 'Contemporary art is popular.', 'advanced'),
('contradict', '모순되다', 'to oppose', 'These statements contradict.', 'advanced'),
('contrary', '반대의', 'opposite', 'Contrary to expectations...', 'advanced'),
('convene', '소집하다', 'to gather', 'The committee will convene tomorrow.', 'advanced'),

-- Science & Technology
('conventional', '전통적인', 'traditional', 'Use conventional methods.', 'advanced'),
('convert', '변환하다', 'to change', 'Convert dollars to euros.', 'advanced'),
('coordinate', '조정하다', 'to organize', 'Coordinate the activities.', 'advanced'),
('core', '핵심', 'center', 'This is the core issue.', 'advanced'),
('corporate', '기업의', 'relating to business', 'Corporate policy changed.', 'advanced'),
('correspond', '일치하다', 'to match', 'These numbers correspond.', 'advanced'),
('criterion', '기준', 'standard', 'What is the main criterion?', 'advanced'),
('crucial', '중대한', 'critical', 'This is a crucial decision.', 'advanced'),
('currency', '통화', 'money', 'The local currency is weak.', 'advanced'),
('denote', '나타내다', 'to indicate', 'Red denotes danger.', 'advanced'),
('depress', '우울하게 하다', 'to sadden', 'Bad news can depress people.', 'advanced'),
('device', '장치', 'tool', 'This device is innovative.', 'advanced'),
('differentiate', '구별하다', 'to distinguish', 'Differentiate between them.', 'advanced'),
('dimension', '차원', 'aspect', 'Consider every dimension.', 'advanced'),
('diminish', '줄어들다', 'to decrease', 'The effect will diminish.', 'advanced'),
('discrete', '별개의', 'separate', 'These are discrete issues.', 'advanced'),
('discriminate', '차별하다', 'to distinguish', 'Do not discriminate unfairly.', 'advanced'),
('displace', '이동시키다', 'to move', 'The water will displace.', 'advanced'),
('dispose', '처분하다', 'to get rid of', 'Dispose of waste properly.', 'advanced'),
('distinct', '뚜렷한', 'clear', 'There is a distinct difference.', 'advanced'),

-- Philosophy & Society
('distort', '왜곡하다', 'to twist', 'Do not distort the facts.', 'advanced'),
('diverse', '다양한', 'varied', 'We have a diverse team.', 'advanced'),
('drama', '드라마', 'play', 'Shakespeare wrote many dramas.', 'advanced'),
('duration', '기간', 'length of time', 'The duration is two hours.', 'advanced'),
('dynamic', '역동적인', 'energetic', 'She has a dynamic personality.', 'advanced'),
('elaborate', '정교한', 'detailed', 'The plan is very elaborate.', 'advanced'),
('enforce', '시행하다', 'to impose', 'Enforce the rules strictly.', 'advanced'),
('entity', '실체', 'thing', 'The company is a legal entity.', 'advanced'),
('equivalent', '동등한', 'equal', 'This is equivalent to $100.', 'advanced'),
('erode', '침식하다', 'to wear away', 'Trust can erode quickly.', 'advanced'),
('ethic', '윤리', 'moral principle', 'Business ethics matter.', 'advanced'),
('evolve', '진화하다', 'to develop', 'Technology continues to evolve.', 'advanced'),
('explicit', '명백한', 'clear', 'Give explicit instructions.', 'advanced'),
('exploit', '착취하다', 'to use', 'Do not exploit workers.', 'advanced'),
('expose', '폭로하다', 'to reveal', 'Expose the corruption.', 'advanced'),
('extract', '추출하다', 'to remove', 'Extract the key points.', 'advanced'),
('facilitate', '용이하게 하다', 'to help', 'Technology facilitates learning.', 'advanced'),
('format', '형식', 'arrangement', 'Follow this format.', 'advanced'),
('forthcoming', '다가오는', 'approaching', 'Details will be forthcoming.', 'advanced'),
('framework', '틀', 'structure', 'Establish a framework.', 'advanced'),
('futile', '헛된', 'useless', 'Resistance is futile.', 'advanced'),
('gender', '성별', 'sex', 'Gender equality is important.', 'advanced'),
('generate', '발생시키다', 'to produce', 'Generate new ideas.', 'advanced'),
('hierarchy', '계층', 'ranking system', 'The corporate hierarchy is clear.', 'advanced'),
('hypothesis', '가설', 'theory', 'Test the hypothesis.', 'advanced'),
('ideological', '이념적인', 'relating to ideas', 'Ideological differences exist.', 'advanced'),
('ignorant', '무지한', 'lacking knowledge', 'He is ignorant of the facts.', 'advanced'),
('immigrate', '이민하다', 'to move to', 'Many people immigrate here.', 'advanced'),
('implicit', '암묵적인', 'implied', 'There is implicit agreement.', 'advanced'),
('incentive', '동기', 'motivation', 'Provide incentives for performance.', 'advanced'),
('incline', '경향', 'tendency', 'I incline to agree.', 'advanced'),
('incorporate', '통합하다', 'to include', 'Incorporate these changes.', 'advanced'),
('infrastructure', '기반시설', 'basic systems', 'Improve the infrastructure.', 'advanced'),
('inherent', '고유한', 'natural', 'There are inherent risks.', 'advanced'),
('inhibit', '억제하다', 'to prevent', 'This will inhibit growth.', 'advanced'),
('initiate', '시작하다', 'to begin', 'Initiate the project.', 'advanced'),
('innovation', '혁신', 'new idea', 'Innovation drives success.', 'advanced'),
('integral', '필수적인', 'essential', 'This is integral to the plan.', 'advanced'),
('integrate', '통합하다', 'to combine', 'Integrate the systems.', 'advanced'),
('intelligence', '지능', 'mental ability', 'Artificial intelligence is advancing.', 'advanced'),
('interact', '상호작용하다', 'to communicate', 'Students interact with teachers.', 'advanced'),
('intermediate', '중간의', 'in between', 'This is an intermediate level.', 'advanced'),
('internal', '내부의', 'inside', 'Internal processes need improvement.', 'advanced'),
('interpret', '해석하다', 'to explain', 'How do you interpret this?', 'advanced'),
('intervene', '개입하다', 'to interfere', 'The government may intervene.', 'advanced'),
('intrinsic', '본질적인', 'inherent', 'This has intrinsic value.', 'advanced'),
('invoke', '요청하다', 'to call upon', 'Invoke the emergency clause.', 'advanced'),
('isolate', '고립시키다', 'to separate', 'Isolate the problem.', 'advanced'),
('layer', '층', 'level', 'Add another layer of security.', 'advanced'),
('lecture', '강의', 'talk', 'The professor gave a lecture.', 'advanced'),
('levy', '부과하다', 'to impose', 'The government will levy a tax.', 'advanced'),
('liberal', '자유주의의', 'open-minded', 'He has liberal views.', 'advanced'),
('license', '허가', 'permit', 'You need a license to drive.', 'advanced'),
('likewise', '마찬가지로', 'similarly', 'Likewise, we must act.', 'advanced'),
('logic', '논리', 'reasoning', 'Use logic to solve this.', 'advanced'),
('manipulate', '조작하다', 'to control', 'Do not manipulate the data.', 'advanced'),
('mechanism', '메커니즘', 'system', 'Explain the mechanism.', 'advanced');
