-- Add more beginner vocabulary words
INSERT INTO vocabulary_words (word, meaning_ko, pronunciation, part_of_speech, example_sentence, difficulty, category) VALUES
('friend', '친구', '/frend/', 'noun', 'She is my best friend.', 'beginner', 'nouns'),
('family', '가족', '/ˈfæməli/', 'noun', 'I love my family.', 'beginner', 'nouns'),
('school', '학교', '/skuːl/', 'noun', 'I go to school every day.', 'beginner', 'nouns'),
('teacher', '선생님', '/ˈtiːtʃər/', 'noun', 'Our teacher is very kind.', 'beginner', 'nouns'),
('student', '학생', '/ˈstjuːdənt/', 'noun', 'I am a student.', 'beginner', 'nouns'),
('food', '음식', '/fuːd/', 'noun', 'I like Korean food.', 'beginner', 'nouns'),
('music', '음악', '/ˈmjuːzɪk/', 'noun', 'I listen to music every day.', 'beginner', 'nouns'),
('movie', '영화', '/ˈmuːvi/', 'noun', 'Let''s watch a movie.', 'beginner', 'nouns'),
('phone', '전화기', '/foʊn/', 'noun', 'My phone is new.', 'beginner', 'nouns'),
('computer', '컴퓨터', '/kəmˈpjuːtər/', 'noun', 'I use a computer for work.', 'beginner', 'nouns'),

('good', '좋은', '/ɡʊd/', 'adjective', 'Have a good day!', 'beginner', 'adjectives'),
('bad', '나쁜', '/bæd/', 'adjective', 'That''s a bad idea.', 'beginner', 'adjectives'),
('big', '큰', '/bɪɡ/', 'adjective', 'This is a big house.', 'beginner', 'adjectives'),
('small', '작은', '/smɔːl/', 'adjective', 'I have a small car.', 'beginner', 'adjectives'),
('new', '새로운', '/nuː/', 'adjective', 'I bought a new bag.', 'beginner', 'adjectives'),
('old', '오래된', '/oʊld/', 'adjective', 'This is an old building.', 'beginner', 'adjectives'),
('hot', '뜨거운', '/hɑːt/', 'adjective', 'The coffee is hot.', 'beginner', 'adjectives'),
('cold', '차가운', '/koʊld/', 'adjective', 'It''s cold outside.', 'beginner', 'adjectives'),
('easy', '쉬운', '/ˈiːzi/', 'adjective', 'This test is easy.', 'beginner', 'adjectives'),
('difficult', '어려운', '/ˈdɪfɪkəlt/', 'adjective', 'Math is difficult for me.', 'beginner', 'adjectives'),

('go', '가다', '/ɡoʊ/', 'verb', 'Let''s go home.', 'beginner', 'verbs'),
('come', '오다', '/kʌm/', 'verb', 'Come here, please.', 'beginner', 'verbs'),
('eat', '먹다', '/iːt/', 'verb', 'I eat breakfast every morning.', 'beginner', 'verbs'),
('drink', '마시다', '/drɪŋk/', 'verb', 'I drink coffee every day.', 'beginner', 'verbs'),
('sleep', '자다', '/sliːp/', 'verb', 'I sleep 8 hours.', 'beginner', 'verbs'),
('study', '공부하다', '/ˈstʌdi/', 'verb', 'I study English.', 'beginner', 'verbs'),
('work', '일하다', '/wɜːrk/', 'verb', 'I work at a company.', 'beginner', 'verbs'),
('play', '놀다', '/pleɪ/', 'verb', 'Let''s play soccer.', 'beginner', 'verbs'),
('watch', '보다', '/wɑːtʃ/', 'verb', 'I watch TV.', 'beginner', 'verbs'),
('listen', '듣다', '/ˈlɪsən/', 'verb', 'Listen to the teacher.', 'beginner', 'verbs');

-- Add more intermediate vocabulary words  
INSERT INTO vocabulary_words (word, meaning_ko, pronunciation, part_of_speech, example_sentence, difficulty, category) VALUES
('environment', '환경', '/ɪnˈvaɪrənmənt/', 'noun', 'We need to protect the environment.', 'intermediate', 'nouns'),
('opportunity', '기회', '/ˌɑːpərˈtuːnəti/', 'noun', 'This is a great opportunity.', 'intermediate', 'nouns'),
('challenge', '도전', '/ˈtʃælɪndʒ/', 'noun', 'I love a good challenge.', 'intermediate', 'nouns'),
('decision', '결정', '/dɪˈsɪʒən/', 'noun', 'It was a difficult decision.', 'intermediate', 'nouns'),
('solution', '해결책', '/səˈluːʃən/', 'noun', 'We need to find a solution.', 'intermediate', 'nouns'),
('knowledge', '지식', '/ˈnɑːlɪdʒ/', 'noun', 'Knowledge is power.', 'intermediate', 'nouns'),
('relationship', '관계', '/rɪˈleɪʃənʃɪp/', 'noun', 'We have a good relationship.', 'intermediate', 'nouns'),
('responsibility', '책임', '/rɪˌspɑːnsəˈbɪləti/', 'noun', 'It''s your responsibility.', 'intermediate', 'nouns'),
('communication', '의사소통', '/kəˌmjuːnɪˈkeɪʃən/', 'noun', 'Good communication is important.', 'intermediate', 'nouns'),
('development', '발전', '/dɪˈveləpmənt/', 'noun', 'The development is going well.', 'intermediate', 'nouns'),

('effective', '효과적인', '/ɪˈfektɪv/', 'adjective', 'This is an effective method.', 'intermediate', 'adjectives'),
('efficient', '효율적인', '/ɪˈfɪʃənt/', 'adjective', 'We need an efficient system.', 'intermediate', 'adjectives'),
('confident', '자신감 있는', '/ˈkɑːnfɪdənt/', 'adjective', 'Be confident in yourself.', 'intermediate', 'adjectives'),
('flexible', '유연한', '/ˈfleksəbəl/', 'adjective', 'You need to be flexible.', 'intermediate', 'adjectives'),
('creative', '창의적인', '/kriˈeɪtɪv/', 'adjective', 'She is very creative.', 'intermediate', 'adjectives'),
('professional', '전문적인', '/prəˈfeʃənəl/', 'adjective', 'He is very professional.', 'intermediate', 'adjectives'),
('valuable', '가치 있는', '/ˈvæljuəbəl/', 'adjective', 'This is valuable information.', 'intermediate', 'adjectives'),
('reliable', '믿을 수 있는', '/rɪˈlaɪəbəl/', 'adjective', 'She is a reliable person.', 'intermediate', 'adjectives'),
('positive', '긍정적인', '/ˈpɑːzətɪv/', 'adjective', 'Stay positive!', 'intermediate', 'adjectives'),
('negative', '부정적인', '/ˈneɡətɪv/', 'adjective', 'Don''t be negative.', 'intermediate', 'adjectives'),

('improve', '향상시키다', '/ɪmˈpruːv/', 'verb', 'I want to improve my English.', 'intermediate', 'verbs'),
('develop', '개발하다', '/dɪˈveləp/', 'verb', 'We need to develop new ideas.', 'intermediate', 'verbs'),
('achieve', '달성하다', '/əˈtʃiːv/', 'verb', 'I achieved my goal.', 'intermediate', 'verbs'),
('manage', '관리하다', '/ˈmænɪdʒ/', 'verb', 'Can you manage the project?', 'intermediate', 'verbs'),
('organize', '조직하다', '/ˈɔːrɡənaɪz/', 'verb', 'Let''s organize the event.', 'intermediate', 'verbs'),
('communicate', '소통하다', '/kəˈmjuːnɪkeɪt/', 'verb', 'We communicate well.', 'intermediate', 'verbs'),
('participate', '참여하다', '/pɑːrˈtɪsɪpeɪt/', 'verb', 'Please participate in the meeting.', 'intermediate', 'verbs'),
('consider', '고려하다', '/kənˈsɪdər/', 'verb', 'Consider all options.', 'intermediate', 'verbs'),
('discover', '발견하다', '/dɪˈskʌvər/', 'verb', 'We discovered a new method.', 'intermediate', 'verbs'),
('influence', '영향을 미치다', '/ˈɪnfluəns/', 'verb', 'This will influence the result.', 'intermediate', 'verbs');

-- Add more advanced vocabulary words
INSERT INTO vocabulary_words (word, meaning_ko, pronunciation, part_of_speech, example_sentence, difficulty, category) VALUES
('phenomenon', '현상', '/fəˈnɑːmɪnən/', 'noun', 'This is an interesting phenomenon.', 'advanced', 'nouns'),
('hypothesis', '가설', '/haɪˈpɑːθəsɪs/', 'noun', 'We need to test this hypothesis.', 'advanced', 'nouns'),
('infrastructure', '기반 시설', '/ˈɪnfrəstrʌktʃər/', 'noun', 'The infrastructure needs improvement.', 'advanced', 'nouns'),
('implementation', '시행', '/ˌɪmplɪmenˈteɪʃən/', 'noun', 'The implementation was successful.', 'advanced', 'nouns'),
('methodology', '방법론', '/ˌmeθəˈdɑːlədʒi/', 'noun', 'What''s your methodology?', 'advanced', 'nouns'),
('paradigm', '패러다임', '/ˈpærədaɪm/', 'noun', 'This is a new paradigm.', 'advanced', 'nouns'),
('sustainability', '지속 가능성', '/səˌsteɪnəˈbɪləti/', 'noun', 'Sustainability is crucial.', 'advanced', 'nouns'),
('accountability', '책임성', '/əˌkaʊntəˈbɪləti/', 'noun', 'We need accountability.', 'advanced', 'nouns'),
('transparency', '투명성', '/trænsˈpærənsi/', 'noun', 'Transparency is important.', 'advanced', 'nouns'),
('complexity', '복잡성', '/kəmˈpleksəti/', 'noun', 'The complexity is overwhelming.', 'advanced', 'nouns'),

('comprehensive', '포괄적인', '/ˌkɑːmprɪˈhensɪv/', 'adjective', 'We need a comprehensive plan.', 'advanced', 'adjectives'),
('substantial', '상당한', '/səbˈstænʃəl/', 'adjective', 'There''s substantial evidence.', 'advanced', 'adjectives'),
('profound', '깊은', '/prəˈfaʊnd/', 'adjective', 'That''s a profound statement.', 'advanced', 'adjectives'),
('sophisticated', '세련된', '/səˈfɪstɪkeɪtɪd/', 'adjective', 'It''s a sophisticated system.', 'advanced', 'adjectives'),
('meticulous', '세심한', '/məˈtɪkjələs/', 'adjective', 'He is meticulous in his work.', 'advanced', 'adjectives'),
('strategic', '전략적인', '/strəˈtiːdʒɪk/', 'adjective', 'This is a strategic decision.', 'advanced', 'adjectives'),
('analytical', '분석적인', '/ˌænəˈlɪtɪkəl/', 'adjective', 'She has analytical skills.', 'advanced', 'adjectives'),
('fundamental', '근본적인', '/ˌfʌndəˈmentəl/', 'adjective', 'This is fundamental.', 'advanced', 'adjectives'),
('significant', '중요한', '/sɪɡˈnɪfɪkənt/', 'adjective', 'This is significant progress.', 'advanced', 'adjectives'),
('concurrent', '동시의', '/kənˈkɜːrənt/', 'adjective', 'These are concurrent events.', 'advanced', 'adjectives'),

('demonstrate', '입증하다', '/ˈdemənstreɪt/', 'verb', 'Can you demonstrate this?', 'advanced', 'verbs'),
('facilitate', '촉진하다', '/fəˈsɪlɪteɪt/', 'verb', 'This will facilitate the process.', 'advanced', 'verbs'),
('synthesize', '종합하다', '/ˈsɪnθəsaɪz/', 'verb', 'Synthesize the information.', 'advanced', 'verbs'),
('contemplate', '숙고하다', '/ˈkɑːntəmpleɪt/', 'verb', 'I need to contemplate this.', 'advanced', 'verbs'),
('integrate', '통합하다', '/ˈɪntɪɡreɪt/', 'verb', 'Let''s integrate these systems.', 'advanced', 'verbs'),
('optimize', '최적화하다', '/ˈɑːptɪmaɪz/', 'verb', 'We need to optimize performance.', 'advanced', 'verbs'),
('scrutinize', '면밀히 조사하다', '/ˈskruːtənaɪz/', 'verb', 'Scrutinize the details.', 'advanced', 'verbs'),
('advocate', '옹호하다', '/ˈædvəkeɪt/', 'verb', 'I advocate for change.', 'advanced', 'verbs'),
('consolidate', '통합하다', '/kənˈsɑːlɪdeɪt/', 'verb', 'Consolidate your resources.', 'advanced', 'verbs'),
('enumerate', '열거하다', '/ɪˈnuːməreɪt/', 'verb', 'Please enumerate the reasons.', 'advanced', 'verbs');
