-- Add toefl_related column to vocabulary_words
ALTER TABLE vocabulary_words ADD COLUMN toefl_related INTEGER DEFAULT 0;

-- Update existing words that are common in both TOEIC and TOEFL
UPDATE vocabulary_words SET toefl_related = 1 WHERE word IN (
  'accomplish', 'achievement', 'perspective', 'sophisticated', 'infrastructure',
  'technology', 'experience', 'opportunity', 'successful', 'effective'
);

-- Insert 200 TOEFL words (some overlap with TOEIC)
INSERT INTO vocabulary_words (word, part_of_speech, meaning_ko, pronunciation, example_sentence, difficulty, category, toeic_related, toefl_related) VALUES
-- Advanced TOEFL words (80 words)
('abandon', 'verb', '버리다, 포기하다', '/əˈbændən/', 'They had to abandon the project.', 'advanced', 'verbs', 0, 1),
('abstract', 'adjective', '추상적인', '/ˈæbstrækt/', 'Abstract concepts can be difficult.', 'advanced', 'adjectives', 1, 1),
('accumulate', 'verb', '축적하다', '/əˈkjuːmjəleɪt/', 'Dust accumulated on the shelf.', 'advanced', 'verbs', 1, 1),
('adequate', 'adjective', '적절한, 충분한', '/ˈædɪkwət/', 'We need adequate resources.', 'advanced', 'adjectives', 1, 1),
('adjacent', 'adjective', '인접한', '/əˈdʒeɪsənt/', 'The park is adjacent to the school.', 'advanced', 'adjectives', 1, 1),
('advocate', 'verb', '옹호하다', '/ˈædvəkeɪt/', 'She advocates for climate action.', 'advanced', 'verbs', 1, 1),
('aesthetic', 'adjective', '미적인', '/esˈθetɪk/', 'The design has aesthetic appeal.', 'advanced', 'adjectives', 0, 1),
('allocate', 'verb', '할당하다', '/ˈæləkeɪt/', 'We need to allocate resources.', 'advanced', 'verbs', 1, 1),
('ambiguous', 'adjective', '애매한', '/æmˈbɪɡjuəs/', 'The statement was ambiguous.', 'advanced', 'adjectives', 0, 1),
('analogous', 'adjective', '유사한', '/əˈnæləɡəs/', 'This situation is analogous.', 'advanced', 'adjectives', 0, 1),
('arbitrary', 'adjective', '임의의', '/ˈɑːrbɪtreri/', 'The decision seemed arbitrary.', 'advanced', 'adjectives', 0, 1),
('assemble', 'verb', '조립하다, 모으다', '/əˈsembl/', 'Please assemble the furniture.', 'advanced', 'verbs', 1, 1),
('assume', 'verb', '가정하다', '/əˈsuːm/', 'We cannot assume anything.', 'advanced', 'verbs', 1, 1),
('attribute', 'verb', '귀속시키다', '/əˈtrɪbjuːt/', 'We attribute success to hard work.', 'advanced', 'verbs', 1, 1),
('authentic', 'adjective', '진짜의', '/ɔːˈθentɪk/', 'This is an authentic painting.', 'advanced', 'adjectives', 1, 1),
('capacity', 'noun', '수용력, 능력', '/kəˈpæsəti/', 'The stadium has a large capacity.', 'advanced', 'nouns', 1, 1),
('coherent', 'adjective', '일관된', '/koʊˈhɪrənt/', 'Please provide a coherent argument.', 'advanced', 'adjectives', 0, 1),
('compatible', 'adjective', '호환되는', '/kəmˈpætəbl/', 'These systems are compatible.', 'advanced', 'adjectives', 1, 1),
('component', 'noun', '구성요소', '/kəmˈpoʊnənt/', 'Each component is important.', 'advanced', 'nouns', 1, 1),
('compound', 'noun', '화합물, 복합체', '/ˈkɑːmpaʊnd/', 'Water is a chemical compound.', 'advanced', 'nouns', 1, 1),
('conceive', 'verb', '생각하다, 임신하다', '/kənˈsiːv/', 'It is hard to conceive the idea.', 'advanced', 'verbs', 0, 1),
('conduct', 'verb', '수행하다', '/kənˈdʌkt/', 'They will conduct research.', 'advanced', 'verbs', 1, 1),
('consequent', 'adjective', '결과적인', '/ˈkɑːnsɪkwənt/', 'The consequent effects were severe.', 'advanced', 'adjectives', 0, 1),
('considerable', 'adjective', '상당한', '/kənˈsɪdərəbl/', 'There was considerable damage.', 'advanced', 'adjectives', 1, 1),
('consistent', 'adjective', '일관된', '/kənˈsɪstənt/', 'Be consistent in your approach.', 'advanced', 'adjectives', 1, 1),
('constrain', 'verb', '제약하다', '/kənˈstreɪn/', 'Budget constraints limit options.', 'advanced', 'verbs', 1, 1),
('contemporary', 'adjective', '현대의', '/kənˈtempəreri/', 'Contemporary art is diverse.', 'advanced', 'adjectives', 0, 1),
('contradict', 'verb', '모순되다', '/ˌkɑːntrəˈdɪkt/', 'These statements contradict each other.', 'advanced', 'verbs', 0, 1),
('crucial', 'adjective', '결정적인', '/ˈkruːʃl/', 'This is a crucial moment.', 'advanced', 'adjectives', 1, 1),
('deduct', 'verb', '공제하다', '/dɪˈdʌkt/', 'They will deduct taxes.', 'advanced', 'verbs', 1, 1),
('demonstrate', 'verb', '입증하다', '/ˈdemənstreɪt/', 'Let me demonstrate the process.', 'advanced', 'verbs', 1, 1),
('derive', 'verb', '유래하다', '/dɪˈraɪv/', 'The word derives from Latin.', 'advanced', 'verbs', 0, 1),
('dimension', 'noun', '차원, 크기', '/daɪˈmenʃn/', 'Consider every dimension.', 'advanced', 'nouns', 1, 1),
('diminish', 'verb', '줄어들다', '/dɪˈmɪnɪʃ/', 'The effects will diminish over time.', 'advanced', 'verbs', 0, 1),
('discrete', 'adjective', '별개의', '/dɪˈskriːt/', 'These are discrete categories.', 'advanced', 'adjectives', 0, 1),
('distinguish', 'verb', '구별하다', '/dɪˈstɪŋɡwɪʃ/', 'Can you distinguish the difference?', 'advanced', 'verbs', 0, 1),
('dominate', 'verb', '지배하다', '/ˈdɑːmɪneɪt/', 'They dominate the market.', 'advanced', 'verbs', 1, 1),
('duration', 'noun', '기간', '/dʊˈreɪʃn/', 'The duration was three hours.', 'advanced', 'nouns', 1, 1),
('eliminate', 'verb', '제거하다', '/ɪˈlɪmɪneɪt/', 'We need to eliminate errors.', 'advanced', 'verbs', 1, 1),
('emerge', 'verb', '나타나다', '/ɪˈmɜːrdʒ/', 'New patterns emerge.', 'advanced', 'verbs', 0, 1),
('emphasize', 'verb', '강조하다', '/ˈemfəsaɪz/', 'I want to emphasize this point.', 'advanced', 'verbs', 1, 1),
('empirical', 'adjective', '경험적인', '/ɪmˈpɪrɪkl/', 'We need empirical evidence.', 'advanced', 'adjectives', 0, 1),
('enable', 'verb', '가능하게 하다', '/ɪˈneɪbl/', 'Technology enables communication.', 'advanced', 'verbs', 1, 1),
('enforce', 'verb', '시행하다', '/ɪnˈfɔːrs/', 'They will enforce the law.', 'advanced', 'verbs', 1, 1),
('enhance', 'verb', '향상시키다', '/ɪnˈhæns/', 'This will enhance performance.', 'advanced', 'verbs', 1, 1),
('ensure', 'verb', '보장하다', '/ɪnˈʃʊr/', 'We must ensure safety.', 'advanced', 'verbs', 1, 1),
('entity', 'noun', '실체, 존재', '/ˈentəti/', 'The company is a legal entity.', 'advanced', 'nouns', 0, 1),
('equivalent', 'adjective', '동등한', '/ɪˈkwɪvələnt/', 'These are equivalent amounts.', 'advanced', 'adjectives', 1, 1),
('erode', 'verb', '침식하다', '/ɪˈroʊd/', 'Water can erode rock.', 'advanced', 'verbs', 0, 1),
('evaluate', 'verb', '평가하다', '/ɪˈvæljueɪt/', 'We need to evaluate the results.', 'advanced', 'verbs', 1, 1),
('evident', 'adjective', '명백한', '/ˈevɪdənt/', 'The truth is evident.', 'advanced', 'adjectives', 0, 1),
('evolve', 'verb', '진화하다', '/ɪˈvɑːlv/', 'Species evolve over time.', 'advanced', 'verbs', 0, 1),
('exceed', 'verb', '초과하다', '/ɪkˈsiːd/', 'Do not exceed the limit.', 'advanced', 'verbs', 1, 1),
('exclude', 'verb', '배제하다', '/ɪkˈskluːd/', 'We cannot exclude this possibility.', 'advanced', 'verbs', 1, 1),
('exhibit', 'verb', '전시하다, 나타내다', '/ɪɡˈzɪbɪt/', 'The museum will exhibit paintings.', 'advanced', 'verbs', 1, 1),
('expand', 'verb', '확장하다', '/ɪkˈspænd/', 'The company plans to expand.', 'advanced', 'verbs', 1, 1),
('explicit', 'adjective', '명시적인', '/ɪkˈsplɪsɪt/', 'Please be explicit about requirements.', 'advanced', 'adjectives', 0, 1),
('exploit', 'verb', '이용하다', '/ɪkˈsplɔɪt/', 'They exploit natural resources.', 'advanced', 'verbs', 0, 1),
('extract', 'verb', '추출하다', '/ɪkˈstrækt/', 'Extract the important data.', 'advanced', 'verbs', 0, 1),
('facilitate', 'verb', '용이하게 하다', '/fəˈsɪlɪteɪt/', 'This will facilitate learning.', 'advanced', 'verbs', 1, 1),
('finite', 'adjective', '유한한', '/ˈfaɪnaɪt/', 'Resources are finite.', 'advanced', 'adjectives', 0, 1),
('fluctuate', 'verb', '변동하다', '/ˈflʌktʃueɪt/', 'Prices fluctuate daily.', 'advanced', 'verbs', 0, 1),
('framework', 'noun', '틀, 체계', '/ˈfreɪmwɜːrk/', 'We need a clear framework.', 'advanced', 'nouns', 1, 1),
('fundamental', 'adjective', '근본적인', '/ˌfʌndəˈmentl/', 'These are fundamental principles.', 'advanced', 'adjectives', 0, 1),
('generate', 'verb', '생성하다', '/ˈdʒenəreɪt/', 'Solar panels generate electricity.', 'advanced', 'verbs', 1, 1),
('hypothesis', 'noun', '가설', '/haɪˈpɑːθəsɪs/', 'The hypothesis needs testing.', 'advanced', 'nouns', 0, 1),
('identical', 'adjective', '동일한', '/aɪˈdentɪkl/', 'The twins look identical.', 'advanced', 'adjectives', 0, 1),
('illustrate', 'verb', '설명하다', '/ˈɪləstreɪt/', 'Let me illustrate with an example.', 'advanced', 'verbs', 1, 1),
('implicit', 'adjective', '암묵적인', '/ɪmˈplɪsɪt/', 'There was an implicit agreement.', 'advanced', 'adjectives', 0, 1),
('impose', 'verb', '부과하다', '/ɪmˈpoʊz/', 'They will impose new taxes.', 'advanced', 'verbs', 1, 1),
('incentive', 'noun', '인센티브', '/ɪnˈsentɪv/', 'They offer financial incentives.', 'advanced', 'nouns', 1, 1),
('incline', 'verb', '기울다', '/ɪnˈklaɪn/', 'I incline to agree with you.', 'advanced', 'verbs', 0, 1),
('incorporate', 'verb', '통합하다', '/ɪnˈkɔːrpəreɪt/', 'We will incorporate your feedback.', 'advanced', 'verbs', 1, 1),
('index', 'noun', '색인, 지수', '/ˈɪndeks/', 'Check the index at the back.', 'advanced', 'nouns', 1, 1),
('indicate', 'verb', '나타내다', '/ˈɪndɪkeɪt/', 'The results indicate success.', 'advanced', 'verbs', 1, 1),
('induce', 'verb', '유도하다', '/ɪnˈduːs/', 'Stress can induce illness.', 'advanced', 'verbs', 0, 1),
('inevitable', 'adjective', '불가피한', '/ɪnˈevɪtəbl/', 'Change is inevitable.', 'advanced', 'adjectives', 0, 1),
('infer', 'verb', '추론하다', '/ɪnˈfɜːr/', 'We can infer from the data.', 'advanced', 'verbs', 0, 1),
('inhibit', 'verb', '억제하다', '/ɪnˈhɪbɪt/', 'This drug inhibits growth.', 'advanced', 'verbs', 0, 1),
('initial', 'adjective', '최초의', '/ɪˈnɪʃl/', 'The initial response was positive.', 'advanced', 'adjectives', 1, 1),

-- Intermediate TOEFL words (70 words)
('abandon', 'verb', '포기하다', '/əˈbændən/', 'Never abandon your dreams.', 'intermediate', 'verbs', 0, 1),
('access', 'noun', '접근', '/ˈækses/', 'Everyone should have access to education.', 'intermediate', 'nouns', 1, 1),
('achieve', 'verb', '달성하다', '/əˈtʃiːv/', 'You can achieve your goals.', 'intermediate', 'verbs', 1, 1),
('acquire', 'verb', '획득하다', '/əˈkwaɪər/', 'Children acquire language naturally.', 'intermediate', 'verbs', 1, 1),
('adapt', 'verb', '적응하다', '/əˈdæpt/', 'Animals adapt to their environment.', 'intermediate', 'verbs', 1, 1),
('adequate', 'adjective', '적절한', '/ˈædɪkwət/', 'Is this adequate for our needs?', 'intermediate', 'adjectives', 1, 1),
('administration', 'noun', '행정', '/ədˌmɪnɪˈstreɪʃn/', 'The administration approved the plan.', 'intermediate', 'nouns', 1, 1),
('adult', 'noun', '성인', '/əˈdʌlt/', 'This program is for adults only.', 'intermediate', 'nouns', 0, 1),
('advantage', 'noun', '이점', '/ədˈvæntɪdʒ/', 'There is a clear advantage.', 'intermediate', 'nouns', 1, 1),
('advice', 'noun', '조언', '/ədˈvaɪs/', 'Can you give me some advice?', 'intermediate', 'nouns', 1, 1),
('affect', 'verb', '영향을 주다', '/əˈfekt/', 'This will affect the outcome.', 'intermediate', 'verbs', 1, 1),
('alternative', 'noun', '대안', '/ɔːlˈtɜːrnətɪv/', 'We need an alternative solution.', 'intermediate', 'nouns', 1, 1),
('approach', 'noun', '접근법', '/əˈproʊtʃ/', 'What is your approach?', 'intermediate', 'nouns', 1, 1),
('appropriate', 'adjective', '적절한', '/əˈproʊpriət/', 'Choose appropriate words.', 'intermediate', 'adjectives', 1, 1),
('area', 'noun', '지역, 영역', '/ˈeriə/', 'This area needs improvement.', 'intermediate', 'nouns', 1, 1),
('aspect', 'noun', '측면', '/ˈæspekt/', 'Consider every aspect.', 'intermediate', 'nouns', 1, 1),
('assist', 'verb', '돕다', '/əˈsɪst/', 'Can I assist you?', 'intermediate', 'verbs', 1, 1),
('assume', 'verb', '가정하다', '/əˈsuːm/', 'Do not assume anything.', 'intermediate', 'verbs', 1, 1),
('attach', 'verb', '붙이다', '/əˈtætʃ/', 'Please attach the document.', 'intermediate', 'verbs', 1, 1),
('attain', 'verb', '달성하다', '/əˈteɪn/', 'They attained their objectives.', 'intermediate', 'verbs', 1, 1),
('attitude', 'noun', '태도', '/ˈætɪtuːd/', 'He has a positive attitude.', 'intermediate', 'nouns', 1, 1),
('authority', 'noun', '권위', '/əˈθɔːrəti/', 'She is an authority on the subject.', 'intermediate', 'nouns', 1, 1),
('available', 'adjective', '이용 가능한', '/əˈveɪləbl/', 'Is this still available?', 'intermediate', 'adjectives', 1, 1),
('aware', 'adjective', '알고 있는', '/əˈwer/', 'Are you aware of the risks?', 'intermediate', 'adjectives', 1, 1),
('benefit', 'noun', '혜택', '/ˈbenɪfɪt/', 'There are many benefits.', 'intermediate', 'nouns', 1, 1),
('capable', 'adjective', '유능한', '/ˈkeɪpəbl/', 'She is very capable.', 'intermediate', 'adjectives', 1, 1),
('category', 'noun', '범주', '/ˈkætəɡɔːri/', 'Which category does this fit?', 'intermediate', 'nouns', 1, 1),
('challenge', 'noun', '도전', '/ˈtʃælɪndʒ/', 'This is a big challenge.', 'intermediate', 'nouns', 1, 1),
('circumstance', 'noun', '상황', '/ˈsɜːrkəmstæns/', 'Under these circumstances...', 'intermediate', 'nouns', 1, 1),
('clarify', 'verb', '명확히 하다', '/ˈklærəfaɪ/', 'Please clarify your statement.', 'intermediate', 'verbs', 1, 1),
('collaborate', 'verb', '협력하다', '/kəˈlæbəreɪt/', 'We need to collaborate.', 'intermediate', 'verbs', 1, 1),
('commute', 'verb', '통근하다', '/kəˈmjuːt/', 'I commute to work daily.', 'intermediate', 'verbs', 1, 1),
('compare', 'verb', '비교하다', '/kəmˈper/', 'Let us compare the options.', 'intermediate', 'verbs', 1, 1),
('compensate', 'verb', '보상하다', '/ˈkɑːmpenseɪt/', 'They will compensate for damages.', 'intermediate', 'verbs', 1, 1),
('complex', 'adjective', '복잡한', '/kəmˈpleks/', 'This is a complex problem.', 'intermediate', 'adjectives', 1, 1),
('concept', 'noun', '개념', '/ˈkɑːnsept/', 'I understand the concept.', 'intermediate', 'nouns', 1, 1),
('conclude', 'verb', '결론짓다', '/kənˈkluːd/', 'What can we conclude?', 'intermediate', 'verbs', 1, 1),
('conference', 'noun', '회의', '/ˈkɑːnfərəns/', 'We have a conference tomorrow.', 'intermediate', 'nouns', 1, 1),
('confirm', 'verb', '확인하다', '/kənˈfɜːrm/', 'Please confirm your attendance.', 'intermediate', 'verbs', 1, 1),
('consequence', 'noun', '결과', '/ˈkɑːnsɪkwens/', 'Consider the consequences.', 'intermediate', 'nouns', 1, 1),
('consider', 'verb', '고려하다', '/kənˈsɪdər/', 'Please consider my proposal.', 'intermediate', 'verbs', 1, 1),
('consult', 'verb', '상담하다', '/kənˈsʌlt/', 'Consult with an expert.', 'intermediate', 'verbs', 1, 1),
('consume', 'verb', '소비하다', '/kənˈsuːm/', 'We consume too much energy.', 'intermediate', 'verbs', 1, 1),
('contact', 'verb', '연락하다', '/ˈkɑːntækt/', 'Please contact me soon.', 'intermediate', 'verbs', 1, 1),
('context', 'noun', '맥락', '/ˈkɑːntekst/', 'Understand the context.', 'intermediate', 'nouns', 1, 1),
('contract', 'noun', '계약', '/ˈkɑːntrækt/', 'Sign the contract here.', 'intermediate', 'nouns', 1, 1),
('contribute', 'verb', '기여하다', '/kənˈtrɪbjuːt/', 'Everyone should contribute.', 'intermediate', 'verbs', 1, 1),
('convenient', 'adjective', '편리한', '/kənˈviːniənt/', 'This is very convenient.', 'intermediate', 'adjectives', 1, 1),
('convince', 'verb', '설득하다', '/kənˈvɪns/', 'Can you convince them?', 'intermediate', 'verbs', 1, 1),
('cooperate', 'verb', '협력하다', '/koʊˈɑːpəreɪt/', 'We must cooperate.', 'intermediate', 'verbs', 1, 1),
('create', 'verb', '창조하다', '/kriˈeɪt/', 'Let us create something new.', 'intermediate', 'verbs', 1, 1),
('criteria', 'noun', '기준', '/kraɪˈtɪriə/', 'What are the criteria?', 'intermediate', 'nouns', 1, 1),
('culture', 'noun', '문화', '/ˈkʌltʃər/', 'Every country has its culture.', 'intermediate', 'nouns', 1, 1),
('data', 'noun', '데이터', '/ˈdeɪtə/', 'We need more data.', 'intermediate', 'nouns', 1, 1),
('debate', 'noun', '토론', '/dɪˈbeɪt/', 'There is much debate on this.', 'intermediate', 'nouns', 1, 1),
('decade', 'noun', '10년', '/ˈdekeɪd/', 'This happened a decade ago.', 'intermediate', 'nouns', 1, 1),
('decline', 'verb', '거절하다, 감소하다', '/dɪˈklaɪn/', 'Sales declined last year.', 'intermediate', 'verbs', 1, 1),
('define', 'verb', '정의하다', '/dɪˈfaɪn/', 'How do you define success?', 'intermediate', 'verbs', 1, 1),
('demonstrate', 'verb', '증명하다', '/ˈdemənstreɪt/', 'Let me demonstrate.', 'intermediate', 'verbs', 1, 1),
('depend', 'verb', '의존하다', '/dɪˈpend/', 'It depends on the situation.', 'intermediate', 'verbs', 1, 1),
('design', 'noun', '디자인', '/dɪˈzaɪn/', 'I love this design.', 'intermediate', 'nouns', 1, 1),
('despite', 'preposition', '~에도 불구하고', '/dɪˈspaɪt/', 'Despite the rain, we went out.', 'intermediate', 'conjunctions', 1, 1),
('detect', 'verb', '탐지하다', '/dɪˈtekt/', 'Can you detect any problems?', 'intermediate', 'verbs', 1, 1),
('device', 'noun', '장치', '/dɪˈvaɪs/', 'This is a useful device.', 'intermediate', 'nouns', 1, 1),
('distribute', 'verb', '분배하다', '/dɪˈstrɪbjuːt/', 'Distribute the materials evenly.', 'intermediate', 'verbs', 1, 1),
('diverse', 'adjective', '다양한', '/daɪˈvɜːrs/', 'We have diverse opinions.', 'intermediate', 'adjectives', 1, 1),
('document', 'noun', '문서', '/ˈdɑːkjumənt/', 'Please read this document.', 'intermediate', 'nouns', 1, 1),
('domestic', 'adjective', '국내의', '/dəˈmestɪk/', 'This is for domestic use.', 'intermediate', 'adjectives', 1, 1),
('economy', 'noun', '경제', '/ɪˈkɑːnəmi/', 'The economy is growing.', 'intermediate', 'nouns', 1, 1),

-- Beginner TOEFL words (50 words)
('ability', 'noun', '능력', '/əˈbɪləti/', 'She has great ability.', 'beginner', 'nouns', 1, 1),
('accept', 'verb', '받아들이다', '/əkˈsept/', 'I accept your offer.', 'beginner', 'verbs', 1, 1),
('accident', 'noun', '사고', '/ˈæksɪdənt/', 'There was an accident.', 'beginner', 'nouns', 1, 1),
('activity', 'noun', '활동', '/ækˈtɪvəti/', 'What is your favorite activity?', 'beginner', 'nouns', 1, 1),
('actual', 'adjective', '실제의', '/ˈæktʃuəl/', 'What is the actual cost?', 'beginner', 'adjectives', 1, 1),
('address', 'noun', '주소', '/əˈdres/', 'What is your address?', 'beginner', 'nouns', 1, 1),
('admit', 'verb', '인정하다', '/ədˈmɪt/', 'I must admit I was wrong.', 'beginner', 'verbs', 1, 1),
('advance', 'verb', '나아가다', '/ədˈvæns/', 'We need to advance quickly.', 'beginner', 'verbs', 1, 1),
('advertise', 'verb', '광고하다', '/ˈædvərtaɪz/', 'They advertise on TV.', 'beginner', 'verbs', 1, 1),
('affect', 'verb', '영향을 주다', '/əˈfekt/', 'How will this affect us?', 'beginner', 'verbs', 1, 1),
('afford', 'verb', '여유가 있다', '/əˈfɔːrd/', 'Can you afford this?', 'beginner', 'verbs', 1, 1),
('agree', 'verb', '동의하다', '/əˈɡriː/', 'I agree with you.', 'beginner', 'verbs', 1, 1),
('allow', 'verb', '허락하다', '/əˈlaʊ/', 'We do not allow pets.', 'beginner', 'verbs', 1, 1),
('amount', 'noun', '양', '/əˈmaʊnt/', 'What is the total amount?', 'beginner', 'nouns', 1, 1),
('announce', 'verb', '발표하다', '/əˈnaʊns/', 'They will announce the winner.', 'beginner', 'verbs', 1, 1),
('answer', 'noun', '답', '/ˈænsər/', 'Do you know the answer?', 'beginner', 'nouns', 1, 1),
('appear', 'verb', '나타나다', '/əˈpɪr/', 'She will appear on TV.', 'beginner', 'verbs', 1, 1),
('apply', 'verb', '지원하다', '/əˈplaɪ/', 'I want to apply for this job.', 'beginner', 'verbs', 1, 1),
('appoint', 'verb', '임명하다', '/əˈpɔɪnt/', 'They will appoint a new manager.', 'beginner', 'verbs', 1, 1),
('appreciate', 'verb', '감사하다', '/əˈpriːʃieɪt/', 'I appreciate your help.', 'beginner', 'verbs', 1, 1),
('argue', 'verb', '논쟁하다', '/ˈɑːrɡjuː/', 'Do not argue with me.', 'beginner', 'verbs', 1, 1),
('arrange', 'verb', '배열하다', '/əˈreɪndʒ/', 'Please arrange the chairs.', 'beginner', 'verbs', 1, 1),
('article', 'noun', '기사, 물품', '/ˈɑːrtɪkl/', 'I read an interesting article.', 'beginner', 'nouns', 1, 1),
('attend', 'verb', '참석하다', '/əˈtend/', 'Will you attend the meeting?', 'beginner', 'verbs', 1, 1),
('attract', 'verb', '끌어당기다', '/əˈtrækt/', 'This will attract customers.', 'beginner', 'verbs', 1, 1),
('avoid', 'verb', '피하다', '/əˈvɔɪd/', 'Try to avoid mistakes.', 'beginner', 'verbs', 1, 1),
('balance', 'noun', '균형', '/ˈbæləns/', 'Maintain a good balance.', 'beginner', 'nouns', 1, 1),
('behave', 'verb', '행동하다', '/bɪˈheɪv/', 'Please behave well.', 'beginner', 'verbs', 1, 1),
('belong', 'verb', '속하다', '/bɪˈlɔːŋ/', 'This belongs to me.', 'beginner', 'verbs', 1, 1),
('borrow', 'verb', '빌리다', '/ˈbɑːroʊ/', 'Can I borrow your pen?', 'beginner', 'verbs', 1, 1),
('break', 'verb', '깨다', '/breɪk/', 'Do not break the glass.', 'beginner', 'verbs', 1, 1),
('budget', 'noun', '예산', '/ˈbʌdʒɪt/', 'What is your budget?', 'beginner', 'nouns', 1, 1),
('build', 'verb', '짓다', '/bɪld/', 'They will build a new house.', 'beginner', 'verbs', 1, 1),
('calm', 'adjective', '차분한', '/kɑːm/', 'Please stay calm.', 'beginner', 'adjectives', 1, 1),
('cancel', 'verb', '취소하다', '/ˈkænsl/', 'I need to cancel my appointment.', 'beginner', 'verbs', 1, 1),
('care', 'verb', '돌보다', '/ker/', 'I care about you.', 'beginner', 'verbs', 1, 1),
('cause', 'noun', '원인', '/kɔːz/', 'What is the cause?', 'beginner', 'nouns', 1, 1),
('certain', 'adjective', '확실한', '/ˈsɜːrtn/', 'Are you certain?', 'beginner', 'adjectives', 1, 1),
('change', 'verb', '바꾸다', '/tʃeɪndʒ/', 'Can you change this?', 'beginner', 'verbs', 1, 1),
('charge', 'verb', '청구하다', '/tʃɑːrdʒ/', 'How much do you charge?', 'beginner', 'verbs', 1, 1),
('check', 'verb', '확인하다', '/tʃek/', 'Please check your email.', 'beginner', 'verbs', 1, 1),
('choose', 'verb', '선택하다', '/tʃuːz/', 'Choose your favorite.', 'beginner', 'verbs', 1, 1),
('claim', 'verb', '주장하다', '/kleɪm/', 'He claims to be innocent.', 'beginner', 'verbs', 1, 1),
('clean', 'adjective', '깨끗한', '/kliːn/', 'The room is clean.', 'beginner', 'adjectives', 1, 1),
('clear', 'adjective', '명확한', '/klɪr/', 'Is that clear?', 'beginner', 'adjectives', 1, 1),
('close', 'verb', '닫다', '/kloʊz/', 'Please close the door.', 'beginner', 'verbs', 1, 1),
('collect', 'verb', '수집하다', '/kəˈlekt/', 'I collect stamps.', 'beginner', 'verbs', 1, 1),
('combine', 'verb', '결합하다', '/kəmˈbaɪn/', 'Combine the ingredients.', 'beginner', 'verbs', 1, 1),
('comment', 'noun', '논평', '/ˈkɑːment/', 'Do you have any comments?', 'beginner', 'nouns', 1, 1),
('commit', 'verb', '저지르다, 전념하다', '/kəˈmɪt/', 'Commit to your goals.', 'beginner', 'verbs', 1, 1);
