-- Add 500 more TOEIC words to reach approximately 588 TOEIC words total
-- This migration focuses on business, workplace, and professional English vocabulary

INSERT INTO vocabulary_words (word, part_of_speech, meaning_ko, pronunciation, example_sentence, difficulty, category, toeic_related, toefl_related) VALUES
-- Advanced TOEIC Business & Professional words (200 words)
('accelerate', 'verb', '가속화하다', '/əkˈseləreɪt/', 'We need to accelerate the process.', 'advanced', 'verbs', 1, 0),
('accommodate', 'verb', '수용하다', '/əˈkɑːmədeɪt/', 'The hotel can accommodate 200 guests.', 'advanced', 'verbs', 1, 1),
('accompany', 'verb', '동반하다', '/əˈkʌmpəni/', 'I will accompany you to the meeting.', 'advanced', 'verbs', 1, 0),
('accordance', 'noun', '일치', '/əˈkɔːrdns/', 'Act in accordance with the rules.', 'advanced', 'nouns', 1, 0),
('account', 'noun', '계정, 계좌', '/əˈkaʊnt/', 'Please check your account balance.', 'advanced', 'nouns', 1, 1),
('accountant', 'noun', '회계사', '/əˈkaʊntənt/', 'She works as an accountant.', 'advanced', 'nouns', 1, 0),
('accumulation', 'noun', '축적', '/əˌkjuːmjəˈleɪʃn/', 'The accumulation of wealth takes time.', 'advanced', 'nouns', 1, 0),
('accuracy', 'noun', '정확성', '/ˈækjərəsi/', 'Accuracy is crucial in accounting.', 'advanced', 'nouns', 1, 1),
('acknowledge', 'verb', '인정하다', '/əkˈnɑːlɪdʒ/', 'Please acknowledge receipt of this email.', 'advanced', 'verbs', 1, 1),
('acquisition', 'noun', '인수', '/ˌækwɪˈzɪʃn/', 'The company announced a major acquisition.', 'advanced', 'nouns', 1, 0),
('activate', 'verb', '활성화하다', '/ˈæktɪveɪt/', 'Click here to activate your account.', 'advanced', 'verbs', 1, 0),
('actual', 'adjective', '실제의', '/ˈæktʃuəl/', 'What is the actual cost?', 'advanced', 'adjectives', 1, 1),
('acute', 'adjective', '심각한', '/əˈkjuːt/', 'There is an acute shortage.', 'advanced', 'adjectives', 1, 0),
('adhere', 'verb', '고수하다', '/ədˈhɪr/', 'Please adhere to the guidelines.', 'advanced', 'verbs', 1, 0),
('adjacent', 'adjective', '인접한', '/əˈdʒeɪsənt/', 'The office is adjacent to the bank.', 'advanced', 'adjectives', 1, 1),
('adjust', 'verb', '조정하다', '/əˈdʒʌst/', 'You can adjust the settings.', 'advanced', 'verbs', 1, 1),
('administer', 'verb', '관리하다', '/ədˈmɪnɪstər/', 'Who will administer the program?', 'advanced', 'verbs', 1, 0),
('admission', 'noun', '입장', '/ədˈmɪʃn/', 'Admission is free for members.', 'advanced', 'nouns', 1, 1),
('adopt', 'verb', '채택하다', '/əˈdɑːpt/', 'The board will adopt the new policy.', 'advanced', 'verbs', 1, 1),
('adverse', 'adjective', '불리한', '/ədˈvɜːrs/', 'Adverse weather conditions delayed flights.', 'advanced', 'adjectives', 1, 0),
('advertise', 'verb', '광고하다', '/ˈædvərtaɪz/', 'We advertise in major newspapers.', 'advanced', 'verbs', 1, 1),
('advisory', 'adjective', '자문의', '/ədˈvaɪzəri/', 'She serves on the advisory board.', 'advanced', 'adjectives', 1, 0),
('affiliate', 'noun', '계열사', '/əˈfɪlieɪt/', 'Our affiliate in Tokyo handles sales.', 'advanced', 'nouns', 1, 0),
('agenda', 'noun', '의제', '/əˈdʒendə/', 'What is on the agenda today?', 'advanced', 'nouns', 1, 1),
('aggregate', 'adjective', '총계의', '/ˈæɡrɪɡət/', 'The aggregate total is impressive.', 'advanced', 'adjectives', 1, 0),
('alliance', 'noun', '동맹', '/əˈlaɪəns/', 'They formed a strategic alliance.', 'advanced', 'nouns', 1, 0),
('allocate', 'verb', '할당하다', '/ˈæləkeɪt/', 'We need to allocate more resources.', 'advanced', 'verbs', 1, 1),
('allowance', 'noun', '수당', '/əˈlaʊəns/', 'You will receive a travel allowance.', 'advanced', 'nouns', 1, 0),
('alter', 'verb', '변경하다', '/ˈɔːltər/', 'Can we alter the schedule?', 'advanced', 'verbs', 1, 1),
('alternative', 'noun', '대안', '/ɔːlˈtɜːrnətɪv/', 'We need an alternative plan.', 'advanced', 'nouns', 1, 1),
('amend', 'verb', '수정하다', '/əˈmend/', 'The contract needs to be amended.', 'advanced', 'verbs', 1, 0),
('ample', 'adjective', '충분한', '/ˈæmpl/', 'There is ample parking space.', 'advanced', 'adjectives', 1, 0),
('analyze', 'verb', '분석하다', '/ˈænəlaɪz/', 'Let us analyze the data.', 'advanced', 'verbs', 1, 1),
('annual', 'adjective', '연례의', '/ˈænjuəl/', 'We hold an annual conference.', 'advanced', 'adjectives', 1, 1),
('anticipate', 'verb', '예상하다', '/ænˈtɪsɪpeɪt/', 'We anticipate strong sales.', 'advanced', 'verbs', 1, 1),
('apologize', 'verb', '사과하다', '/əˈpɑːlədʒaɪz/', 'I apologize for the delay.', 'advanced', 'verbs', 1, 0),
('apparent', 'adjective', '명백한', '/əˈpærənt/', 'The reason is apparent.', 'advanced', 'adjectives', 1, 1),
('appeal', 'noun', '호소', '/əˈpiːl/', 'The product has wide appeal.', 'advanced', 'nouns', 1, 1),
('applicable', 'adjective', '적용 가능한', '/ˈæplɪkəbl/', 'This rule is not applicable here.', 'advanced', 'adjectives', 1, 0),
('applicant', 'noun', '지원자', '/ˈæplɪkənt/', 'We received 100 applicants.', 'advanced', 'nouns', 1, 1),
('appraisal', 'noun', '평가', '/əˈpreɪzl/', 'Your annual appraisal is next week.', 'advanced', 'nouns', 1, 0),
('appreciable', 'adjective', '상당한', '/əˈpriːʃəbl/', 'There was appreciable growth.', 'advanced', 'adjectives', 1, 0),
('appreciation', 'noun', '감사', '/əˌpriːʃiˈeɪʃn/', 'I express my appreciation.', 'advanced', 'nouns', 1, 0),
('apprentice', 'noun', '견습생', '/əˈprentɪs/', 'He started as an apprentice.', 'advanced', 'nouns', 1, 0),
('approval', 'noun', '승인', '/əˈpruːvl/', 'We need management approval.', 'advanced', 'nouns', 1, 1),
('approve', 'verb', '승인하다', '/əˈpruːv/', 'The board will approve the budget.', 'advanced', 'verbs', 1, 1),
('approximate', 'adjective', '대략의', '/əˈprɑːksɪmət/', 'What is the approximate cost?', 'advanced', 'adjectives', 1, 1),
('arbitrary', 'adjective', '임의의', '/ˈɑːrbɪtreri/', 'The decision was not arbitrary.', 'advanced', 'adjectives', 1, 1),
('architect', 'noun', '건축가', '/ˈɑːrkɪtekt/', 'She is a renowned architect.', 'advanced', 'nouns', 1, 0),
('archive', 'noun', '기록 보관소', '/ˈɑːrkaɪv/', 'Check the company archives.', 'advanced', 'nouns', 1, 0),
('arise', 'verb', '발생하다', '/əˈraɪz/', 'Problems may arise.', 'advanced', 'verbs', 1, 1),
('array', 'noun', '배열', '/əˈreɪ/', 'There is an array of options.', 'advanced', 'nouns', 1, 0),
('artifact', 'noun', '유물', '/ˈɑːrtɪfækt/', 'The museum displays ancient artifacts.', 'advanced', 'nouns', 1, 0),
('ascertain', 'verb', '확인하다', '/ˌæsərˈteɪn/', 'We need to ascertain the facts.', 'advanced', 'verbs', 1, 0),
('aspire', 'verb', '열망하다', '/əˈspaɪər/', 'I aspire to be a manager.', 'advanced', 'verbs', 1, 0),
('assess', 'verb', '평가하다', '/əˈses/', 'We need to assess the situation.', 'advanced', 'verbs', 1, 1),
('asset', 'noun', '자산', '/ˈæset/', 'The company has valuable assets.', 'advanced', 'nouns', 1, 1),
('assign', 'verb', '할당하다', '/əˈsaɪn/', 'I will assign tasks to the team.', 'advanced', 'verbs', 1, 1),
('assignment', 'noun', '과제', '/əˈsaɪnmənt/', 'Complete the assignment by Friday.', 'advanced', 'nouns', 1, 1),
('assurance', 'noun', '보증', '/əˈʃʊrəns/', 'We give you our assurance.', 'advanced', 'nouns', 1, 0),
('assure', 'verb', '확신시키다', '/əˈʃʊr/', 'I assure you it is safe.', 'advanced', 'verbs', 1, 1),
('attainment', 'noun', '달성', '/əˈteɪnmənt/', 'The attainment of goals is important.', 'advanced', 'nouns', 1, 0),
('attempt', 'verb', '시도하다', '/əˈtempt/', 'I will attempt to solve this.', 'advanced', 'verbs', 1, 1),
('attendee', 'noun', '참석자', '/əˌtenˈdiː/', 'All attendees received certificates.', 'advanced', 'nouns', 1, 0),
('attorney', 'noun', '변호사', '/əˈtɜːrni/', 'Consult your attorney.', 'advanced', 'nouns', 1, 0),
('attribute', 'noun', '속성', '/ˈætrɪbjuːt/', 'Leadership is a key attribute.', 'advanced', 'nouns', 1, 1),
('audit', 'noun', '감사', '/ˈɔːdɪt/', 'The annual audit begins tomorrow.', 'advanced', 'nouns', 1, 0),
('auditor', 'noun', '감사원', '/ˈɔːdɪtər/', 'The auditor found no errors.', 'advanced', 'nouns', 1, 0),
('augment', 'verb', '증대하다', '/ɔːɡˈment/', 'We need to augment our staff.', 'advanced', 'verbs', 1, 0),
('authentic', 'adjective', '진정한', '/ɔːˈθentɪk/', 'This is authentic Italian cuisine.', 'advanced', 'adjectives', 1, 1),
('authorization', 'noun', '승인', '/ˌɔːθərəˈzeɪʃn/', 'You need authorization to access.', 'advanced', 'nouns', 1, 0),
('authorize', 'verb', '권한을 부여하다', '/ˈɔːθəraɪz/', 'Who authorized this purchase?', 'advanced', 'verbs', 1, 1),
('automate', 'verb', '자동화하다', '/ˈɔːtəmeɪt/', 'We plan to automate the process.', 'advanced', 'verbs', 1, 0),
('autonomy', 'noun', '자율성', '/ɔːˈtɑːnəmi/', 'Employees have more autonomy.', 'advanced', 'nouns', 1, 0),
('auxiliary', 'adjective', '보조의', '/ɔːɡˈzɪliəri/', 'We need auxiliary staff.', 'advanced', 'adjectives', 1, 0),
('avail', 'verb', '이용하다', '/əˈveɪl/', 'Avail yourself of this opportunity.', 'advanced', 'verbs', 1, 0),
('availability', 'noun', '이용 가능성', '/əˌveɪləˈbɪləti/', 'Check product availability online.', 'advanced', 'nouns', 1, 1),
('avenue', 'noun', '방법, 길', '/ˈævənuː/', 'We explored every avenue.', 'advanced', 'nouns', 1, 1),
('averse', 'adjective', '반대하는', '/əˈvɜːrs/', 'He is averse to risk.', 'advanced', 'adjectives', 1, 0),
('aviation', 'noun', '항공', '/ˌeɪviˈeɪʃn/', 'The aviation industry is growing.', 'advanced', 'nouns', 1, 0),
('await', 'verb', '기다리다', '/əˈweɪt/', 'We await your response.', 'advanced', 'verbs', 1, 0),
('award', 'noun', '상', '/əˈwɔːrd/', 'She won the employee award.', 'advanced', 'nouns', 1, 1),
('backdrop', 'noun', '배경', '/ˈbækdrɑːp/', 'This happens against a backdrop of change.', 'advanced', 'nouns', 1, 0),
('backlog', 'noun', '밀린 일', '/ˈbæklɔːɡ/', 'We have a backlog of orders.', 'advanced', 'nouns', 1, 0),
('backup', 'noun', '백업', '/ˈbækʌp/', 'Always keep a backup copy.', 'advanced', 'nouns', 1, 0),
('bail', 'noun', '보석금', '/beɪl/', 'Bail was set at $10,000.', 'advanced', 'nouns', 1, 0),
('ballot', 'noun', '투표', '/ˈbælət/', 'Cast your ballot here.', 'advanced', 'nouns', 1, 0),
('bankrupt', 'adjective', '파산한', '/ˈbæŋkrʌpt/', 'The company went bankrupt.', 'advanced', 'adjectives', 1, 0),
('bankruptcy', 'noun', '파산', '/ˈbæŋkrʌptsi/', 'They filed for bankruptcy.', 'advanced', 'nouns', 1, 0),
('bargain', 'noun', '거래', '/ˈbɑːrɡɪn/', 'This is a good bargain.', 'advanced', 'nouns', 1, 0),
('barrier', 'noun', '장벽', '/ˈbæriər/', 'Language is not a barrier.', 'advanced', 'nouns', 1, 1),
('baseline', 'noun', '기준선', '/ˈbeɪslaɪn/', 'Establish a baseline first.', 'advanced', 'nouns', 1, 0),
('benchmark', 'noun', '기준', '/ˈbentʃmɑːrk/', 'This sets a new benchmark.', 'advanced', 'nouns', 1, 0),
('beneficial', 'adjective', '유익한', '/ˌbenɪˈfɪʃl/', 'This is beneficial for all.', 'advanced', 'adjectives', 1, 1),
('beneficiary', 'noun', '수혜자', '/ˌbenɪˈfɪʃieri/', 'Who is the beneficiary?', 'advanced', 'nouns', 1, 0),
('bilateral', 'adjective', '양자간의', '/baɪˈlætərəl/', 'They signed a bilateral agreement.', 'advanced', 'adjectives', 1, 0),
('binding', 'adjective', '구속력 있는', '/ˈbaɪndɪŋ/', 'This contract is legally binding.', 'advanced', 'adjectives', 1, 0),
('biweekly', 'adjective', '격주의', '/baɪˈwiːkli/', 'We have biweekly meetings.', 'advanced', 'adjectives', 1, 0),
('board', 'noun', '이사회', '/bɔːrd/', 'The board approved the plan.', 'advanced', 'nouns', 1, 1),
('bonus', 'noun', '보너스', '/ˈboʊnəs/', 'Employees received a year-end bonus.', 'advanced', 'nouns', 1, 0),
('boom', 'noun', '호황', '/buːm/', 'The economy is experiencing a boom.', 'advanced', 'nouns', 1, 0),

-- Intermediate TOEIC words (200 words)
('branch', 'noun', '지점', '/bræntʃ/', 'Our branch office is downtown.', 'intermediate', 'nouns', 1, 0),
('brand', 'noun', '브랜드', '/brænd/', 'This is a well-known brand.', 'intermediate', 'nouns', 1, 1),
('breach', 'noun', '위반', '/briːtʃ/', 'This is a breach of contract.', 'intermediate', 'nouns', 1, 0),
('breakdown', 'noun', '고장', '/ˈbreɪkdaʊn/', 'There was a system breakdown.', 'intermediate', 'nouns', 1, 0),
('breakthrough', 'noun', '돌파구', '/ˈbreɪkθruː/', 'Scientists made a breakthrough.', 'intermediate', 'nouns', 1, 0),
('brief', 'adjective', '간단한', '/briːf/', 'Please give a brief summary.', 'intermediate', 'adjectives', 1, 1),
('briefing', 'noun', '브리핑', '/ˈbriːfɪŋ/', 'Attend the morning briefing.', 'intermediate', 'nouns', 1, 0),
('brochure', 'noun', '브로셔', '/broʊˈʃʊr/', 'Take a brochure with you.', 'intermediate', 'nouns', 1, 0),
('browse', 'verb', '둘러보다', '/braʊz/', 'Feel free to browse our website.', 'intermediate', 'verbs', 1, 0),
('bulk', 'noun', '대량', '/bʌlk/', 'We buy in bulk to save money.', 'intermediate', 'nouns', 1, 0),
('bureau', 'noun', '사무국', '/ˈbjʊroʊ/', 'Contact the information bureau.', 'intermediate', 'nouns', 1, 0),
('bureaucracy', 'noun', '관료제', '/bjʊˈrɑːkrəsi/', 'Too much bureaucracy slows progress.', 'intermediate', 'nouns', 1, 0),
('campaign', 'noun', '캠페인', '/kæmˈpeɪn/', 'Our marketing campaign was successful.', 'intermediate', 'nouns', 1, 1),
('candidate', 'noun', '후보자', '/ˈkændɪdeɪt/', 'She is a strong candidate.', 'intermediate', 'nouns', 1, 1),
('capacity', 'noun', '용량', '/kəˈpæsəti/', 'The hall has a 500-person capacity.', 'intermediate', 'nouns', 1, 1),
('capital', 'noun', '자본', '/ˈkæpɪtl/', 'We need more capital to expand.', 'intermediate', 'nouns', 1, 1),
('carrier', 'noun', '운송업자', '/ˈkæriər/', 'Choose a reliable carrier.', 'intermediate', 'nouns', 1, 0),
('catalog', 'noun', '목록', '/ˈkætəlɔːɡ/', 'Browse our online catalog.', 'intermediate', 'nouns', 1, 0),
('catering', 'noun', '케이터링', '/ˈkeɪtərɪŋ/', 'We provide catering services.', 'intermediate', 'nouns', 1, 0),
('caution', 'noun', '주의', '/ˈkɔːʃn/', 'Proceed with caution.', 'intermediate', 'nouns', 1, 1),
('cease', 'verb', '중단하다', '/siːs/', 'They will cease operations.', 'intermediate', 'verbs', 1, 0),
('certificate', 'noun', '증명서', '/sərˈtɪfɪkət/', 'You will receive a certificate.', 'intermediate', 'nouns', 1, 1),
('certify', 'verb', '증명하다', '/ˈsɜːrtɪfaɪ/', 'This document certifies completion.', 'intermediate', 'verbs', 1, 0),
('chairman', 'noun', '의장', '/ˈtʃermən/', 'The chairman called the meeting.', 'intermediate', 'nouns', 1, 0),
('chamber', 'noun', '회의소', '/ˈtʃeɪmbər/', 'Join the chamber of commerce.', 'intermediate', 'nouns', 1, 0),
('chancellor', 'noun', '장관', '/ˈtʃænsələr/', 'The chancellor announced reforms.', 'intermediate', 'nouns', 1, 0),
('charge', 'noun', '요금', '/tʃɑːrdʒ/', 'There is no delivery charge.', 'intermediate', 'nouns', 1, 1),
('charter', 'noun', '헌장', '/ˈtʃɑːrtər/', 'The company charter was approved.', 'intermediate', 'nouns', 1, 0),
('checkout', 'noun', '계산대', '/ˈtʃekaʊt/', 'Please proceed to checkout.', 'intermediate', 'nouns', 1, 0),
('CircumStance', 'noun', '상황', '/ˈsɜːrkəmstæns/', 'Under the circumstances...', 'intermediate', 'nouns', 1, 1),
('cite', 'verb', '인용하다', '/saɪt/', 'Please cite your sources.', 'intermediate', 'verbs', 1, 1),
('civil', 'adjective', '민간의', '/ˈsɪvl/', 'This is a civil matter.', 'intermediate', 'adjectives', 1, 1),
('clause', 'noun', '조항', '/klɔːz/', 'Read the contract clause carefully.', 'intermediate', 'nouns', 1, 0),
('clearance', 'noun', '허가', '/ˈklɪrəns/', 'You need security clearance.', 'intermediate', 'nouns', 1, 0),
('client', 'noun', '고객', '/ˈklaɪənt/', 'Our clients are very satisfied.', 'intermediate', 'nouns', 1, 1),
('clientele', 'noun', '고객층', '/ˌklaɪənˈtel/', 'We have a loyal clientele.', 'intermediate', 'nouns', 1, 0),
('clinic', 'noun', '진료소', '/ˈklɪnɪk/', 'Visit our dental clinic.', 'intermediate', 'nouns', 1, 0),
('coalition', 'noun', '연합', '/ˌkoʊəˈlɪʃn/', 'They formed a coalition.', 'intermediate', 'nouns', 1, 0),
('code', 'noun', '규정', '/koʊd/', 'Follow the dress code.', 'intermediate', 'nouns', 1, 1),
('colleague', 'noun', '동료', '/ˈkɑːliːɡ/', 'My colleague will help you.', 'intermediate', 'nouns', 1, 1),
('collective', 'adjective', '집단의', '/kəˈlektɪv/', 'This was a collective effort.', 'intermediate', 'adjectives', 1, 1),
('collide', 'verb', '충돌하다', '/kəˈlaɪd/', 'The two cars collided.', 'intermediate', 'verbs', 1, 0),
('collision', 'noun', '충돌', '/kəˈlɪʒn/', 'There was a collision on the highway.', 'intermediate', 'nouns', 1, 0),
('column', 'noun', '칼럼', '/ˈkɑːləm/', 'She writes a weekly column.', 'intermediate', 'nouns', 1, 1),
('commence', 'verb', '시작하다', '/kəˈmens/', 'The meeting will commence at 9.', 'intermediate', 'verbs', 1, 0),
('commend', 'verb', '칭찬하다', '/kəˈmend/', 'I commend you for your effort.', 'intermediate', 'verbs', 1, 0),
('commentary', 'noun', '논평', '/ˈkɑːmənteri/', 'Read the expert commentary.', 'intermediate', 'nouns', 1, 0),
('commerce', 'noun', '상업', '/ˈkɑːmɜːrs/', 'E-commerce is growing rapidly.', 'intermediate', 'nouns', 1, 1),
('commercial', 'adjective', '상업의', '/kəˈmɜːrʃl/', 'This is a commercial property.', 'intermediate', 'adjectives', 1, 1),
('commission', 'noun', '수수료', '/kəˈmɪʃn/', 'Sales staff earn commission.', 'intermediate', 'nouns', 1, 1),
('commit', 'verb', '약속하다', '/kəˈmɪt/', 'We commit to quality service.', 'intermediate', 'verbs', 1, 1),
('commitment', 'noun', '약속', '/kəˈmɪtmənt/', 'This requires a long-term commitment.', 'intermediate', 'nouns', 1, 1),
('committee', 'noun', '위원회', '/kəˈmɪti/', 'Join the planning committee.', 'intermediate', 'nouns', 1, 1),
('commodity', 'noun', '상품', '/kəˈmɑːdəti/', 'Oil is a valuable commodity.', 'intermediate', 'nouns', 1, 0),
('communicate', 'verb', '의사소통하다', '/kəˈmjuːnɪkeɪt/', 'We communicate via email.', 'intermediate', 'verbs', 1, 1),
('community', 'noun', '지역사회', '/kəˈmjuːnəti/', 'Support your local community.', 'intermediate', 'nouns', 1, 1),
('commute', 'noun', '통근', '/kəˈmjuːt/', 'My daily commute is 30 minutes.', 'intermediate', 'nouns', 1, 1),
('compact', 'adjective', '소형의', '/kəmˈpækt/', 'This is a compact design.', 'intermediate', 'adjectives', 1, 0),
('companion', 'noun', '동반자', '/kəmˈpæniən/', 'She is my travel companion.', 'intermediate', 'nouns', 1, 0),
('comparable', 'adjective', '비교할 만한', '/ˈkɑːmpərəbl/', 'The quality is comparable.', 'intermediate', 'adjectives', 1, 1),
('comparative', 'adjective', '비교의', '/kəmˈpærətɪv/', 'Do a comparative analysis.', 'intermediate', 'adjectives', 1, 0),
('comparison', 'noun', '비교', '/kəmˈpærɪsn/', 'In comparison to last year...', 'intermediate', 'nouns', 1, 1),
('compartment', 'noun', '구획', '/kəmˈpɑːrtmənt/', 'Store items in the compartment.', 'intermediate', 'nouns', 1, 0),
('compassion', 'noun', '연민', '/kəmˈpæʃn/', 'Show compassion to others.', 'intermediate', 'nouns', 1, 0),
('compel', 'verb', '강요하다', '/kəmˈpel/', 'Nothing can compel me to agree.', 'intermediate', 'verbs', 1, 0),
('compensate', 'verb', '보상하다', '/ˈkɑːmpenseɪt/', 'We will compensate for the loss.', 'intermediate', 'verbs', 1, 1),
('compensation', 'noun', '보상', '/ˌkɑːmpenˈseɪʃn/', 'Seek compensation for damages.', 'intermediate', 'nouns', 1, 1),
('competence', 'noun', '능력', '/ˈkɑːmpɪtəns/', 'She has proven her competence.', 'intermediate', 'nouns', 1, 0),
('competent', 'adjective', '유능한', '/ˈkɑːmpɪtənt/', 'Hire competent staff.', 'intermediate', 'adjectives', 1, 1),
('competition', 'noun', '경쟁', '/ˌkɑːmpəˈtɪʃn/', 'The competition is fierce.', 'intermediate', 'nouns', 1, 1),
('competitive', 'adjective', '경쟁력 있는', '/kəmˈpetətɪv/', 'We offer competitive prices.', 'intermediate', 'adjectives', 1, 1),
('competitor', 'noun', '경쟁자', '/kəmˈpetɪtər/', 'Our main competitor is XYZ Corp.', 'intermediate', 'nouns', 1, 1),
('compile', 'verb', '편집하다', '/kəmˈpaɪl/', 'Compile a list of names.', 'intermediate', 'verbs', 1, 0),
('complain', 'verb', '불평하다', '/kəmˈpleɪn/', 'Customers may complain about service.', 'intermediate', 'verbs', 1, 1),
('complaint', 'noun', '불만', '/kəmˈpleɪnt/', 'File a formal complaint.', 'intermediate', 'nouns', 1, 1),
('complement', 'verb', '보완하다', '/ˈkɑːmplɪment/', 'These colors complement each other.', 'intermediate', 'verbs', 1, 0),
('complete', 'verb', '완료하다', '/kəmˈpliːt/', 'Please complete the form.', 'intermediate', 'verbs', 1, 1),
('completion', 'noun', '완료', '/kəmˈpliːʃn/', 'The project nears completion.', 'intermediate', 'nouns', 1, 1),
('complexity', 'noun', '복잡성', '/kəmˈpleksəti/', 'The complexity is challenging.', 'intermediate', 'nouns', 1, 1),
('compliance', 'noun', '준수', '/kəmˈplaɪəns/', 'Ensure regulatory compliance.', 'intermediate', 'nouns', 1, 0),
('complicate', 'verb', '복잡하게 하다', '/ˈkɑːmplɪkeɪt/', 'Do not complicate matters.', 'intermediate', 'verbs', 1, 0),
('complication', 'noun', '합병증', '/ˌkɑːmplɪˈkeɪʃn/', 'There were unexpected complications.', 'intermediate', 'nouns', 1, 0),
('compliment', 'noun', '칭찬', '/ˈkɑːmplɪmənt/', 'Thank you for the compliment.', 'intermediate', 'nouns', 1, 0),
('comply', 'verb', '따르다', '/kəmˈplaɪ/', 'You must comply with regulations.', 'intermediate', 'verbs', 1, 1),
('compose', 'verb', '구성하다', '/kəmˈpoʊz/', 'Water is composed of hydrogen and oxygen.', 'intermediate', 'verbs', 1, 1),
('composition', 'noun', '구성', '/ˌkɑːmpəˈzɪʃn/', 'Analyze the composition.', 'intermediate', 'nouns', 1, 1),
('compound', 'adjective', '복합의', '/ˈkɑːmpaʊnd/', 'This is a compound problem.', 'intermediate', 'adjectives', 1, 1),
('comprehend', 'verb', '이해하다', '/ˌkɑːmprɪˈhend/', 'Do you comprehend the instructions?', 'intermediate', 'verbs', 1, 1),
('comprehensive', 'adjective', '포괄적인', '/ˌkɑːmprɪˈhensɪv/', 'This is a comprehensive guide.', 'intermediate', 'adjectives', 1, 1),
('compress', 'verb', '압축하다', '/kəmˈpres/', 'Compress the files to save space.', 'intermediate', 'verbs', 1, 0),
('comprise', 'verb', '구성되다', '/kəmˈpraɪz/', 'The team comprises 10 members.', 'intermediate', 'verbs', 1, 1),
('compromise', 'noun', '타협', '/ˈkɑːmprəmaɪz/', 'We reached a compromise.', 'intermediate', 'nouns', 1, 1),
('compulsory', 'adjective', '의무적인', '/kəmˈpʌlsəri/', 'Attendance is compulsory.', 'intermediate', 'adjectives', 1, 0),
('compute', 'verb', '계산하다', '/kəmˈpjuːt/', 'Compute the total cost.', 'intermediate', 'verbs', 1, 0),
('conceal', 'verb', '숨기다', '/kənˈsiːl/', 'Do not conceal information.', 'intermediate', 'verbs', 1, 0),
('concede', 'verb', '인정하다', '/kənˈsiːd/', 'I concede that you are right.', 'intermediate', 'verbs', 1, 0),

-- Beginner TOEIC words (100 words)  
('concentrate', 'verb', '집중하다', '/ˈkɑːnsntreɪt/', 'Please concentrate on your work.', 'beginner', 'verbs', 1, 1),
('concern', 'noun', '걱정', '/kənˈsɜːrn/', 'Safety is our main concern.', 'beginner', 'nouns', 1, 1),
('concerned', 'adjective', '걱정하는', '/kənˈsɜːrnd/', 'I am concerned about this.', 'beginner', 'adjectives', 1, 1),
('concerning', 'preposition', '~에 관한', '/kənˈsɜːrnɪŋ/', 'I have questions concerning the policy.', 'beginner', 'conjunctions', 1, 0),
('conclude', 'verb', '결론짓다', '/kənˈkluːd/', 'Let me conclude my presentation.', 'beginner', 'verbs', 1, 1),
('conclusion', 'noun', '결론', '/kənˈkluːʒn/', 'What is your conclusion?', 'beginner', 'nouns', 1, 1),
('concrete', 'adjective', '구체적인', '/ˈkɑːnkriːt/', 'Give me a concrete example.', 'beginner', 'adjectives', 1, 1),
('condition', 'noun', '조건', '/kənˈdɪʃn/', 'What are the conditions?', 'beginner', 'nouns', 1, 1),
('conduct', 'noun', '행동', '/ˈkɑːndʌkt/', 'Professional conduct is expected.', 'beginner', 'nouns', 1, 1),
('confidence', 'noun', '자신감', '/ˈkɑːnfɪdəns/', 'She has great confidence.', 'beginner', 'nouns', 1, 1),
('confident', 'adjective', '자신 있는', '/ˈkɑːnfɪdənt/', 'I am confident we will succeed.', 'beginner', 'adjectives', 1, 1),
('confidential', 'adjective', '기밀의', '/ˌkɑːnfɪˈdenʃl/', 'This information is confidential.', 'beginner', 'adjectives', 1, 0),
('configuration', 'noun', '구성', '/kənˌfɪɡjəˈreɪʃn/', 'Check the system configuration.', 'beginner', 'nouns', 1, 0),
('confine', 'verb', '제한하다', '/kənˈfaɪn/', 'Please confine your comments.', 'beginner', 'verbs', 1, 0),
('confirm', 'verb', '확인하다', '/kənˈfɜːrm/', 'Please confirm your booking.', 'beginner', 'verbs', 1, 1),
('confirmation', 'noun', '확인', '/ˌkɑːnfərˈmeɪʃn/', 'You will receive confirmation by email.', 'beginner', 'nouns', 1, 1),
('conflict', 'noun', '갈등', '/ˈkɑːnflɪkt/', 'There is a schedule conflict.', 'beginner', 'nouns', 1, 1),
('conform', 'verb', '따르다', '/kənˈfɔːrm/', 'Products must conform to standards.', 'beginner', 'verbs', 1, 0),
('confront', 'verb', '직면하다', '/kənˈfrʌnt/', 'We must confront the problem.', 'beginner', 'verbs', 1, 0),
('confuse', 'verb', '혼란시키다', '/kənˈfjuːz/', 'Do not confuse the two concepts.', 'beginner', 'verbs', 1, 1),
('confusion', 'noun', '혼란', '/kənˈfjuːʒn/', 'There is some confusion about the schedule.', 'beginner', 'nouns', 1, 1),
('congratulate', 'verb', '축하하다', '/kənˈɡrætʃəleɪt/', 'I congratulate you on your success.', 'beginner', 'verbs', 1, 0),
('congratulation', 'noun', '축하', '/kənˌɡrætʃəˈleɪʃn/', 'Congratulations on your promotion!', 'beginner', 'nouns', 1, 0),
('connect', 'verb', '연결하다', '/kəˈnekt/', 'Connect the cable here.', 'beginner', 'verbs', 1, 1),
('connection', 'noun', '연결', '/kəˈnekʃn/', 'Check your internet connection.', 'beginner', 'nouns', 1, 1),
('consent', 'noun', '동의', '/kənˈsent/', 'We need your written consent.', 'beginner', 'nouns', 1, 1),
('consequence', 'noun', '결과', '/ˈkɑːnsɪkwens/', 'What are the consequences?', 'beginner', 'nouns', 1, 1),
('consequently', 'adverb', '결과적으로', '/ˈkɑːnsɪkwəntli/', 'Consequently, we must act now.', 'beginner', 'adverbs', 1, 1),
('conservative', 'adjective', '보수적인', '/kənˈsɜːrvətɪv/', 'Take a conservative approach.', 'beginner', 'adjectives', 1, 0),
('conserve', 'verb', '보존하다', '/kənˈsɜːrv/', 'Conserve energy and water.', 'beginner', 'verbs', 1, 0),
('consider', 'verb', '고려하다', '/kənˈsɪdər/', 'Please consider my proposal.', 'beginner', 'verbs', 1, 1),
('considerable', 'adjective', '상당한', '/kənˈsɪdərəbl/', 'We made considerable progress.', 'beginner', 'adjectives', 1, 1),
('considerably', 'adverb', '상당히', '/kənˈsɪdərəbli/', 'Prices have risen considerably.', 'beginner', 'adverbs', 1, 0),
('considerate', 'adjective', '사려 깊은', '/kənˈsɪdərət/', 'That was very considerate.', 'beginner', 'adjectives', 1, 0),
('consideration', 'noun', '고려', '/kənˌsɪdəˈreɪʃn/', 'Take this into consideration.', 'beginner', 'nouns', 1, 1),
('consist', 'verb', '구성되다', '/kənˈsɪst/', 'The team consists of 5 people.', 'beginner', 'verbs', 1, 1),
('consistent', 'adjective', '일관된', '/kənˈsɪstənt/', 'Be consistent in your approach.', 'beginner', 'adjectives', 1, 1),
('consolidate', 'verb', '통합하다', '/kənˈsɑːlɪdeɪt/', 'We will consolidate our offices.', 'beginner', 'verbs', 1, 0),
('constant', 'adjective', '지속적인', '/ˈkɑːnstənt/', 'There is constant noise.', 'beginner', 'adjectives', 1, 1),
('constantly', 'adverb', '끊임없이', '/ˈkɑːnstəntli/', 'He is constantly late.', 'beginner', 'adverbs', 1, 1),
('constitute', 'verb', '구성하다', '/ˈkɑːnstɪtuːt/', 'Women constitute 60% of students.', 'beginner', 'verbs', 1, 0),
('constitution', 'noun', '헌법', '/ˌkɑːnstɪˈtuːʃn/', 'The constitution protects rights.', 'beginner', 'nouns', 1, 0),
('constraint', 'noun', '제약', '/kənˈstreɪnt/', 'Budget constraints are tight.', 'beginner', 'nouns', 1, 1),
('construct', 'verb', '건설하다', '/kənˈstrʌkt/', 'They will construct a new building.', 'beginner', 'verbs', 1, 1),
('construction', 'noun', '건설', '/kənˈstrʌkʃn/', 'Construction begins next month.', 'beginner', 'nouns', 1, 1),
('consult', 'verb', '상담하다', '/kənˈsʌlt/', 'Consult your doctor.', 'beginner', 'verbs', 1, 1),
('consultant', 'noun', '컨설턴트', '/kənˈsʌltənt/', 'Hire a business consultant.', 'beginner', 'nouns', 1, 1),
('consultation', 'noun', '상담', '/ˌkɑːnslˈteɪʃn/', 'Schedule a consultation.', 'beginner', 'nouns', 1, 0),
('consume', 'verb', '소비하다', '/kənˈsuːm/', 'Americans consume a lot of coffee.', 'beginner', 'verbs', 1, 1),
('consumer', 'noun', '소비자', '/kənˈsuːmər/', 'Consumer demand is high.', 'beginner', 'nouns', 1, 1),
('consumption', 'noun', '소비', '/kənˈsʌmpʃn/', 'Reduce energy consumption.', 'beginner', 'nouns', 1, 1),
('contact', 'noun', '연락', '/ˈkɑːntækt/', 'Keep in contact with me.', 'beginner', 'nouns', 1, 1),
('contain', 'verb', '포함하다', '/kənˈteɪn/', 'This box contains documents.', 'beginner', 'verbs', 1, 1),
('container', 'noun', '용기', '/kənˈteɪnər/', 'Store food in containers.', 'beginner', 'nouns', 1, 1),
('contaminate', 'verb', '오염시키다', '/kənˈtæmɪneɪt/', 'Do not contaminate the water.', 'beginner', 'verbs', 1, 0),
('contemporary', 'adjective', '현대의', '/kənˈtempəreri/', 'This is contemporary art.', 'beginner', 'adjectives', 1, 1),
('content', 'noun', '내용', '/ˈkɑːntent/', 'Review the content carefully.', 'beginner', 'nouns', 1, 1),
('contest', 'noun', '경연', '/ˈkɑːntest/', 'Enter the photo contest.', 'beginner', 'nouns', 1, 1),
('context', 'noun', '맥락', '/ˈkɑːntekst/', 'Consider the context.', 'beginner', 'nouns', 1, 1),
('continent', 'noun', '대륙', '/ˈkɑːntɪnənt/', 'Africa is a large continent.', 'beginner', 'nouns', 1, 0),
('continental', 'adjective', '대륙의', '/ˌkɑːntɪˈnentl/', 'Enjoy a continental breakfast.', 'beginner', 'adjectives', 1, 0),
('continual', 'adjective', '계속되는', '/kənˈtɪnjuəl/', 'There were continual interruptions.', 'beginner', 'adjectives', 1, 0),
('continue', 'verb', '계속하다', '/kənˈtɪnjuː/', 'Please continue with your work.', 'beginner', 'verbs', 1, 1),
('continuous', 'adjective', '연속적인', '/kənˈtɪnjuəs/', 'Continuous improvement is key.', 'beginner', 'adjectives', 1, 1),
('contract', 'verb', '계약하다', '/ˈkɑːntrækt/', 'We contracted a new supplier.', 'beginner', 'verbs', 1, 1),
('contractor', 'noun', '계약자', '/ˈkɑːntræktər/', 'Hire a licensed contractor.', 'beginner', 'nouns', 1, 0),
('contrary', 'adjective', '반대의', '/ˈkɑːntreri/', 'On the contrary, I agree.', 'beginner', 'adjectives', 1, 1),
('contrast', 'noun', '대조', '/ˈkɑːntræst/', 'In contrast to last year...', 'beginner', 'nouns', 1, 1),
('contribute', 'verb', '기여하다', '/kənˈtrɪbjuːt/', 'Everyone should contribute ideas.', 'beginner', 'verbs', 1, 1),
('contribution', 'noun', '기여', '/ˌkɑːntrɪˈbjuːʃn/', 'Thank you for your contribution.', 'beginner', 'nouns', 1, 1),
('control', 'verb', '통제하다', '/kənˈtroʊl/', 'Control your expenses.', 'beginner', 'verbs', 1, 1),
('controversial', 'adjective', '논란의', '/ˌkɑːntrəˈvɜːrʃl/', 'This is a controversial topic.', 'beginner', 'adjectives', 1, 0),
('controversy', 'noun', '논란', '/ˈkɑːntrəvɜːrsi/', 'The decision caused controversy.', 'beginner', 'nouns', 1, 0),
('convenience', 'noun', '편의', '/kənˈviːniəns/', 'This provides great convenience.', 'beginner', 'nouns', 1, 1),
('convenient', 'adjective', '편리한', '/kənˈviːniənt/', 'Choose a convenient time.', 'beginner', 'adjectives', 1, 1),
('convention', 'noun', '관습', '/kənˈvenʃn/', 'Follow social conventions.', 'beginner', 'nouns', 1, 1),
('conventional', 'adjective', '전통적인', '/kənˈvenʃənl/', 'Use conventional methods.', 'beginner', 'adjectives', 1, 1),
('conversation', 'noun', '대화', '/ˌkɑːnvərˈseɪʃn/', 'We had a good conversation.', 'beginner', 'nouns', 1, 1),
('convert', 'verb', '전환하다', '/kənˈvɜːrt/', 'Convert dollars to euros.', 'beginner', 'verbs', 1, 1),
('convey', 'verb', '전달하다', '/kənˈveɪ/', 'Please convey my regards.', 'beginner', 'verbs', 1, 0),
('convince', 'verb', '설득하다', '/kənˈvɪns/', 'Try to convince them.', 'beginner', 'verbs', 1, 1),
('cooperate', 'verb', '협력하다', '/koʊˈɑːpəreɪt/', 'Let us cooperate on this.', 'beginner', 'verbs', 1, 1),
('cooperation', 'noun', '협력', '/koʊˌɑːpəˈreɪʃn/', 'Thank you for your cooperation.', 'beginner', 'nouns', 1, 1),
('cooperative', 'adjective', '협조적인', '/koʊˈɑːpərətɪv/', 'He is very cooperative.', 'beginner', 'adjectives', 1, 0),
('coordinate', 'verb', '조정하다', '/koʊˈɔːrdɪneɪt/', 'Coordinate the schedules.', 'beginner', 'verbs', 1, 1),
('coordination', 'noun', '조정', '/koʊˌɔːrdɪˈneɪʃn/', 'Good coordination is essential.', 'beginner', 'nouns', 1, 0),
('coordinator', 'noun', '조정자', '/koʊˈɔːrdɪneɪtər/', 'Contact the event coordinator.', 'beginner', 'nouns', 1, 0),
('copy', 'noun', '사본', '/ˈkɑːpi/', 'Make a copy of this document.', 'beginner', 'nouns', 1, 1),
('core', 'noun', '핵심', '/kɔːr/', 'This is the core issue.', 'beginner', 'nouns', 1, 1),
('corporate', 'adjective', '기업의', '/ˈkɔːrpərət/', 'This is our corporate policy.', 'beginner', 'adjectives', 1, 1),
('corporation', 'noun', '기업', '/ˌkɔːrpəˈreɪʃn/', 'She works for a large corporation.', 'beginner', 'nouns', 1, 1),
('correct', 'adjective', '올바른', '/kəˈrekt/', 'That is the correct answer.', 'beginner', 'adjectives', 1, 1),
('correction', 'noun', '수정', '/kəˈrekʃn/', 'Please make the necessary corrections.', 'beginner', 'nouns', 1, 1),
('correctly', 'adverb', '올바르게', '/kəˈrektli/', 'Answer the questions correctly.', 'beginner', 'adverbs', 1, 1),
('correspond', 'verb', '일치하다', '/ˌkɔːrəˈspɑːnd/', 'The results correspond to our predictions.', 'beginner', 'verbs', 1, 1),
('correspondence', 'noun', '서신', '/ˌkɔːrəˈspɑːndəns/', 'Handle all correspondence promptly.', 'beginner', 'nouns', 1, 0),
('correspondent', 'noun', '특파원', '/ˌkɔːrəˈspɑːndənt/', 'She is our foreign correspondent.', 'beginner', 'nouns', 1, 0);
